// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/types.proto
// Protobuf Java Version: 4.29.3

package com.callscreen.contracts.callscreen.common.v1;

/**
 * <pre>
 * AuditContext records who performed an action and from where. Attached to
 * records whose access must be individually accountable under DPDP.
 * </pre>
 *
 * Protobuf type {@code callscreen.common.v1.AuditContext}
 */
public final class AuditContext extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:callscreen.common.v1.AuditContext)
    AuditContextOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AuditContext.class.getName());
  }
  // Use AuditContext.newBuilder() to construct.
  private AuditContext(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AuditContext() {
    actorType_ = "";
    sourceIp_ = "";
    region_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_AuditContext_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_AuditContext_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.callscreen.contracts.callscreen.common.v1.AuditContext.class, com.callscreen.contracts.callscreen.common.v1.AuditContext.Builder.class);
  }

  private int bitField0_;
  public static final int ACTOR_FIELD_NUMBER = 1;
  private com.callscreen.contracts.callscreen.common.v1.ResourceId actor_;
  /**
   * <pre>
   * Identifier of the acting principal, whether an end user or an operator.
   * </pre>
   *
   * <code>.callscreen.common.v1.ResourceId actor = 1 [json_name = "actor"];</code>
   * @return Whether the actor field is set.
   */
  @java.lang.Override
  public boolean hasActor() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Identifier of the acting principal, whether an end user or an operator.
   * </pre>
   *
   * <code>.callscreen.common.v1.ResourceId actor = 1 [json_name = "actor"];</code>
   * @return The actor.
   */
  @java.lang.Override
  public com.callscreen.contracts.callscreen.common.v1.ResourceId getActor() {
    return actor_ == null ? com.callscreen.contracts.callscreen.common.v1.ResourceId.getDefaultInstance() : actor_;
  }
  /**
   * <pre>
   * Identifier of the acting principal, whether an end user or an operator.
   * </pre>
   *
   * <code>.callscreen.common.v1.ResourceId actor = 1 [json_name = "actor"];</code>
   */
  @java.lang.Override
  public com.callscreen.contracts.callscreen.common.v1.ResourceIdOrBuilder getActorOrBuilder() {
    return actor_ == null ? com.callscreen.contracts.callscreen.common.v1.ResourceId.getDefaultInstance() : actor_;
  }

  public static final int ACTOR_TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object actorType_ = "";
  /**
   * <pre>
   * Kind of principal, for example "user", "operator", "system".
   * </pre>
   *
   * <code>string actor_type = 2 [json_name = "actorType"];</code>
   * @return The actorType.
   */
  @java.lang.Override
  public java.lang.String getActorType() {
    java.lang.Object ref = actorType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      actorType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Kind of principal, for example "user", "operator", "system".
   * </pre>
   *
   * <code>string actor_type = 2 [json_name = "actorType"];</code>
   * @return The bytes for actorType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActorTypeBytes() {
    java.lang.Object ref = actorType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      actorType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OCCURRED_AT_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp occurredAt_;
  /**
   * <pre>
   * When the action occurred, as recorded by the server.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];</code>
   * @return Whether the occurredAt field is set.
   */
  @java.lang.Override
  public boolean hasOccurredAt() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * When the action occurred, as recorded by the server.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];</code>
   * @return The occurredAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getOccurredAt() {
    return occurredAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : occurredAt_;
  }
  /**
   * <pre>
   * When the action occurred, as recorded by the server.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getOccurredAtOrBuilder() {
    return occurredAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : occurredAt_;
  }

  public static final int SOURCE_IP_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceIp_ = "";
  /**
   * <pre>
   * Source network address of the actor.
   * </pre>
   *
   * <code>string source_ip = 4 [json_name = "sourceIp", (.callscreen.common.v1.field_classification) = { ... }</code>
   * @return The sourceIp.
   */
  @java.lang.Override
  public java.lang.String getSourceIp() {
    java.lang.Object ref = sourceIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceIp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Source network address of the actor.
   * </pre>
   *
   * <code>string source_ip = 4 [json_name = "sourceIp", (.callscreen.common.v1.field_classification) = { ... }</code>
   * @return The bytes for sourceIp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceIpBytes() {
    java.lang.Object ref = sourceIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REGION_FIELD_NUMBER = 5;
  private int region_ = 0;
  /**
   * <pre>
   * Region that served the request, for residency audit.
   * </pre>
   *
   * <code>.callscreen.common.v1.Region region = 5 [json_name = "region"];</code>
   * @return The enum numeric value on the wire for region.
   */
  @java.lang.Override public int getRegionValue() {
    return region_;
  }
  /**
   * <pre>
   * Region that served the request, for residency audit.
   * </pre>
   *
   * <code>.callscreen.common.v1.Region region = 5 [json_name = "region"];</code>
   * @return The region.
   */
  @java.lang.Override public com.callscreen.contracts.callscreen.common.v1.Region getRegion() {
    com.callscreen.contracts.callscreen.common.v1.Region result = com.callscreen.contracts.callscreen.common.v1.Region.forNumber(region_);
    return result == null ? com.callscreen.contracts.callscreen.common.v1.Region.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getActor());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, actorType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getOccurredAt());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceIp_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, sourceIp_);
    }
    if (region_ != com.callscreen.contracts.callscreen.common.v1.Region.REGION_UNSPECIFIED.getNumber()) {
      output.writeEnum(5, region_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getActor());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, actorType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getOccurredAt());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceIp_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, sourceIp_);
    }
    if (region_ != com.callscreen.contracts.callscreen.common.v1.Region.REGION_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, region_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.callscreen.contracts.callscreen.common.v1.AuditContext)) {
      return super.equals(obj);
    }
    com.callscreen.contracts.callscreen.common.v1.AuditContext other = (com.callscreen.contracts.callscreen.common.v1.AuditContext) obj;

    if (hasActor() != other.hasActor()) return false;
    if (hasActor()) {
      if (!getActor()
          .equals(other.getActor())) return false;
    }
    if (!getActorType()
        .equals(other.getActorType())) return false;
    if (hasOccurredAt() != other.hasOccurredAt()) return false;
    if (hasOccurredAt()) {
      if (!getOccurredAt()
          .equals(other.getOccurredAt())) return false;
    }
    if (!getSourceIp()
        .equals(other.getSourceIp())) return false;
    if (region_ != other.region_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasActor()) {
      hash = (37 * hash) + ACTOR_FIELD_NUMBER;
      hash = (53 * hash) + getActor().hashCode();
    }
    hash = (37 * hash) + ACTOR_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getActorType().hashCode();
    if (hasOccurredAt()) {
      hash = (37 * hash) + OCCURRED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getOccurredAt().hashCode();
    }
    hash = (37 * hash) + SOURCE_IP_FIELD_NUMBER;
    hash = (53 * hash) + getSourceIp().hashCode();
    hash = (37 * hash) + REGION_FIELD_NUMBER;
    hash = (53 * hash) + region_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.callscreen.contracts.callscreen.common.v1.AuditContext parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.AuditContext parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.AuditContext parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.AuditContext parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.AuditContext parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.AuditContext parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.AuditContext parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.callscreen.contracts.callscreen.common.v1.AuditContext parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.callscreen.contracts.callscreen.common.v1.AuditContext parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.callscreen.contracts.callscreen.common.v1.AuditContext parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.AuditContext parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.callscreen.contracts.callscreen.common.v1.AuditContext parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.callscreen.contracts.callscreen.common.v1.AuditContext prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * AuditContext records who performed an action and from where. Attached to
   * records whose access must be individually accountable under DPDP.
   * </pre>
   *
   * Protobuf type {@code callscreen.common.v1.AuditContext}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:callscreen.common.v1.AuditContext)
      com.callscreen.contracts.callscreen.common.v1.AuditContextOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_AuditContext_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_AuditContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.callscreen.contracts.callscreen.common.v1.AuditContext.class, com.callscreen.contracts.callscreen.common.v1.AuditContext.Builder.class);
    }

    // Construct using com.callscreen.contracts.callscreen.common.v1.AuditContext.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getActorFieldBuilder();
        getOccurredAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      actor_ = null;
      if (actorBuilder_ != null) {
        actorBuilder_.dispose();
        actorBuilder_ = null;
      }
      actorType_ = "";
      occurredAt_ = null;
      if (occurredAtBuilder_ != null) {
        occurredAtBuilder_.dispose();
        occurredAtBuilder_ = null;
      }
      sourceIp_ = "";
      region_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_AuditContext_descriptor;
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.AuditContext getDefaultInstanceForType() {
      return com.callscreen.contracts.callscreen.common.v1.AuditContext.getDefaultInstance();
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.AuditContext build() {
      com.callscreen.contracts.callscreen.common.v1.AuditContext result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.AuditContext buildPartial() {
      com.callscreen.contracts.callscreen.common.v1.AuditContext result = new com.callscreen.contracts.callscreen.common.v1.AuditContext(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.callscreen.contracts.callscreen.common.v1.AuditContext result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.actor_ = actorBuilder_ == null
            ? actor_
            : actorBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.actorType_ = actorType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.occurredAt_ = occurredAtBuilder_ == null
            ? occurredAt_
            : occurredAtBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sourceIp_ = sourceIp_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.region_ = region_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.callscreen.contracts.callscreen.common.v1.AuditContext) {
        return mergeFrom((com.callscreen.contracts.callscreen.common.v1.AuditContext)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.callscreen.contracts.callscreen.common.v1.AuditContext other) {
      if (other == com.callscreen.contracts.callscreen.common.v1.AuditContext.getDefaultInstance()) return this;
      if (other.hasActor()) {
        mergeActor(other.getActor());
      }
      if (!other.getActorType().isEmpty()) {
        actorType_ = other.actorType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasOccurredAt()) {
        mergeOccurredAt(other.getOccurredAt());
      }
      if (!other.getSourceIp().isEmpty()) {
        sourceIp_ = other.sourceIp_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.region_ != 0) {
        setRegionValue(other.getRegionValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getActorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              actorType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getOccurredAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              sourceIp_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              region_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.callscreen.contracts.callscreen.common.v1.ResourceId actor_;
    private com.google.protobuf.SingleFieldBuilder<
        com.callscreen.contracts.callscreen.common.v1.ResourceId, com.callscreen.contracts.callscreen.common.v1.ResourceId.Builder, com.callscreen.contracts.callscreen.common.v1.ResourceIdOrBuilder> actorBuilder_;
    /**
     * <pre>
     * Identifier of the acting principal, whether an end user or an operator.
     * </pre>
     *
     * <code>.callscreen.common.v1.ResourceId actor = 1 [json_name = "actor"];</code>
     * @return Whether the actor field is set.
     */
    public boolean hasActor() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Identifier of the acting principal, whether an end user or an operator.
     * </pre>
     *
     * <code>.callscreen.common.v1.ResourceId actor = 1 [json_name = "actor"];</code>
     * @return The actor.
     */
    public com.callscreen.contracts.callscreen.common.v1.ResourceId getActor() {
      if (actorBuilder_ == null) {
        return actor_ == null ? com.callscreen.contracts.callscreen.common.v1.ResourceId.getDefaultInstance() : actor_;
      } else {
        return actorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Identifier of the acting principal, whether an end user or an operator.
     * </pre>
     *
     * <code>.callscreen.common.v1.ResourceId actor = 1 [json_name = "actor"];</code>
     */
    public Builder setActor(com.callscreen.contracts.callscreen.common.v1.ResourceId value) {
      if (actorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actor_ = value;
      } else {
        actorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifier of the acting principal, whether an end user or an operator.
     * </pre>
     *
     * <code>.callscreen.common.v1.ResourceId actor = 1 [json_name = "actor"];</code>
     */
    public Builder setActor(
        com.callscreen.contracts.callscreen.common.v1.ResourceId.Builder builderForValue) {
      if (actorBuilder_ == null) {
        actor_ = builderForValue.build();
      } else {
        actorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifier of the acting principal, whether an end user or an operator.
     * </pre>
     *
     * <code>.callscreen.common.v1.ResourceId actor = 1 [json_name = "actor"];</code>
     */
    public Builder mergeActor(com.callscreen.contracts.callscreen.common.v1.ResourceId value) {
      if (actorBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          actor_ != null &&
          actor_ != com.callscreen.contracts.callscreen.common.v1.ResourceId.getDefaultInstance()) {
          getActorBuilder().mergeFrom(value);
        } else {
          actor_ = value;
        }
      } else {
        actorBuilder_.mergeFrom(value);
      }
      if (actor_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Identifier of the acting principal, whether an end user or an operator.
     * </pre>
     *
     * <code>.callscreen.common.v1.ResourceId actor = 1 [json_name = "actor"];</code>
     */
    public Builder clearActor() {
      bitField0_ = (bitField0_ & ~0x00000001);
      actor_ = null;
      if (actorBuilder_ != null) {
        actorBuilder_.dispose();
        actorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifier of the acting principal, whether an end user or an operator.
     * </pre>
     *
     * <code>.callscreen.common.v1.ResourceId actor = 1 [json_name = "actor"];</code>
     */
    public com.callscreen.contracts.callscreen.common.v1.ResourceId.Builder getActorBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getActorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Identifier of the acting principal, whether an end user or an operator.
     * </pre>
     *
     * <code>.callscreen.common.v1.ResourceId actor = 1 [json_name = "actor"];</code>
     */
    public com.callscreen.contracts.callscreen.common.v1.ResourceIdOrBuilder getActorOrBuilder() {
      if (actorBuilder_ != null) {
        return actorBuilder_.getMessageOrBuilder();
      } else {
        return actor_ == null ?
            com.callscreen.contracts.callscreen.common.v1.ResourceId.getDefaultInstance() : actor_;
      }
    }
    /**
     * <pre>
     * Identifier of the acting principal, whether an end user or an operator.
     * </pre>
     *
     * <code>.callscreen.common.v1.ResourceId actor = 1 [json_name = "actor"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.callscreen.contracts.callscreen.common.v1.ResourceId, com.callscreen.contracts.callscreen.common.v1.ResourceId.Builder, com.callscreen.contracts.callscreen.common.v1.ResourceIdOrBuilder> 
        getActorFieldBuilder() {
      if (actorBuilder_ == null) {
        actorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.callscreen.contracts.callscreen.common.v1.ResourceId, com.callscreen.contracts.callscreen.common.v1.ResourceId.Builder, com.callscreen.contracts.callscreen.common.v1.ResourceIdOrBuilder>(
                getActor(),
                getParentForChildren(),
                isClean());
        actor_ = null;
      }
      return actorBuilder_;
    }

    private java.lang.Object actorType_ = "";
    /**
     * <pre>
     * Kind of principal, for example "user", "operator", "system".
     * </pre>
     *
     * <code>string actor_type = 2 [json_name = "actorType"];</code>
     * @return The actorType.
     */
    public java.lang.String getActorType() {
      java.lang.Object ref = actorType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actorType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Kind of principal, for example "user", "operator", "system".
     * </pre>
     *
     * <code>string actor_type = 2 [json_name = "actorType"];</code>
     * @return The bytes for actorType.
     */
    public com.google.protobuf.ByteString
        getActorTypeBytes() {
      java.lang.Object ref = actorType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actorType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Kind of principal, for example "user", "operator", "system".
     * </pre>
     *
     * <code>string actor_type = 2 [json_name = "actorType"];</code>
     * @param value The actorType to set.
     * @return This builder for chaining.
     */
    public Builder setActorType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      actorType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Kind of principal, for example "user", "operator", "system".
     * </pre>
     *
     * <code>string actor_type = 2 [json_name = "actorType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearActorType() {
      actorType_ = getDefaultInstance().getActorType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Kind of principal, for example "user", "operator", "system".
     * </pre>
     *
     * <code>string actor_type = 2 [json_name = "actorType"];</code>
     * @param value The bytes for actorType to set.
     * @return This builder for chaining.
     */
    public Builder setActorTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      actorType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp occurredAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> occurredAtBuilder_;
    /**
     * <pre>
     * When the action occurred, as recorded by the server.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];</code>
     * @return Whether the occurredAt field is set.
     */
    public boolean hasOccurredAt() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * When the action occurred, as recorded by the server.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];</code>
     * @return The occurredAt.
     */
    public com.google.protobuf.Timestamp getOccurredAt() {
      if (occurredAtBuilder_ == null) {
        return occurredAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : occurredAt_;
      } else {
        return occurredAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * When the action occurred, as recorded by the server.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];</code>
     */
    public Builder setOccurredAt(com.google.protobuf.Timestamp value) {
      if (occurredAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        occurredAt_ = value;
      } else {
        occurredAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When the action occurred, as recorded by the server.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];</code>
     */
    public Builder setOccurredAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (occurredAtBuilder_ == null) {
        occurredAt_ = builderForValue.build();
      } else {
        occurredAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When the action occurred, as recorded by the server.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];</code>
     */
    public Builder mergeOccurredAt(com.google.protobuf.Timestamp value) {
      if (occurredAtBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          occurredAt_ != null &&
          occurredAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getOccurredAtBuilder().mergeFrom(value);
        } else {
          occurredAt_ = value;
        }
      } else {
        occurredAtBuilder_.mergeFrom(value);
      }
      if (occurredAt_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * When the action occurred, as recorded by the server.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];</code>
     */
    public Builder clearOccurredAt() {
      bitField0_ = (bitField0_ & ~0x00000004);
      occurredAt_ = null;
      if (occurredAtBuilder_ != null) {
        occurredAtBuilder_.dispose();
        occurredAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When the action occurred, as recorded by the server.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getOccurredAtBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getOccurredAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * When the action occurred, as recorded by the server.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getOccurredAtOrBuilder() {
      if (occurredAtBuilder_ != null) {
        return occurredAtBuilder_.getMessageOrBuilder();
      } else {
        return occurredAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : occurredAt_;
      }
    }
    /**
     * <pre>
     * When the action occurred, as recorded by the server.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getOccurredAtFieldBuilder() {
      if (occurredAtBuilder_ == null) {
        occurredAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getOccurredAt(),
                getParentForChildren(),
                isClean());
        occurredAt_ = null;
      }
      return occurredAtBuilder_;
    }

    private java.lang.Object sourceIp_ = "";
    /**
     * <pre>
     * Source network address of the actor.
     * </pre>
     *
     * <code>string source_ip = 4 [json_name = "sourceIp", (.callscreen.common.v1.field_classification) = { ... }</code>
     * @return The sourceIp.
     */
    public java.lang.String getSourceIp() {
      java.lang.Object ref = sourceIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Source network address of the actor.
     * </pre>
     *
     * <code>string source_ip = 4 [json_name = "sourceIp", (.callscreen.common.v1.field_classification) = { ... }</code>
     * @return The bytes for sourceIp.
     */
    public com.google.protobuf.ByteString
        getSourceIpBytes() {
      java.lang.Object ref = sourceIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Source network address of the actor.
     * </pre>
     *
     * <code>string source_ip = 4 [json_name = "sourceIp", (.callscreen.common.v1.field_classification) = { ... }</code>
     * @param value The sourceIp to set.
     * @return This builder for chaining.
     */
    public Builder setSourceIp(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceIp_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Source network address of the actor.
     * </pre>
     *
     * <code>string source_ip = 4 [json_name = "sourceIp", (.callscreen.common.v1.field_classification) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceIp() {
      sourceIp_ = getDefaultInstance().getSourceIp();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Source network address of the actor.
     * </pre>
     *
     * <code>string source_ip = 4 [json_name = "sourceIp", (.callscreen.common.v1.field_classification) = { ... }</code>
     * @param value The bytes for sourceIp to set.
     * @return This builder for chaining.
     */
    public Builder setSourceIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceIp_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int region_ = 0;
    /**
     * <pre>
     * Region that served the request, for residency audit.
     * </pre>
     *
     * <code>.callscreen.common.v1.Region region = 5 [json_name = "region"];</code>
     * @return The enum numeric value on the wire for region.
     */
    @java.lang.Override public int getRegionValue() {
      return region_;
    }
    /**
     * <pre>
     * Region that served the request, for residency audit.
     * </pre>
     *
     * <code>.callscreen.common.v1.Region region = 5 [json_name = "region"];</code>
     * @param value The enum numeric value on the wire for region to set.
     * @return This builder for chaining.
     */
    public Builder setRegionValue(int value) {
      region_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Region that served the request, for residency audit.
     * </pre>
     *
     * <code>.callscreen.common.v1.Region region = 5 [json_name = "region"];</code>
     * @return The region.
     */
    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.Region getRegion() {
      com.callscreen.contracts.callscreen.common.v1.Region result = com.callscreen.contracts.callscreen.common.v1.Region.forNumber(region_);
      return result == null ? com.callscreen.contracts.callscreen.common.v1.Region.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Region that served the request, for residency audit.
     * </pre>
     *
     * <code>.callscreen.common.v1.Region region = 5 [json_name = "region"];</code>
     * @param value The region to set.
     * @return This builder for chaining.
     */
    public Builder setRegion(com.callscreen.contracts.callscreen.common.v1.Region value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      region_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Region that served the request, for residency audit.
     * </pre>
     *
     * <code>.callscreen.common.v1.Region region = 5 [json_name = "region"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRegion() {
      bitField0_ = (bitField0_ & ~0x00000010);
      region_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:callscreen.common.v1.AuditContext)
  }

  // @@protoc_insertion_point(class_scope:callscreen.common.v1.AuditContext)
  private static final com.callscreen.contracts.callscreen.common.v1.AuditContext DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.callscreen.contracts.callscreen.common.v1.AuditContext();
  }

  public static com.callscreen.contracts.callscreen.common.v1.AuditContext getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuditContext>
      PARSER = new com.google.protobuf.AbstractParser<AuditContext>() {
    @java.lang.Override
    public AuditContext parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AuditContext> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuditContext> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.callscreen.contracts.callscreen.common.v1.AuditContext getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

