// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/types.proto
// Protobuf Java Version: 4.29.3

package com.callscreen.contracts.callscreen.common.v1;

public interface AuditContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:callscreen.common.v1.AuditContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Identifier of the acting principal, whether an end user or an operator.
   * </pre>
   *
   * <code>.callscreen.common.v1.ResourceId actor = 1 [json_name = "actor"];</code>
   * @return Whether the actor field is set.
   */
  boolean hasActor();
  /**
   * <pre>
   * Identifier of the acting principal, whether an end user or an operator.
   * </pre>
   *
   * <code>.callscreen.common.v1.ResourceId actor = 1 [json_name = "actor"];</code>
   * @return The actor.
   */
  com.callscreen.contracts.callscreen.common.v1.ResourceId getActor();
  /**
   * <pre>
   * Identifier of the acting principal, whether an end user or an operator.
   * </pre>
   *
   * <code>.callscreen.common.v1.ResourceId actor = 1 [json_name = "actor"];</code>
   */
  com.callscreen.contracts.callscreen.common.v1.ResourceIdOrBuilder getActorOrBuilder();

  /**
   * <pre>
   * Kind of principal, for example "user", "operator", "system".
   * </pre>
   *
   * <code>string actor_type = 2 [json_name = "actorType"];</code>
   * @return The actorType.
   */
  java.lang.String getActorType();
  /**
   * <pre>
   * Kind of principal, for example "user", "operator", "system".
   * </pre>
   *
   * <code>string actor_type = 2 [json_name = "actorType"];</code>
   * @return The bytes for actorType.
   */
  com.google.protobuf.ByteString
      getActorTypeBytes();

  /**
   * <pre>
   * When the action occurred, as recorded by the server.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];</code>
   * @return Whether the occurredAt field is set.
   */
  boolean hasOccurredAt();
  /**
   * <pre>
   * When the action occurred, as recorded by the server.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];</code>
   * @return The occurredAt.
   */
  com.google.protobuf.Timestamp getOccurredAt();
  /**
   * <pre>
   * When the action occurred, as recorded by the server.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getOccurredAtOrBuilder();

  /**
   * <pre>
   * Source network address of the actor.
   * </pre>
   *
   * <code>string source_ip = 4 [json_name = "sourceIp", (.callscreen.common.v1.field_classification) = { ... }</code>
   * @return The sourceIp.
   */
  java.lang.String getSourceIp();
  /**
   * <pre>
   * Source network address of the actor.
   * </pre>
   *
   * <code>string source_ip = 4 [json_name = "sourceIp", (.callscreen.common.v1.field_classification) = { ... }</code>
   * @return The bytes for sourceIp.
   */
  com.google.protobuf.ByteString
      getSourceIpBytes();

  /**
   * <pre>
   * Region that served the request, for residency audit.
   * </pre>
   *
   * <code>.callscreen.common.v1.Region region = 5 [json_name = "region"];</code>
   * @return The enum numeric value on the wire for region.
   */
  int getRegionValue();
  /**
   * <pre>
   * Region that served the request, for residency audit.
   * </pre>
   *
   * <code>.callscreen.common.v1.Region region = 5 [json_name = "region"];</code>
   * @return The region.
   */
  com.callscreen.contracts.callscreen.common.v1.Region getRegion();
}
