// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/types.proto
// Protobuf Java Version: 4.29.3

package com.callscreen.contracts.callscreen.common.v1;

/**
 * <pre>
 * ClientContext travels with every request originating from an end-user client.
 *
 * It is populated by the client SDK, validated at the edge, and then attached
 * to the request's trace so that any downstream failure can be attributed to a
 * specific app version, OS version and locale without a separate lookup.
 * </pre>
 *
 * Protobuf type {@code callscreen.common.v1.ClientContext}
 */
public final class ClientContext extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:callscreen.common.v1.ClientContext)
    ClientContextOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ClientContext.class.getName());
  }
  // Use ClientContext.newBuilder() to construct.
  private ClientContext(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ClientContext() {
    platform_ = 0;
    appVersion_ = "";
    osVersion_ = "";
    deviceModel_ = "";
    deviceManufacturer_ = "";
    locale_ = "";
    timezone_ = "";
    installId_ = "";
    networkType_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_ClientContext_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_ClientContext_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.callscreen.contracts.callscreen.common.v1.ClientContext.class, com.callscreen.contracts.callscreen.common.v1.ClientContext.Builder.class);
  }

  public static final int PLATFORM_FIELD_NUMBER = 1;
  private int platform_ = 0;
  /**
   * <pre>
   * Client family issuing the request.
   * </pre>
   *
   * <code>.callscreen.common.v1.Platform platform = 1 [json_name = "platform"];</code>
   * @return The enum numeric value on the wire for platform.
   */
  @java.lang.Override public int getPlatformValue() {
    return platform_;
  }
  /**
   * <pre>
   * Client family issuing the request.
   * </pre>
   *
   * <code>.callscreen.common.v1.Platform platform = 1 [json_name = "platform"];</code>
   * @return The platform.
   */
  @java.lang.Override public com.callscreen.contracts.callscreen.common.v1.Platform getPlatform() {
    com.callscreen.contracts.callscreen.common.v1.Platform result = com.callscreen.contracts.callscreen.common.v1.Platform.forNumber(platform_);
    return result == null ? com.callscreen.contracts.callscreen.common.v1.Platform.UNRECOGNIZED : result;
  }

  public static final int APP_VERSION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object appVersion_ = "";
  /**
   * <pre>
   * Application version name, for example "1.4.2". Used to enforce the minimum
   * supported version floor described in Phase 1 §14.
   * </pre>
   *
   * <code>string app_version = 2 [json_name = "appVersion"];</code>
   * @return The appVersion.
   */
  @java.lang.Override
  public java.lang.String getAppVersion() {
    java.lang.Object ref = appVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Application version name, for example "1.4.2". Used to enforce the minimum
   * supported version floor described in Phase 1 §14.
   * </pre>
   *
   * <code>string app_version = 2 [json_name = "appVersion"];</code>
   * @return The bytes for appVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppVersionBytes() {
    java.lang.Object ref = appVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APP_BUILD_FIELD_NUMBER = 3;
  private long appBuild_ = 0L;
  /**
   * <pre>
   * Monotonic build number. Unambiguous where `app_version` may be reused
   * across staged rollouts.
   * </pre>
   *
   * <code>int64 app_build = 3 [json_name = "appBuild"];</code>
   * @return The appBuild.
   */
  @java.lang.Override
  public long getAppBuild() {
    return appBuild_;
  }

  public static final int OS_VERSION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object osVersion_ = "";
  /**
   * <pre>
   * Operating system version string, for example "Android 14".
   * </pre>
   *
   * <code>string os_version = 4 [json_name = "osVersion"];</code>
   * @return The osVersion.
   */
  @java.lang.Override
  public java.lang.String getOsVersion() {
    java.lang.Object ref = osVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      osVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Operating system version string, for example "Android 14".
   * </pre>
   *
   * <code>string os_version = 4 [json_name = "osVersion"];</code>
   * @return The bytes for osVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOsVersionBytes() {
    java.lang.Object ref = osVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      osVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_MODEL_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object deviceModel_ = "";
  /**
   * <pre>
   * Device model identifier. Needed because telephony and audio behaviour
   * varies enormously across Android OEMs, and OEM-specific defects are a
   * recurring class of production incident.
   * </pre>
   *
   * <code>string device_model = 5 [json_name = "deviceModel"];</code>
   * @return The deviceModel.
   */
  @java.lang.Override
  public java.lang.String getDeviceModel() {
    java.lang.Object ref = deviceModel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceModel_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Device model identifier. Needed because telephony and audio behaviour
   * varies enormously across Android OEMs, and OEM-specific defects are a
   * recurring class of production incident.
   * </pre>
   *
   * <code>string device_model = 5 [json_name = "deviceModel"];</code>
   * @return The bytes for deviceModel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceModelBytes() {
    java.lang.Object ref = deviceModel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceModel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_MANUFACTURER_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object deviceManufacturer_ = "";
  /**
   * <pre>
   * Manufacturer, for example "Xiaomi". Separated from model because
   * OEM-specific background-execution policy is manufacturer-wide.
   * </pre>
   *
   * <code>string device_manufacturer = 6 [json_name = "deviceManufacturer"];</code>
   * @return The deviceManufacturer.
   */
  @java.lang.Override
  public java.lang.String getDeviceManufacturer() {
    java.lang.Object ref = deviceManufacturer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceManufacturer_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Manufacturer, for example "Xiaomi". Separated from model because
   * OEM-specific background-execution policy is manufacturer-wide.
   * </pre>
   *
   * <code>string device_manufacturer = 6 [json_name = "deviceManufacturer"];</code>
   * @return The bytes for deviceManufacturer.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceManufacturerBytes() {
    java.lang.Object ref = deviceManufacturer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceManufacturer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCALE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object locale_ = "";
  /**
   * <pre>
   * BCP 47 locale tag, for example "hi-IN" or "en-IN". Drives which language
   * the AI layer responds in and which string catalogue the client resolves.
   * </pre>
   *
   * <code>string locale = 7 [json_name = "locale"];</code>
   * @return The locale.
   */
  @java.lang.Override
  public java.lang.String getLocale() {
    java.lang.Object ref = locale_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      locale_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * BCP 47 locale tag, for example "hi-IN" or "en-IN". Drives which language
   * the AI layer responds in and which string catalogue the client resolves.
   * </pre>
   *
   * <code>string locale = 7 [json_name = "locale"];</code>
   * @return The bytes for locale.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocaleBytes() {
    java.lang.Object ref = locale_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      locale_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEZONE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object timezone_ = "";
  /**
   * <pre>
   * IANA timezone name, for example "Asia/Kolkata".
   * </pre>
   *
   * <code>string timezone = 8 [json_name = "timezone"];</code>
   * @return The timezone.
   */
  @java.lang.Override
  public java.lang.String getTimezone() {
    java.lang.Object ref = timezone_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timezone_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * IANA timezone name, for example "Asia/Kolkata".
   * </pre>
   *
   * <code>string timezone = 8 [json_name = "timezone"];</code>
   * @return The bytes for timezone.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimezoneBytes() {
    java.lang.Object ref = timezone_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timezone_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSTALL_ID_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object installId_ = "";
  /**
   * <pre>
   * Stable pseudonymous install identifier. Personal data: it is capable of
   * singling out an individual even though it contains no direct identifier.
   * </pre>
   *
   * <code>string install_id = 9 [json_name = "installId", (.callscreen.common.v1.field_classification) = { ... }</code>
   * @return The installId.
   */
  @java.lang.Override
  public java.lang.String getInstallId() {
    java.lang.Object ref = installId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      installId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Stable pseudonymous install identifier. Personal data: it is capable of
   * singling out an individual even though it contains no direct identifier.
   * </pre>
   *
   * <code>string install_id = 9 [json_name = "installId", (.callscreen.common.v1.field_classification) = { ... }</code>
   * @return The bytes for installId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInstallIdBytes() {
    java.lang.Object ref = installId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      installId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NETWORK_TYPE_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object networkType_ = "";
  /**
   * <pre>
   * Network transport in use, for example "wifi", "4g", "5g". Recorded because
   * latency budgets and codec selection differ sharply by bearer, and Indian
   * mobile networks vary widely.
   * </pre>
   *
   * <code>string network_type = 10 [json_name = "networkType"];</code>
   * @return The networkType.
   */
  @java.lang.Override
  public java.lang.String getNetworkType() {
    java.lang.Object ref = networkType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      networkType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Network transport in use, for example "wifi", "4g", "5g". Recorded because
   * latency budgets and codec selection differ sharply by bearer, and Indian
   * mobile networks vary widely.
   * </pre>
   *
   * <code>string network_type = 10 [json_name = "networkType"];</code>
   * @return The bytes for networkType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNetworkTypeBytes() {
    java.lang.Object ref = networkType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      networkType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (platform_ != com.callscreen.contracts.callscreen.common.v1.Platform.PLATFORM_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, platform_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(appVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, appVersion_);
    }
    if (appBuild_ != 0L) {
      output.writeInt64(3, appBuild_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(osVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, osVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceModel_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, deviceModel_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceManufacturer_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, deviceManufacturer_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(locale_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, locale_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timezone_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, timezone_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(installId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, installId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(networkType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, networkType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (platform_ != com.callscreen.contracts.callscreen.common.v1.Platform.PLATFORM_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, platform_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(appVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, appVersion_);
    }
    if (appBuild_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, appBuild_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(osVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, osVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceModel_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, deviceModel_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceManufacturer_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, deviceManufacturer_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(locale_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, locale_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timezone_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, timezone_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(installId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, installId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(networkType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, networkType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.callscreen.contracts.callscreen.common.v1.ClientContext)) {
      return super.equals(obj);
    }
    com.callscreen.contracts.callscreen.common.v1.ClientContext other = (com.callscreen.contracts.callscreen.common.v1.ClientContext) obj;

    if (platform_ != other.platform_) return false;
    if (!getAppVersion()
        .equals(other.getAppVersion())) return false;
    if (getAppBuild()
        != other.getAppBuild()) return false;
    if (!getOsVersion()
        .equals(other.getOsVersion())) return false;
    if (!getDeviceModel()
        .equals(other.getDeviceModel())) return false;
    if (!getDeviceManufacturer()
        .equals(other.getDeviceManufacturer())) return false;
    if (!getLocale()
        .equals(other.getLocale())) return false;
    if (!getTimezone()
        .equals(other.getTimezone())) return false;
    if (!getInstallId()
        .equals(other.getInstallId())) return false;
    if (!getNetworkType()
        .equals(other.getNetworkType())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + platform_;
    hash = (37 * hash) + APP_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getAppVersion().hashCode();
    hash = (37 * hash) + APP_BUILD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAppBuild());
    hash = (37 * hash) + OS_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getOsVersion().hashCode();
    hash = (37 * hash) + DEVICE_MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceModel().hashCode();
    hash = (37 * hash) + DEVICE_MANUFACTURER_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceManufacturer().hashCode();
    hash = (37 * hash) + LOCALE_FIELD_NUMBER;
    hash = (53 * hash) + getLocale().hashCode();
    hash = (37 * hash) + TIMEZONE_FIELD_NUMBER;
    hash = (53 * hash) + getTimezone().hashCode();
    hash = (37 * hash) + INSTALL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getInstallId().hashCode();
    hash = (37 * hash) + NETWORK_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getNetworkType().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.callscreen.contracts.callscreen.common.v1.ClientContext parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.ClientContext parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.ClientContext parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.ClientContext parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.ClientContext parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.ClientContext parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.ClientContext parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.callscreen.contracts.callscreen.common.v1.ClientContext parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.callscreen.contracts.callscreen.common.v1.ClientContext parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.callscreen.contracts.callscreen.common.v1.ClientContext parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.ClientContext parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.callscreen.contracts.callscreen.common.v1.ClientContext parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.callscreen.contracts.callscreen.common.v1.ClientContext prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ClientContext travels with every request originating from an end-user client.
   *
   * It is populated by the client SDK, validated at the edge, and then attached
   * to the request's trace so that any downstream failure can be attributed to a
   * specific app version, OS version and locale without a separate lookup.
   * </pre>
   *
   * Protobuf type {@code callscreen.common.v1.ClientContext}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:callscreen.common.v1.ClientContext)
      com.callscreen.contracts.callscreen.common.v1.ClientContextOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_ClientContext_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_ClientContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.callscreen.contracts.callscreen.common.v1.ClientContext.class, com.callscreen.contracts.callscreen.common.v1.ClientContext.Builder.class);
    }

    // Construct using com.callscreen.contracts.callscreen.common.v1.ClientContext.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      platform_ = 0;
      appVersion_ = "";
      appBuild_ = 0L;
      osVersion_ = "";
      deviceModel_ = "";
      deviceManufacturer_ = "";
      locale_ = "";
      timezone_ = "";
      installId_ = "";
      networkType_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_ClientContext_descriptor;
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.ClientContext getDefaultInstanceForType() {
      return com.callscreen.contracts.callscreen.common.v1.ClientContext.getDefaultInstance();
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.ClientContext build() {
      com.callscreen.contracts.callscreen.common.v1.ClientContext result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.ClientContext buildPartial() {
      com.callscreen.contracts.callscreen.common.v1.ClientContext result = new com.callscreen.contracts.callscreen.common.v1.ClientContext(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.callscreen.contracts.callscreen.common.v1.ClientContext result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.platform_ = platform_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.appVersion_ = appVersion_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.appBuild_ = appBuild_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.osVersion_ = osVersion_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.deviceModel_ = deviceModel_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.deviceManufacturer_ = deviceManufacturer_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.locale_ = locale_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.timezone_ = timezone_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.installId_ = installId_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.networkType_ = networkType_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.callscreen.contracts.callscreen.common.v1.ClientContext) {
        return mergeFrom((com.callscreen.contracts.callscreen.common.v1.ClientContext)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.callscreen.contracts.callscreen.common.v1.ClientContext other) {
      if (other == com.callscreen.contracts.callscreen.common.v1.ClientContext.getDefaultInstance()) return this;
      if (other.platform_ != 0) {
        setPlatformValue(other.getPlatformValue());
      }
      if (!other.getAppVersion().isEmpty()) {
        appVersion_ = other.appVersion_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getAppBuild() != 0L) {
        setAppBuild(other.getAppBuild());
      }
      if (!other.getOsVersion().isEmpty()) {
        osVersion_ = other.osVersion_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getDeviceModel().isEmpty()) {
        deviceModel_ = other.deviceModel_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getDeviceManufacturer().isEmpty()) {
        deviceManufacturer_ = other.deviceManufacturer_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getLocale().isEmpty()) {
        locale_ = other.locale_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getTimezone().isEmpty()) {
        timezone_ = other.timezone_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getInstallId().isEmpty()) {
        installId_ = other.installId_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getNetworkType().isEmpty()) {
        networkType_ = other.networkType_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              platform_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              appVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              appBuild_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              osVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              deviceModel_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              deviceManufacturer_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              locale_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              timezone_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              installId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              networkType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int platform_ = 0;
    /**
     * <pre>
     * Client family issuing the request.
     * </pre>
     *
     * <code>.callscreen.common.v1.Platform platform = 1 [json_name = "platform"];</code>
     * @return The enum numeric value on the wire for platform.
     */
    @java.lang.Override public int getPlatformValue() {
      return platform_;
    }
    /**
     * <pre>
     * Client family issuing the request.
     * </pre>
     *
     * <code>.callscreen.common.v1.Platform platform = 1 [json_name = "platform"];</code>
     * @param value The enum numeric value on the wire for platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformValue(int value) {
      platform_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Client family issuing the request.
     * </pre>
     *
     * <code>.callscreen.common.v1.Platform platform = 1 [json_name = "platform"];</code>
     * @return The platform.
     */
    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.Platform getPlatform() {
      com.callscreen.contracts.callscreen.common.v1.Platform result = com.callscreen.contracts.callscreen.common.v1.Platform.forNumber(platform_);
      return result == null ? com.callscreen.contracts.callscreen.common.v1.Platform.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Client family issuing the request.
     * </pre>
     *
     * <code>.callscreen.common.v1.Platform platform = 1 [json_name = "platform"];</code>
     * @param value The platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatform(com.callscreen.contracts.callscreen.common.v1.Platform value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      platform_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Client family issuing the request.
     * </pre>
     *
     * <code>.callscreen.common.v1.Platform platform = 1 [json_name = "platform"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatform() {
      bitField0_ = (bitField0_ & ~0x00000001);
      platform_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object appVersion_ = "";
    /**
     * <pre>
     * Application version name, for example "1.4.2". Used to enforce the minimum
     * supported version floor described in Phase 1 §14.
     * </pre>
     *
     * <code>string app_version = 2 [json_name = "appVersion"];</code>
     * @return The appVersion.
     */
    public java.lang.String getAppVersion() {
      java.lang.Object ref = appVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Application version name, for example "1.4.2". Used to enforce the minimum
     * supported version floor described in Phase 1 §14.
     * </pre>
     *
     * <code>string app_version = 2 [json_name = "appVersion"];</code>
     * @return The bytes for appVersion.
     */
    public com.google.protobuf.ByteString
        getAppVersionBytes() {
      java.lang.Object ref = appVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Application version name, for example "1.4.2". Used to enforce the minimum
     * supported version floor described in Phase 1 §14.
     * </pre>
     *
     * <code>string app_version = 2 [json_name = "appVersion"];</code>
     * @param value The appVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAppVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      appVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Application version name, for example "1.4.2". Used to enforce the minimum
     * supported version floor described in Phase 1 §14.
     * </pre>
     *
     * <code>string app_version = 2 [json_name = "appVersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAppVersion() {
      appVersion_ = getDefaultInstance().getAppVersion();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Application version name, for example "1.4.2". Used to enforce the minimum
     * supported version floor described in Phase 1 §14.
     * </pre>
     *
     * <code>string app_version = 2 [json_name = "appVersion"];</code>
     * @param value The bytes for appVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAppVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      appVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long appBuild_ ;
    /**
     * <pre>
     * Monotonic build number. Unambiguous where `app_version` may be reused
     * across staged rollouts.
     * </pre>
     *
     * <code>int64 app_build = 3 [json_name = "appBuild"];</code>
     * @return The appBuild.
     */
    @java.lang.Override
    public long getAppBuild() {
      return appBuild_;
    }
    /**
     * <pre>
     * Monotonic build number. Unambiguous where `app_version` may be reused
     * across staged rollouts.
     * </pre>
     *
     * <code>int64 app_build = 3 [json_name = "appBuild"];</code>
     * @param value The appBuild to set.
     * @return This builder for chaining.
     */
    public Builder setAppBuild(long value) {

      appBuild_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Monotonic build number. Unambiguous where `app_version` may be reused
     * across staged rollouts.
     * </pre>
     *
     * <code>int64 app_build = 3 [json_name = "appBuild"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAppBuild() {
      bitField0_ = (bitField0_ & ~0x00000004);
      appBuild_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object osVersion_ = "";
    /**
     * <pre>
     * Operating system version string, for example "Android 14".
     * </pre>
     *
     * <code>string os_version = 4 [json_name = "osVersion"];</code>
     * @return The osVersion.
     */
    public java.lang.String getOsVersion() {
      java.lang.Object ref = osVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Operating system version string, for example "Android 14".
     * </pre>
     *
     * <code>string os_version = 4 [json_name = "osVersion"];</code>
     * @return The bytes for osVersion.
     */
    public com.google.protobuf.ByteString
        getOsVersionBytes() {
      java.lang.Object ref = osVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Operating system version string, for example "Android 14".
     * </pre>
     *
     * <code>string os_version = 4 [json_name = "osVersion"];</code>
     * @param value The osVersion to set.
     * @return This builder for chaining.
     */
    public Builder setOsVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      osVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Operating system version string, for example "Android 14".
     * </pre>
     *
     * <code>string os_version = 4 [json_name = "osVersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOsVersion() {
      osVersion_ = getDefaultInstance().getOsVersion();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Operating system version string, for example "Android 14".
     * </pre>
     *
     * <code>string os_version = 4 [json_name = "osVersion"];</code>
     * @param value The bytes for osVersion to set.
     * @return This builder for chaining.
     */
    public Builder setOsVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      osVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object deviceModel_ = "";
    /**
     * <pre>
     * Device model identifier. Needed because telephony and audio behaviour
     * varies enormously across Android OEMs, and OEM-specific defects are a
     * recurring class of production incident.
     * </pre>
     *
     * <code>string device_model = 5 [json_name = "deviceModel"];</code>
     * @return The deviceModel.
     */
    public java.lang.String getDeviceModel() {
      java.lang.Object ref = deviceModel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceModel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Device model identifier. Needed because telephony and audio behaviour
     * varies enormously across Android OEMs, and OEM-specific defects are a
     * recurring class of production incident.
     * </pre>
     *
     * <code>string device_model = 5 [json_name = "deviceModel"];</code>
     * @return The bytes for deviceModel.
     */
    public com.google.protobuf.ByteString
        getDeviceModelBytes() {
      java.lang.Object ref = deviceModel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Device model identifier. Needed because telephony and audio behaviour
     * varies enormously across Android OEMs, and OEM-specific defects are a
     * recurring class of production incident.
     * </pre>
     *
     * <code>string device_model = 5 [json_name = "deviceModel"];</code>
     * @param value The deviceModel to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceModel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      deviceModel_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Device model identifier. Needed because telephony and audio behaviour
     * varies enormously across Android OEMs, and OEM-specific defects are a
     * recurring class of production incident.
     * </pre>
     *
     * <code>string device_model = 5 [json_name = "deviceModel"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceModel() {
      deviceModel_ = getDefaultInstance().getDeviceModel();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Device model identifier. Needed because telephony and audio behaviour
     * varies enormously across Android OEMs, and OEM-specific defects are a
     * recurring class of production incident.
     * </pre>
     *
     * <code>string device_model = 5 [json_name = "deviceModel"];</code>
     * @param value The bytes for deviceModel to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      deviceModel_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object deviceManufacturer_ = "";
    /**
     * <pre>
     * Manufacturer, for example "Xiaomi". Separated from model because
     * OEM-specific background-execution policy is manufacturer-wide.
     * </pre>
     *
     * <code>string device_manufacturer = 6 [json_name = "deviceManufacturer"];</code>
     * @return The deviceManufacturer.
     */
    public java.lang.String getDeviceManufacturer() {
      java.lang.Object ref = deviceManufacturer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceManufacturer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Manufacturer, for example "Xiaomi". Separated from model because
     * OEM-specific background-execution policy is manufacturer-wide.
     * </pre>
     *
     * <code>string device_manufacturer = 6 [json_name = "deviceManufacturer"];</code>
     * @return The bytes for deviceManufacturer.
     */
    public com.google.protobuf.ByteString
        getDeviceManufacturerBytes() {
      java.lang.Object ref = deviceManufacturer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceManufacturer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Manufacturer, for example "Xiaomi". Separated from model because
     * OEM-specific background-execution policy is manufacturer-wide.
     * </pre>
     *
     * <code>string device_manufacturer = 6 [json_name = "deviceManufacturer"];</code>
     * @param value The deviceManufacturer to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceManufacturer(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      deviceManufacturer_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Manufacturer, for example "Xiaomi". Separated from model because
     * OEM-specific background-execution policy is manufacturer-wide.
     * </pre>
     *
     * <code>string device_manufacturer = 6 [json_name = "deviceManufacturer"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceManufacturer() {
      deviceManufacturer_ = getDefaultInstance().getDeviceManufacturer();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Manufacturer, for example "Xiaomi". Separated from model because
     * OEM-specific background-execution policy is manufacturer-wide.
     * </pre>
     *
     * <code>string device_manufacturer = 6 [json_name = "deviceManufacturer"];</code>
     * @param value The bytes for deviceManufacturer to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceManufacturerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      deviceManufacturer_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object locale_ = "";
    /**
     * <pre>
     * BCP 47 locale tag, for example "hi-IN" or "en-IN". Drives which language
     * the AI layer responds in and which string catalogue the client resolves.
     * </pre>
     *
     * <code>string locale = 7 [json_name = "locale"];</code>
     * @return The locale.
     */
    public java.lang.String getLocale() {
      java.lang.Object ref = locale_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        locale_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * BCP 47 locale tag, for example "hi-IN" or "en-IN". Drives which language
     * the AI layer responds in and which string catalogue the client resolves.
     * </pre>
     *
     * <code>string locale = 7 [json_name = "locale"];</code>
     * @return The bytes for locale.
     */
    public com.google.protobuf.ByteString
        getLocaleBytes() {
      java.lang.Object ref = locale_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locale_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * BCP 47 locale tag, for example "hi-IN" or "en-IN". Drives which language
     * the AI layer responds in and which string catalogue the client resolves.
     * </pre>
     *
     * <code>string locale = 7 [json_name = "locale"];</code>
     * @param value The locale to set.
     * @return This builder for chaining.
     */
    public Builder setLocale(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      locale_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BCP 47 locale tag, for example "hi-IN" or "en-IN". Drives which language
     * the AI layer responds in and which string catalogue the client resolves.
     * </pre>
     *
     * <code>string locale = 7 [json_name = "locale"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLocale() {
      locale_ = getDefaultInstance().getLocale();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BCP 47 locale tag, for example "hi-IN" or "en-IN". Drives which language
     * the AI layer responds in and which string catalogue the client resolves.
     * </pre>
     *
     * <code>string locale = 7 [json_name = "locale"];</code>
     * @param value The bytes for locale to set.
     * @return This builder for chaining.
     */
    public Builder setLocaleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      locale_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object timezone_ = "";
    /**
     * <pre>
     * IANA timezone name, for example "Asia/Kolkata".
     * </pre>
     *
     * <code>string timezone = 8 [json_name = "timezone"];</code>
     * @return The timezone.
     */
    public java.lang.String getTimezone() {
      java.lang.Object ref = timezone_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timezone_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * IANA timezone name, for example "Asia/Kolkata".
     * </pre>
     *
     * <code>string timezone = 8 [json_name = "timezone"];</code>
     * @return The bytes for timezone.
     */
    public com.google.protobuf.ByteString
        getTimezoneBytes() {
      java.lang.Object ref = timezone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timezone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * IANA timezone name, for example "Asia/Kolkata".
     * </pre>
     *
     * <code>string timezone = 8 [json_name = "timezone"];</code>
     * @param value The timezone to set.
     * @return This builder for chaining.
     */
    public Builder setTimezone(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      timezone_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * IANA timezone name, for example "Asia/Kolkata".
     * </pre>
     *
     * <code>string timezone = 8 [json_name = "timezone"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTimezone() {
      timezone_ = getDefaultInstance().getTimezone();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * IANA timezone name, for example "Asia/Kolkata".
     * </pre>
     *
     * <code>string timezone = 8 [json_name = "timezone"];</code>
     * @param value The bytes for timezone to set.
     * @return This builder for chaining.
     */
    public Builder setTimezoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      timezone_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object installId_ = "";
    /**
     * <pre>
     * Stable pseudonymous install identifier. Personal data: it is capable of
     * singling out an individual even though it contains no direct identifier.
     * </pre>
     *
     * <code>string install_id = 9 [json_name = "installId", (.callscreen.common.v1.field_classification) = { ... }</code>
     * @return The installId.
     */
    public java.lang.String getInstallId() {
      java.lang.Object ref = installId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        installId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Stable pseudonymous install identifier. Personal data: it is capable of
     * singling out an individual even though it contains no direct identifier.
     * </pre>
     *
     * <code>string install_id = 9 [json_name = "installId", (.callscreen.common.v1.field_classification) = { ... }</code>
     * @return The bytes for installId.
     */
    public com.google.protobuf.ByteString
        getInstallIdBytes() {
      java.lang.Object ref = installId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        installId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Stable pseudonymous install identifier. Personal data: it is capable of
     * singling out an individual even though it contains no direct identifier.
     * </pre>
     *
     * <code>string install_id = 9 [json_name = "installId", (.callscreen.common.v1.field_classification) = { ... }</code>
     * @param value The installId to set.
     * @return This builder for chaining.
     */
    public Builder setInstallId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      installId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stable pseudonymous install identifier. Personal data: it is capable of
     * singling out an individual even though it contains no direct identifier.
     * </pre>
     *
     * <code>string install_id = 9 [json_name = "installId", (.callscreen.common.v1.field_classification) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearInstallId() {
      installId_ = getDefaultInstance().getInstallId();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stable pseudonymous install identifier. Personal data: it is capable of
     * singling out an individual even though it contains no direct identifier.
     * </pre>
     *
     * <code>string install_id = 9 [json_name = "installId", (.callscreen.common.v1.field_classification) = { ... }</code>
     * @param value The bytes for installId to set.
     * @return This builder for chaining.
     */
    public Builder setInstallIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      installId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object networkType_ = "";
    /**
     * <pre>
     * Network transport in use, for example "wifi", "4g", "5g". Recorded because
     * latency budgets and codec selection differ sharply by bearer, and Indian
     * mobile networks vary widely.
     * </pre>
     *
     * <code>string network_type = 10 [json_name = "networkType"];</code>
     * @return The networkType.
     */
    public java.lang.String getNetworkType() {
      java.lang.Object ref = networkType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        networkType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Network transport in use, for example "wifi", "4g", "5g". Recorded because
     * latency budgets and codec selection differ sharply by bearer, and Indian
     * mobile networks vary widely.
     * </pre>
     *
     * <code>string network_type = 10 [json_name = "networkType"];</code>
     * @return The bytes for networkType.
     */
    public com.google.protobuf.ByteString
        getNetworkTypeBytes() {
      java.lang.Object ref = networkType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        networkType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Network transport in use, for example "wifi", "4g", "5g". Recorded because
     * latency budgets and codec selection differ sharply by bearer, and Indian
     * mobile networks vary widely.
     * </pre>
     *
     * <code>string network_type = 10 [json_name = "networkType"];</code>
     * @param value The networkType to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      networkType_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Network transport in use, for example "wifi", "4g", "5g". Recorded because
     * latency budgets and codec selection differ sharply by bearer, and Indian
     * mobile networks vary widely.
     * </pre>
     *
     * <code>string network_type = 10 [json_name = "networkType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNetworkType() {
      networkType_ = getDefaultInstance().getNetworkType();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Network transport in use, for example "wifi", "4g", "5g". Recorded because
     * latency budgets and codec selection differ sharply by bearer, and Indian
     * mobile networks vary widely.
     * </pre>
     *
     * <code>string network_type = 10 [json_name = "networkType"];</code>
     * @param value The bytes for networkType to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      networkType_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:callscreen.common.v1.ClientContext)
  }

  // @@protoc_insertion_point(class_scope:callscreen.common.v1.ClientContext)
  private static final com.callscreen.contracts.callscreen.common.v1.ClientContext DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.callscreen.contracts.callscreen.common.v1.ClientContext();
  }

  public static com.callscreen.contracts.callscreen.common.v1.ClientContext getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientContext>
      PARSER = new com.google.protobuf.AbstractParser<ClientContext>() {
    @java.lang.Override
    public ClientContext parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ClientContext> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientContext> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.callscreen.contracts.callscreen.common.v1.ClientContext getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

