// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/types.proto
// Protobuf Java Version: 4.29.3

package com.callscreen.contracts.callscreen.common.v1;

/**
 * <pre>
 * Environment distinguishes deployment tiers on the wire so that a misrouted
 * staging client can be rejected rather than silently writing to production.
 * </pre>
 *
 * Protobuf enum {@code callscreen.common.v1.Environment}
 */
public enum Environment
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ENVIRONMENT_UNSPECIFIED = 0;</code>
   */
  ENVIRONMENT_UNSPECIFIED(0),
  /**
   * <code>ENVIRONMENT_DEVELOPMENT = 1;</code>
   */
  ENVIRONMENT_DEVELOPMENT(1),
  /**
   * <code>ENVIRONMENT_STAGING = 2;</code>
   */
  ENVIRONMENT_STAGING(2),
  /**
   * <code>ENVIRONMENT_PRODUCTION = 3;</code>
   */
  ENVIRONMENT_PRODUCTION(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Environment.class.getName());
  }
  /**
   * <code>ENVIRONMENT_UNSPECIFIED = 0;</code>
   */
  public static final int ENVIRONMENT_UNSPECIFIED_VALUE = 0;
  /**
   * <code>ENVIRONMENT_DEVELOPMENT = 1;</code>
   */
  public static final int ENVIRONMENT_DEVELOPMENT_VALUE = 1;
  /**
   * <code>ENVIRONMENT_STAGING = 2;</code>
   */
  public static final int ENVIRONMENT_STAGING_VALUE = 2;
  /**
   * <code>ENVIRONMENT_PRODUCTION = 3;</code>
   */
  public static final int ENVIRONMENT_PRODUCTION_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Environment valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Environment forNumber(int value) {
    switch (value) {
      case 0: return ENVIRONMENT_UNSPECIFIED;
      case 1: return ENVIRONMENT_DEVELOPMENT;
      case 2: return ENVIRONMENT_STAGING;
      case 3: return ENVIRONMENT_PRODUCTION;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Environment>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Environment> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Environment>() {
          public Environment findValueByNumber(int number) {
            return Environment.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.callscreen.contracts.callscreen.common.v1.TypesProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final Environment[] VALUES = values();

  public static Environment valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Environment(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:callscreen.common.v1.Environment)
}

