// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/error.proto
// Protobuf Java Version: 4.29.3

package com.callscreen.contracts.callscreen.common.v1;

/**
 * <pre>
 * ErrorCode enumerates every failure class the platform can return.
 *
 * Ranges are allocated by domain so that adding a code in one area cannot
 * collide with concurrent work in another:
 * 1-99     generic / transport
 * 100-199  authentication and authorisation
 * 200-299  validation and client fault
 * 300-399  resource state
 * 400-499  quota, rate limiting and billing
 * 500-599  upstream dependency and vendor faults
 * 600-699  policy, safety and compliance refusals
 * </pre>
 *
 * Protobuf enum {@code callscreen.common.v1.ErrorCode}
 */
public enum ErrorCode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Never returned deliberately. Its presence indicates a service constructed
   * an error without setting a code, which the platform library treats as a bug
   * and reports to the error tracker.
   * </pre>
   *
   * <code>ERROR_CODE_UNSPECIFIED = 0;</code>
   */
  ERROR_CODE_UNSPECIFIED(0),
  /**
   * <pre>
   * --- Generic / transport (1-99) -----------------------------------------
   * An unhandled fault. Always accompanied by an incident-correlatable trace id.
   * </pre>
   *
   * <code>ERROR_CODE_INTERNAL = 1;</code>
   */
  ERROR_CODE_INTERNAL(1),
  /**
   * <pre>
   * The service is starting, draining, or a dependency is unavailable.
   * </pre>
   *
   * <code>ERROR_CODE_UNAVAILABLE = 2;</code>
   */
  ERROR_CODE_UNAVAILABLE(2),
  /**
   * <pre>
   * The request exceeded its deadline inside our system.
   * </pre>
   *
   * <code>ERROR_CODE_DEADLINE_EXCEEDED = 3;</code>
   */
  ERROR_CODE_DEADLINE_EXCEEDED(3),
  /**
   * <pre>
   * The caller cancelled before completion. Not an error worth alerting on.
   * </pre>
   *
   * <code>ERROR_CODE_CANCELLED = 4;</code>
   */
  ERROR_CODE_CANCELLED(4),
  /**
   * <pre>
   * The client is running a contract version this server no longer supports.
   * Drives the forced-upgrade prompt described in Phase 1 §14.
   * </pre>
   *
   * <code>ERROR_CODE_UNSUPPORTED_CLIENT_VERSION = 5;</code>
   */
  ERROR_CODE_UNSUPPORTED_CLIENT_VERSION(5),
  /**
   * <pre>
   * --- Authentication and authorisation (100-199) --------------------------
   * No credential was presented.
   * </pre>
   *
   * <code>ERROR_CODE_UNAUTHENTICATED = 100;</code>
   */
  ERROR_CODE_UNAUTHENTICATED(100),
  /**
   * <pre>
   * The credential was presented but is expired, malformed or revoked.
   * </pre>
   *
   * <code>ERROR_CODE_INVALID_CREDENTIAL = 101;</code>
   */
  ERROR_CODE_INVALID_CREDENTIAL(101),
  /**
   * <pre>
   * The credential is valid but lacks permission for this operation.
   * </pre>
   *
   * <code>ERROR_CODE_PERMISSION_DENIED = 102;</code>
   */
  ERROR_CODE_PERMISSION_DENIED(102),
  /**
   * <pre>
   * Device attestation failed. The client may be tampered with or emulated.
   * </pre>
   *
   * <code>ERROR_CODE_ATTESTATION_FAILED = 103;</code>
   */
  ERROR_CODE_ATTESTATION_FAILED(103),
  /**
   * <pre>
   * --- Validation and client fault (200-299) -------------------------------
   * The request violated the schema or a documented business rule. Populate
   * `field_violations` so the client can highlight the offending input.
   * </pre>
   *
   * <code>ERROR_CODE_INVALID_ARGUMENT = 200;</code>
   */
  ERROR_CODE_INVALID_ARGUMENT(200),
  /**
   * <pre>
   * A required field was absent.
   * </pre>
   *
   * <code>ERROR_CODE_MISSING_REQUIRED_FIELD = 201;</code>
   */
  ERROR_CODE_MISSING_REQUIRED_FIELD(201),
  /**
   * <pre>
   * The request body exceeded the permitted size.
   * </pre>
   *
   * <code>ERROR_CODE_PAYLOAD_TOO_LARGE = 202;</code>
   */
  ERROR_CODE_PAYLOAD_TOO_LARGE(202),
  /**
   * <pre>
   * The supplied idempotency key was reused with a different payload.
   * </pre>
   *
   * <code>ERROR_CODE_IDEMPOTENCY_CONFLICT = 203;</code>
   */
  ERROR_CODE_IDEMPOTENCY_CONFLICT(203),
  /**
   * <pre>
   * --- Resource state (300-399) ---------------------------------------------
   * </pre>
   *
   * <code>ERROR_CODE_NOT_FOUND = 300;</code>
   */
  ERROR_CODE_NOT_FOUND(300),
  /**
   * <code>ERROR_CODE_ALREADY_EXISTS = 301;</code>
   */
  ERROR_CODE_ALREADY_EXISTS(301),
  /**
   * <pre>
   * The resource is not in a state that permits this transition.
   * </pre>
   *
   * <code>ERROR_CODE_FAILED_PRECONDITION = 302;</code>
   */
  ERROR_CODE_FAILED_PRECONDITION(302),
  /**
   * <pre>
   * Optimistic concurrency check failed; the caller should re-read and retry.
   * </pre>
   *
   * <code>ERROR_CODE_VERSION_CONFLICT = 303;</code>
   */
  ERROR_CODE_VERSION_CONFLICT(303),
  /**
   * <pre>
   * --- Quota, rate limiting and billing (400-499) --------------------------
   * Too many requests. `retry_after` is always populated for this code.
   * </pre>
   *
   * <code>ERROR_CODE_RATE_LIMITED = 400;</code>
   */
  ERROR_CODE_RATE_LIMITED(400),
  /**
   * <pre>
   * A hard usage allowance has been consumed.
   * </pre>
   *
   * <code>ERROR_CODE_QUOTA_EXCEEDED = 401;</code>
   */
  ERROR_CODE_QUOTA_EXCEEDED(401),
  /**
   * <pre>
   * The operation requires an entitlement the account does not hold.
   * </pre>
   *
   * <code>ERROR_CODE_SUBSCRIPTION_REQUIRED = 402;</code>
   */
  ERROR_CODE_SUBSCRIPTION_REQUIRED(402),
  /**
   * <pre>
   * Payment is overdue and the account is in a restricted state.
   * </pre>
   *
   * <code>ERROR_CODE_PAYMENT_REQUIRED = 403;</code>
   */
  ERROR_CODE_PAYMENT_REQUIRED(403),
  /**
   * <pre>
   * --- Upstream dependency and vendor faults (500-599) ---------------------
   * A third-party vendor failed. Distinguished from INTERNAL so that vendor
   * reliability can be measured and alerted on separately from our own.
   * </pre>
   *
   * <code>ERROR_CODE_UPSTREAM_FAILURE = 500;</code>
   */
  ERROR_CODE_UPSTREAM_FAILURE(500),
  /**
   * <pre>
   * A vendor rate-limited us. Drives failover to a secondary provider.
   * </pre>
   *
   * <code>ERROR_CODE_UPSTREAM_RATE_LIMITED = 501;</code>
   */
  ERROR_CODE_UPSTREAM_RATE_LIMITED(501),
  /**
   * <pre>
   * Every configured provider for a capability is unavailable.
   * </pre>
   *
   * <code>ERROR_CODE_NO_PROVIDER_AVAILABLE = 502;</code>
   */
  ERROR_CODE_NO_PROVIDER_AVAILABLE(502),
  /**
   * <pre>
   * --- Policy, safety and compliance (600-699) ------------------------------
   * The request was refused by a safety or moderation policy.
   * </pre>
   *
   * <code>ERROR_CODE_POLICY_VIOLATION = 600;</code>
   */
  ERROR_CODE_POLICY_VIOLATION(600),
  /**
   * <pre>
   * The operation is unavailable in the caller's jurisdiction.
   * </pre>
   *
   * <code>ERROR_CODE_REGION_RESTRICTED = 601;</code>
   */
  ERROR_CODE_REGION_RESTRICTED(601),
  /**
   * <pre>
   * The user has not granted the consent this operation requires under DPDP.
   * </pre>
   *
   * <code>ERROR_CODE_CONSENT_REQUIRED = 602;</code>
   */
  ERROR_CODE_CONSENT_REQUIRED(602),
  /**
   * <pre>
   * Data residency rules forbid servicing this request from this region.
   * </pre>
   *
   * <code>ERROR_CODE_RESIDENCY_VIOLATION = 603;</code>
   */
  ERROR_CODE_RESIDENCY_VIOLATION(603),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ErrorCode.class.getName());
  }
  /**
   * <pre>
   * Never returned deliberately. Its presence indicates a service constructed
   * an error without setting a code, which the platform library treats as a bug
   * and reports to the error tracker.
   * </pre>
   *
   * <code>ERROR_CODE_UNSPECIFIED = 0;</code>
   */
  public static final int ERROR_CODE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * --- Generic / transport (1-99) -----------------------------------------
   * An unhandled fault. Always accompanied by an incident-correlatable trace id.
   * </pre>
   *
   * <code>ERROR_CODE_INTERNAL = 1;</code>
   */
  public static final int ERROR_CODE_INTERNAL_VALUE = 1;
  /**
   * <pre>
   * The service is starting, draining, or a dependency is unavailable.
   * </pre>
   *
   * <code>ERROR_CODE_UNAVAILABLE = 2;</code>
   */
  public static final int ERROR_CODE_UNAVAILABLE_VALUE = 2;
  /**
   * <pre>
   * The request exceeded its deadline inside our system.
   * </pre>
   *
   * <code>ERROR_CODE_DEADLINE_EXCEEDED = 3;</code>
   */
  public static final int ERROR_CODE_DEADLINE_EXCEEDED_VALUE = 3;
  /**
   * <pre>
   * The caller cancelled before completion. Not an error worth alerting on.
   * </pre>
   *
   * <code>ERROR_CODE_CANCELLED = 4;</code>
   */
  public static final int ERROR_CODE_CANCELLED_VALUE = 4;
  /**
   * <pre>
   * The client is running a contract version this server no longer supports.
   * Drives the forced-upgrade prompt described in Phase 1 §14.
   * </pre>
   *
   * <code>ERROR_CODE_UNSUPPORTED_CLIENT_VERSION = 5;</code>
   */
  public static final int ERROR_CODE_UNSUPPORTED_CLIENT_VERSION_VALUE = 5;
  /**
   * <pre>
   * --- Authentication and authorisation (100-199) --------------------------
   * No credential was presented.
   * </pre>
   *
   * <code>ERROR_CODE_UNAUTHENTICATED = 100;</code>
   */
  public static final int ERROR_CODE_UNAUTHENTICATED_VALUE = 100;
  /**
   * <pre>
   * The credential was presented but is expired, malformed or revoked.
   * </pre>
   *
   * <code>ERROR_CODE_INVALID_CREDENTIAL = 101;</code>
   */
  public static final int ERROR_CODE_INVALID_CREDENTIAL_VALUE = 101;
  /**
   * <pre>
   * The credential is valid but lacks permission for this operation.
   * </pre>
   *
   * <code>ERROR_CODE_PERMISSION_DENIED = 102;</code>
   */
  public static final int ERROR_CODE_PERMISSION_DENIED_VALUE = 102;
  /**
   * <pre>
   * Device attestation failed. The client may be tampered with or emulated.
   * </pre>
   *
   * <code>ERROR_CODE_ATTESTATION_FAILED = 103;</code>
   */
  public static final int ERROR_CODE_ATTESTATION_FAILED_VALUE = 103;
  /**
   * <pre>
   * --- Validation and client fault (200-299) -------------------------------
   * The request violated the schema or a documented business rule. Populate
   * `field_violations` so the client can highlight the offending input.
   * </pre>
   *
   * <code>ERROR_CODE_INVALID_ARGUMENT = 200;</code>
   */
  public static final int ERROR_CODE_INVALID_ARGUMENT_VALUE = 200;
  /**
   * <pre>
   * A required field was absent.
   * </pre>
   *
   * <code>ERROR_CODE_MISSING_REQUIRED_FIELD = 201;</code>
   */
  public static final int ERROR_CODE_MISSING_REQUIRED_FIELD_VALUE = 201;
  /**
   * <pre>
   * The request body exceeded the permitted size.
   * </pre>
   *
   * <code>ERROR_CODE_PAYLOAD_TOO_LARGE = 202;</code>
   */
  public static final int ERROR_CODE_PAYLOAD_TOO_LARGE_VALUE = 202;
  /**
   * <pre>
   * The supplied idempotency key was reused with a different payload.
   * </pre>
   *
   * <code>ERROR_CODE_IDEMPOTENCY_CONFLICT = 203;</code>
   */
  public static final int ERROR_CODE_IDEMPOTENCY_CONFLICT_VALUE = 203;
  /**
   * <pre>
   * --- Resource state (300-399) ---------------------------------------------
   * </pre>
   *
   * <code>ERROR_CODE_NOT_FOUND = 300;</code>
   */
  public static final int ERROR_CODE_NOT_FOUND_VALUE = 300;
  /**
   * <code>ERROR_CODE_ALREADY_EXISTS = 301;</code>
   */
  public static final int ERROR_CODE_ALREADY_EXISTS_VALUE = 301;
  /**
   * <pre>
   * The resource is not in a state that permits this transition.
   * </pre>
   *
   * <code>ERROR_CODE_FAILED_PRECONDITION = 302;</code>
   */
  public static final int ERROR_CODE_FAILED_PRECONDITION_VALUE = 302;
  /**
   * <pre>
   * Optimistic concurrency check failed; the caller should re-read and retry.
   * </pre>
   *
   * <code>ERROR_CODE_VERSION_CONFLICT = 303;</code>
   */
  public static final int ERROR_CODE_VERSION_CONFLICT_VALUE = 303;
  /**
   * <pre>
   * --- Quota, rate limiting and billing (400-499) --------------------------
   * Too many requests. `retry_after` is always populated for this code.
   * </pre>
   *
   * <code>ERROR_CODE_RATE_LIMITED = 400;</code>
   */
  public static final int ERROR_CODE_RATE_LIMITED_VALUE = 400;
  /**
   * <pre>
   * A hard usage allowance has been consumed.
   * </pre>
   *
   * <code>ERROR_CODE_QUOTA_EXCEEDED = 401;</code>
   */
  public static final int ERROR_CODE_QUOTA_EXCEEDED_VALUE = 401;
  /**
   * <pre>
   * The operation requires an entitlement the account does not hold.
   * </pre>
   *
   * <code>ERROR_CODE_SUBSCRIPTION_REQUIRED = 402;</code>
   */
  public static final int ERROR_CODE_SUBSCRIPTION_REQUIRED_VALUE = 402;
  /**
   * <pre>
   * Payment is overdue and the account is in a restricted state.
   * </pre>
   *
   * <code>ERROR_CODE_PAYMENT_REQUIRED = 403;</code>
   */
  public static final int ERROR_CODE_PAYMENT_REQUIRED_VALUE = 403;
  /**
   * <pre>
   * --- Upstream dependency and vendor faults (500-599) ---------------------
   * A third-party vendor failed. Distinguished from INTERNAL so that vendor
   * reliability can be measured and alerted on separately from our own.
   * </pre>
   *
   * <code>ERROR_CODE_UPSTREAM_FAILURE = 500;</code>
   */
  public static final int ERROR_CODE_UPSTREAM_FAILURE_VALUE = 500;
  /**
   * <pre>
   * A vendor rate-limited us. Drives failover to a secondary provider.
   * </pre>
   *
   * <code>ERROR_CODE_UPSTREAM_RATE_LIMITED = 501;</code>
   */
  public static final int ERROR_CODE_UPSTREAM_RATE_LIMITED_VALUE = 501;
  /**
   * <pre>
   * Every configured provider for a capability is unavailable.
   * </pre>
   *
   * <code>ERROR_CODE_NO_PROVIDER_AVAILABLE = 502;</code>
   */
  public static final int ERROR_CODE_NO_PROVIDER_AVAILABLE_VALUE = 502;
  /**
   * <pre>
   * --- Policy, safety and compliance (600-699) ------------------------------
   * The request was refused by a safety or moderation policy.
   * </pre>
   *
   * <code>ERROR_CODE_POLICY_VIOLATION = 600;</code>
   */
  public static final int ERROR_CODE_POLICY_VIOLATION_VALUE = 600;
  /**
   * <pre>
   * The operation is unavailable in the caller's jurisdiction.
   * </pre>
   *
   * <code>ERROR_CODE_REGION_RESTRICTED = 601;</code>
   */
  public static final int ERROR_CODE_REGION_RESTRICTED_VALUE = 601;
  /**
   * <pre>
   * The user has not granted the consent this operation requires under DPDP.
   * </pre>
   *
   * <code>ERROR_CODE_CONSENT_REQUIRED = 602;</code>
   */
  public static final int ERROR_CODE_CONSENT_REQUIRED_VALUE = 602;
  /**
   * <pre>
   * Data residency rules forbid servicing this request from this region.
   * </pre>
   *
   * <code>ERROR_CODE_RESIDENCY_VIOLATION = 603;</code>
   */
  public static final int ERROR_CODE_RESIDENCY_VIOLATION_VALUE = 603;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ErrorCode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ErrorCode forNumber(int value) {
    switch (value) {
      case 0: return ERROR_CODE_UNSPECIFIED;
      case 1: return ERROR_CODE_INTERNAL;
      case 2: return ERROR_CODE_UNAVAILABLE;
      case 3: return ERROR_CODE_DEADLINE_EXCEEDED;
      case 4: return ERROR_CODE_CANCELLED;
      case 5: return ERROR_CODE_UNSUPPORTED_CLIENT_VERSION;
      case 100: return ERROR_CODE_UNAUTHENTICATED;
      case 101: return ERROR_CODE_INVALID_CREDENTIAL;
      case 102: return ERROR_CODE_PERMISSION_DENIED;
      case 103: return ERROR_CODE_ATTESTATION_FAILED;
      case 200: return ERROR_CODE_INVALID_ARGUMENT;
      case 201: return ERROR_CODE_MISSING_REQUIRED_FIELD;
      case 202: return ERROR_CODE_PAYLOAD_TOO_LARGE;
      case 203: return ERROR_CODE_IDEMPOTENCY_CONFLICT;
      case 300: return ERROR_CODE_NOT_FOUND;
      case 301: return ERROR_CODE_ALREADY_EXISTS;
      case 302: return ERROR_CODE_FAILED_PRECONDITION;
      case 303: return ERROR_CODE_VERSION_CONFLICT;
      case 400: return ERROR_CODE_RATE_LIMITED;
      case 401: return ERROR_CODE_QUOTA_EXCEEDED;
      case 402: return ERROR_CODE_SUBSCRIPTION_REQUIRED;
      case 403: return ERROR_CODE_PAYMENT_REQUIRED;
      case 500: return ERROR_CODE_UPSTREAM_FAILURE;
      case 501: return ERROR_CODE_UPSTREAM_RATE_LIMITED;
      case 502: return ERROR_CODE_NO_PROVIDER_AVAILABLE;
      case 600: return ERROR_CODE_POLICY_VIOLATION;
      case 601: return ERROR_CODE_REGION_RESTRICTED;
      case 602: return ERROR_CODE_CONSENT_REQUIRED;
      case 603: return ERROR_CODE_RESIDENCY_VIOLATION;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ErrorCode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
          public ErrorCode findValueByNumber(int number) {
            return ErrorCode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.callscreen.contracts.callscreen.common.v1.ErrorProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final ErrorCode[] VALUES = values();

  public static ErrorCode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:callscreen.common.v1.ErrorCode)
}

