// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/error.proto
// Protobuf Java Version: 4.29.3

package com.callscreen.contracts.callscreen.common.v1;

public final class ErrorProto {
  private ErrorProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ErrorProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_callscreen_common_v1_FieldViolation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_callscreen_common_v1_FieldViolation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_callscreen_common_v1_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_callscreen_common_v1_Error_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n callscreen/common/v1/error.proto\022\024call" +
      "screen.common.v1\032&callscreen/common/v1/a" +
      "nnotations.proto\032\036google/protobuf/durati" +
      "on.proto\"r\n\016FieldViolation\022\024\n\005field\030\001 \001(" +
      "\tR\005field\022 \n\013description\030\002 \001(\tR\013descripti" +
      "on\022(\n\020user_message_key\030\003 \001(\tR\016userMessag" +
      "eKey\"\214\003\n\005Error\0223\n\004code\030\001 \001(\0162\037.callscree" +
      "n.common.v1.ErrorCodeR\004code\022\030\n\007message\030\002" +
      " \001(\tR\007message\022(\n\020user_message_key\030\003 \001(\tR" +
      "\016userMessageKey\022\031\n\010trace_id\030\004 \001(\tR\007trace" +
      "Id\022\034\n\tretryable\030\005 \001(\010R\tretryable\022:\n\013retr" +
      "y_after\030\006 \001(\0132\031.google.protobuf.Duration" +
      "R\nretryAfter\022O\n\020field_violations\030\007 \003(\0132$" +
      ".callscreen.common.v1.FieldViolationR\017fi" +
      "eldViolations\022%\n\016source_service\030\010 \001(\tR\rs" +
      "ourceService:\035\222\265\030\031\010\002\020\002\032\023callscreen/platf" +
      "orm*\343\007\n\tErrorCode\022\032\n\026ERROR_CODE_UNSPECIF" +
      "IED\020\000\022\027\n\023ERROR_CODE_INTERNAL\020\001\022\032\n\026ERROR_" +
      "CODE_UNAVAILABLE\020\002\022 \n\034ERROR_CODE_DEADLIN" +
      "E_EXCEEDED\020\003\022\030\n\024ERROR_CODE_CANCELLED\020\004\022)" +
      "\n%ERROR_CODE_UNSUPPORTED_CLIENT_VERSION\020" +
      "\005\022\036\n\032ERROR_CODE_UNAUTHENTICATED\020d\022!\n\035ERR" +
      "OR_CODE_INVALID_CREDENTIAL\020e\022 \n\034ERROR_CO" +
      "DE_PERMISSION_DENIED\020f\022!\n\035ERROR_CODE_ATT" +
      "ESTATION_FAILED\020g\022 \n\033ERROR_CODE_INVALID_" +
      "ARGUMENT\020\310\001\022&\n!ERROR_CODE_MISSING_REQUIR" +
      "ED_FIELD\020\311\001\022!\n\034ERROR_CODE_PAYLOAD_TOO_LA" +
      "RGE\020\312\001\022$\n\037ERROR_CODE_IDEMPOTENCY_CONFLIC" +
      "T\020\313\001\022\031\n\024ERROR_CODE_NOT_FOUND\020\254\002\022\036\n\031ERROR" +
      "_CODE_ALREADY_EXISTS\020\255\002\022#\n\036ERROR_CODE_FA" +
      "ILED_PRECONDITION\020\256\002\022 \n\033ERROR_CODE_VERSI" +
      "ON_CONFLICT\020\257\002\022\034\n\027ERROR_CODE_RATE_LIMITE" +
      "D\020\220\003\022\036\n\031ERROR_CODE_QUOTA_EXCEEDED\020\221\003\022%\n " +
      "ERROR_CODE_SUBSCRIPTION_REQUIRED\020\222\003\022 \n\033E" +
      "RROR_CODE_PAYMENT_REQUIRED\020\223\003\022 \n\033ERROR_C" +
      "ODE_UPSTREAM_FAILURE\020\364\003\022%\n ERROR_CODE_UP" +
      "STREAM_RATE_LIMITED\020\365\003\022%\n ERROR_CODE_NO_" +
      "PROVIDER_AVAILABLE\020\366\003\022 \n\033ERROR_CODE_POLI" +
      "CY_VIOLATION\020\330\004\022!\n\034ERROR_CODE_REGION_RES" +
      "TRICTED\020\331\004\022 \n\033ERROR_CODE_CONSENT_REQUIRE" +
      "D\020\332\004\022#\n\036ERROR_CODE_RESIDENCY_VIOLATION\020\333" +
      "\004B\217\002\n-com.callscreen.contracts.callscree" +
      "n.common.v1B\nErrorProtoP\001Z`github.com/ca" +
      "llscreen/callscreen-platform/packages/go" +
      "/contracts-go/callscreen/common/v1;commo" +
      "nv1\242\002\003CCX\252\002\024Callscreen.Common.V1\312\002\024Calls" +
      "creen\\Common\\V1\342\002 Callscreen\\Common\\V1\\G" +
      "PBMetadata\352\002\026Callscreen::Common::V1b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.callscreen.contracts.callscreen.common.v1.AnnotationsProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
        });
    internal_static_callscreen_common_v1_FieldViolation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_callscreen_common_v1_FieldViolation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_callscreen_common_v1_FieldViolation_descriptor,
        new java.lang.String[] { "Field", "Description", "UserMessageKey", });
    internal_static_callscreen_common_v1_Error_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_callscreen_common_v1_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_callscreen_common_v1_Error_descriptor,
        new java.lang.String[] { "Code", "Message", "UserMessageKey", "TraceId", "Retryable", "RetryAfter", "FieldViolations", "SourceService", });
    descriptor.resolveAllFeaturesImmutable();
    com.callscreen.contracts.callscreen.common.v1.AnnotationsProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.callscreen.contracts.callscreen.common.v1.AnnotationsProto.messageClassification);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
