// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/error.proto
// Protobuf Java Version: 4.29.3

package com.callscreen.contracts.callscreen.common.v1;

/**
 * <pre>
 * Error is the single error shape returned by every service in the platform.
 * </pre>
 *
 * Protobuf type {@code callscreen.common.v1.Error}
 */
public final class Error extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:callscreen.common.v1.Error)
    ErrorOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Error.class.getName());
  }
  // Use Error.newBuilder() to construct.
  private Error(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Error() {
    code_ = 0;
    message_ = "";
    userMessageKey_ = "";
    traceId_ = "";
    fieldViolations_ = java.util.Collections.emptyList();
    sourceService_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.callscreen.contracts.callscreen.common.v1.ErrorProto.internal_static_callscreen_common_v1_Error_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.callscreen.contracts.callscreen.common.v1.ErrorProto.internal_static_callscreen_common_v1_Error_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.callscreen.contracts.callscreen.common.v1.Error.class, com.callscreen.contracts.callscreen.common.v1.Error.Builder.class);
  }

  private int bitField0_;
  public static final int CODE_FIELD_NUMBER = 1;
  private int code_ = 0;
  /**
   * <pre>
   * Machine-readable classification. Clients branch on this and nothing else.
   * </pre>
   *
   * <code>.callscreen.common.v1.ErrorCode code = 1 [json_name = "code"];</code>
   * @return The enum numeric value on the wire for code.
   */
  @java.lang.Override public int getCodeValue() {
    return code_;
  }
  /**
   * <pre>
   * Machine-readable classification. Clients branch on this and nothing else.
   * </pre>
   *
   * <code>.callscreen.common.v1.ErrorCode code = 1 [json_name = "code"];</code>
   * @return The code.
   */
  @java.lang.Override public com.callscreen.contracts.callscreen.common.v1.ErrorCode getCode() {
    com.callscreen.contracts.callscreen.common.v1.ErrorCode result = com.callscreen.contracts.callscreen.common.v1.ErrorCode.forNumber(code_);
    return result == null ? com.callscreen.contracts.callscreen.common.v1.ErrorCode.UNRECOGNIZED : result;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <pre>
   * Engineer-facing detail. English, never localised, never shown to a user.
   * May name internal components; treated as INTERNAL sensitivity and therefore
   * excluded from any client-visible surface in release builds.
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Engineer-facing detail. English, never localised, never shown to a user.
   * May name internal components; treated as INTERNAL sensitivity and therefore
   * excluded from any client-visible surface in release builds.
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_MESSAGE_KEY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userMessageKey_ = "";
  /**
   * <pre>
   * Localisation key the client resolves against its own string catalogue.
   * Empty when the error is not intended to be surfaced to the user at all.
   * </pre>
   *
   * <code>string user_message_key = 3 [json_name = "userMessageKey"];</code>
   * @return The userMessageKey.
   */
  @java.lang.Override
  public java.lang.String getUserMessageKey() {
    java.lang.Object ref = userMessageKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userMessageKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Localisation key the client resolves against its own string catalogue.
   * Empty when the error is not intended to be surfaced to the user at all.
   * </pre>
   *
   * <code>string user_message_key = 3 [json_name = "userMessageKey"];</code>
   * @return The bytes for userMessageKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserMessageKeyBytes() {
    java.lang.Object ref = userMessageKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userMessageKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRACE_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object traceId_ = "";
  /**
   * <pre>
   * Correlation identifier tying this error to a distributed trace. Shown in
   * support flows so an engineer can locate the exact request.
   * </pre>
   *
   * <code>string trace_id = 4 [json_name = "traceId"];</code>
   * @return The traceId.
   */
  @java.lang.Override
  public java.lang.String getTraceId() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Correlation identifier tying this error to a distributed trace. Shown in
   * support flows so an engineer can locate the exact request.
   * </pre>
   *
   * <code>string trace_id = 4 [json_name = "traceId"];</code>
   * @return The bytes for traceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTraceIdBytes() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETRYABLE_FIELD_NUMBER = 5;
  private boolean retryable_ = false;
  /**
   * <pre>
   * Whether retrying the identical request could succeed. Explicit rather than
   * inferred, so that retry behaviour is a contract and not a convention.
   * </pre>
   *
   * <code>bool retryable = 5 [json_name = "retryable"];</code>
   * @return The retryable.
   */
  @java.lang.Override
  public boolean getRetryable() {
    return retryable_;
  }

  public static final int RETRY_AFTER_FIELD_NUMBER = 6;
  private com.google.protobuf.Duration retryAfter_;
  /**
   * <pre>
   * How long the client should wait before retrying. Only meaningful when
   * `retryable` is true. Always populated for RATE_LIMITED.
   * </pre>
   *
   * <code>.google.protobuf.Duration retry_after = 6 [json_name = "retryAfter"];</code>
   * @return Whether the retryAfter field is set.
   */
  @java.lang.Override
  public boolean hasRetryAfter() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * How long the client should wait before retrying. Only meaningful when
   * `retryable` is true. Always populated for RATE_LIMITED.
   * </pre>
   *
   * <code>.google.protobuf.Duration retry_after = 6 [json_name = "retryAfter"];</code>
   * @return The retryAfter.
   */
  @java.lang.Override
  public com.google.protobuf.Duration getRetryAfter() {
    return retryAfter_ == null ? com.google.protobuf.Duration.getDefaultInstance() : retryAfter_;
  }
  /**
   * <pre>
   * How long the client should wait before retrying. Only meaningful when
   * `retryable` is true. Always populated for RATE_LIMITED.
   * </pre>
   *
   * <code>.google.protobuf.Duration retry_after = 6 [json_name = "retryAfter"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.DurationOrBuilder getRetryAfterOrBuilder() {
    return retryAfter_ == null ? com.google.protobuf.Duration.getDefaultInstance() : retryAfter_;
  }

  public static final int FIELD_VIOLATIONS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<com.callscreen.contracts.callscreen.common.v1.FieldViolation> fieldViolations_;
  /**
   * <pre>
   * Per-field detail for validation failures. Empty for non-validation errors.
   * </pre>
   *
   * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
   */
  @java.lang.Override
  public java.util.List<com.callscreen.contracts.callscreen.common.v1.FieldViolation> getFieldViolationsList() {
    return fieldViolations_;
  }
  /**
   * <pre>
   * Per-field detail for validation failures. Empty for non-validation errors.
   * </pre>
   *
   * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.callscreen.contracts.callscreen.common.v1.FieldViolationOrBuilder> 
      getFieldViolationsOrBuilderList() {
    return fieldViolations_;
  }
  /**
   * <pre>
   * Per-field detail for validation failures. Empty for non-validation errors.
   * </pre>
   *
   * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
   */
  @java.lang.Override
  public int getFieldViolationsCount() {
    return fieldViolations_.size();
  }
  /**
   * <pre>
   * Per-field detail for validation failures. Empty for non-validation errors.
   * </pre>
   *
   * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
   */
  @java.lang.Override
  public com.callscreen.contracts.callscreen.common.v1.FieldViolation getFieldViolations(int index) {
    return fieldViolations_.get(index);
  }
  /**
   * <pre>
   * Per-field detail for validation failures. Empty for non-validation errors.
   * </pre>
   *
   * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
   */
  @java.lang.Override
  public com.callscreen.contracts.callscreen.common.v1.FieldViolationOrBuilder getFieldViolationsOrBuilder(
      int index) {
    return fieldViolations_.get(index);
  }

  public static final int SOURCE_SERVICE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceService_ = "";
  /**
   * <pre>
   * Stable identifier of the service that produced the error, matching the
   * directory name under services/. Used to attribute error budget burn.
   * </pre>
   *
   * <code>string source_service = 8 [json_name = "sourceService"];</code>
   * @return The sourceService.
   */
  @java.lang.Override
  public java.lang.String getSourceService() {
    java.lang.Object ref = sourceService_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceService_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Stable identifier of the service that produced the error, matching the
   * directory name under services/. Used to attribute error budget burn.
   * </pre>
   *
   * <code>string source_service = 8 [json_name = "sourceService"];</code>
   * @return The bytes for sourceService.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceServiceBytes() {
    java.lang.Object ref = sourceService_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceService_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != com.callscreen.contracts.callscreen.common.v1.ErrorCode.ERROR_CODE_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, code_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, message_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userMessageKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, userMessageKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(traceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, traceId_);
    }
    if (retryable_ != false) {
      output.writeBool(5, retryable_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getRetryAfter());
    }
    for (int i = 0; i < fieldViolations_.size(); i++) {
      output.writeMessage(7, fieldViolations_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceService_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, sourceService_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != com.callscreen.contracts.callscreen.common.v1.ErrorCode.ERROR_CODE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, code_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, message_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userMessageKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, userMessageKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(traceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, traceId_);
    }
    if (retryable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, retryable_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getRetryAfter());
    }
    for (int i = 0; i < fieldViolations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, fieldViolations_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceService_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, sourceService_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.callscreen.contracts.callscreen.common.v1.Error)) {
      return super.equals(obj);
    }
    com.callscreen.contracts.callscreen.common.v1.Error other = (com.callscreen.contracts.callscreen.common.v1.Error) obj;

    if (code_ != other.code_) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getUserMessageKey()
        .equals(other.getUserMessageKey())) return false;
    if (!getTraceId()
        .equals(other.getTraceId())) return false;
    if (getRetryable()
        != other.getRetryable()) return false;
    if (hasRetryAfter() != other.hasRetryAfter()) return false;
    if (hasRetryAfter()) {
      if (!getRetryAfter()
          .equals(other.getRetryAfter())) return false;
    }
    if (!getFieldViolationsList()
        .equals(other.getFieldViolationsList())) return false;
    if (!getSourceService()
        .equals(other.getSourceService())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + code_;
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + USER_MESSAGE_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getUserMessageKey().hashCode();
    hash = (37 * hash) + TRACE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTraceId().hashCode();
    hash = (37 * hash) + RETRYABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRetryable());
    if (hasRetryAfter()) {
      hash = (37 * hash) + RETRY_AFTER_FIELD_NUMBER;
      hash = (53 * hash) + getRetryAfter().hashCode();
    }
    if (getFieldViolationsCount() > 0) {
      hash = (37 * hash) + FIELD_VIOLATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getFieldViolationsList().hashCode();
    }
    hash = (37 * hash) + SOURCE_SERVICE_FIELD_NUMBER;
    hash = (53 * hash) + getSourceService().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.callscreen.contracts.callscreen.common.v1.Error parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Error parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Error parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Error parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Error parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Error parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Error parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Error parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.callscreen.contracts.callscreen.common.v1.Error parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.callscreen.contracts.callscreen.common.v1.Error parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Error parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Error parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.callscreen.contracts.callscreen.common.v1.Error prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Error is the single error shape returned by every service in the platform.
   * </pre>
   *
   * Protobuf type {@code callscreen.common.v1.Error}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:callscreen.common.v1.Error)
      com.callscreen.contracts.callscreen.common.v1.ErrorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.callscreen.contracts.callscreen.common.v1.ErrorProto.internal_static_callscreen_common_v1_Error_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.callscreen.contracts.callscreen.common.v1.ErrorProto.internal_static_callscreen_common_v1_Error_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.callscreen.contracts.callscreen.common.v1.Error.class, com.callscreen.contracts.callscreen.common.v1.Error.Builder.class);
    }

    // Construct using com.callscreen.contracts.callscreen.common.v1.Error.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getRetryAfterFieldBuilder();
        getFieldViolationsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      code_ = 0;
      message_ = "";
      userMessageKey_ = "";
      traceId_ = "";
      retryable_ = false;
      retryAfter_ = null;
      if (retryAfterBuilder_ != null) {
        retryAfterBuilder_.dispose();
        retryAfterBuilder_ = null;
      }
      if (fieldViolationsBuilder_ == null) {
        fieldViolations_ = java.util.Collections.emptyList();
      } else {
        fieldViolations_ = null;
        fieldViolationsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      sourceService_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.callscreen.contracts.callscreen.common.v1.ErrorProto.internal_static_callscreen_common_v1_Error_descriptor;
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.Error getDefaultInstanceForType() {
      return com.callscreen.contracts.callscreen.common.v1.Error.getDefaultInstance();
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.Error build() {
      com.callscreen.contracts.callscreen.common.v1.Error result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.Error buildPartial() {
      com.callscreen.contracts.callscreen.common.v1.Error result = new com.callscreen.contracts.callscreen.common.v1.Error(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.callscreen.contracts.callscreen.common.v1.Error result) {
      if (fieldViolationsBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          fieldViolations_ = java.util.Collections.unmodifiableList(fieldViolations_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.fieldViolations_ = fieldViolations_;
      } else {
        result.fieldViolations_ = fieldViolationsBuilder_.build();
      }
    }

    private void buildPartial0(com.callscreen.contracts.callscreen.common.v1.Error result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.code_ = code_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.message_ = message_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.userMessageKey_ = userMessageKey_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.traceId_ = traceId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.retryable_ = retryable_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.retryAfter_ = retryAfterBuilder_ == null
            ? retryAfter_
            : retryAfterBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.sourceService_ = sourceService_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.callscreen.contracts.callscreen.common.v1.Error) {
        return mergeFrom((com.callscreen.contracts.callscreen.common.v1.Error)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.callscreen.contracts.callscreen.common.v1.Error other) {
      if (other == com.callscreen.contracts.callscreen.common.v1.Error.getDefaultInstance()) return this;
      if (other.code_ != 0) {
        setCodeValue(other.getCodeValue());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getUserMessageKey().isEmpty()) {
        userMessageKey_ = other.userMessageKey_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getTraceId().isEmpty()) {
        traceId_ = other.traceId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getRetryable() != false) {
        setRetryable(other.getRetryable());
      }
      if (other.hasRetryAfter()) {
        mergeRetryAfter(other.getRetryAfter());
      }
      if (fieldViolationsBuilder_ == null) {
        if (!other.fieldViolations_.isEmpty()) {
          if (fieldViolations_.isEmpty()) {
            fieldViolations_ = other.fieldViolations_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureFieldViolationsIsMutable();
            fieldViolations_.addAll(other.fieldViolations_);
          }
          onChanged();
        }
      } else {
        if (!other.fieldViolations_.isEmpty()) {
          if (fieldViolationsBuilder_.isEmpty()) {
            fieldViolationsBuilder_.dispose();
            fieldViolationsBuilder_ = null;
            fieldViolations_ = other.fieldViolations_;
            bitField0_ = (bitField0_ & ~0x00000040);
            fieldViolationsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getFieldViolationsFieldBuilder() : null;
          } else {
            fieldViolationsBuilder_.addAllMessages(other.fieldViolations_);
          }
        }
      }
      if (!other.getSourceService().isEmpty()) {
        sourceService_ = other.sourceService_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              code_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              userMessageKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              traceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              retryable_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              input.readMessage(
                  getRetryAfterFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              com.callscreen.contracts.callscreen.common.v1.FieldViolation m =
                  input.readMessage(
                      com.callscreen.contracts.callscreen.common.v1.FieldViolation.parser(),
                      extensionRegistry);
              if (fieldViolationsBuilder_ == null) {
                ensureFieldViolationsIsMutable();
                fieldViolations_.add(m);
              } else {
                fieldViolationsBuilder_.addMessage(m);
              }
              break;
            } // case 58
            case 66: {
              sourceService_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int code_ = 0;
    /**
     * <pre>
     * Machine-readable classification. Clients branch on this and nothing else.
     * </pre>
     *
     * <code>.callscreen.common.v1.ErrorCode code = 1 [json_name = "code"];</code>
     * @return The enum numeric value on the wire for code.
     */
    @java.lang.Override public int getCodeValue() {
      return code_;
    }
    /**
     * <pre>
     * Machine-readable classification. Clients branch on this and nothing else.
     * </pre>
     *
     * <code>.callscreen.common.v1.ErrorCode code = 1 [json_name = "code"];</code>
     * @param value The enum numeric value on the wire for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeValue(int value) {
      code_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Machine-readable classification. Clients branch on this and nothing else.
     * </pre>
     *
     * <code>.callscreen.common.v1.ErrorCode code = 1 [json_name = "code"];</code>
     * @return The code.
     */
    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.ErrorCode getCode() {
      com.callscreen.contracts.callscreen.common.v1.ErrorCode result = com.callscreen.contracts.callscreen.common.v1.ErrorCode.forNumber(code_);
      return result == null ? com.callscreen.contracts.callscreen.common.v1.ErrorCode.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Machine-readable classification. Clients branch on this and nothing else.
     * </pre>
     *
     * <code>.callscreen.common.v1.ErrorCode code = 1 [json_name = "code"];</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(com.callscreen.contracts.callscreen.common.v1.ErrorCode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      code_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Machine-readable classification. Clients branch on this and nothing else.
     * </pre>
     *
     * <code>.callscreen.common.v1.ErrorCode code = 1 [json_name = "code"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <pre>
     * Engineer-facing detail. English, never localised, never shown to a user.
     * May name internal components; treated as INTERNAL sensitivity and therefore
     * excluded from any client-visible surface in release builds.
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Engineer-facing detail. English, never localised, never shown to a user.
     * May name internal components; treated as INTERNAL sensitivity and therefore
     * excluded from any client-visible surface in release builds.
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Engineer-facing detail. English, never localised, never shown to a user.
     * May name internal components; treated as INTERNAL sensitivity and therefore
     * excluded from any client-visible surface in release builds.
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Engineer-facing detail. English, never localised, never shown to a user.
     * May name internal components; treated as INTERNAL sensitivity and therefore
     * excluded from any client-visible surface in release builds.
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Engineer-facing detail. English, never localised, never shown to a user.
     * May name internal components; treated as INTERNAL sensitivity and therefore
     * excluded from any client-visible surface in release builds.
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object userMessageKey_ = "";
    /**
     * <pre>
     * Localisation key the client resolves against its own string catalogue.
     * Empty when the error is not intended to be surfaced to the user at all.
     * </pre>
     *
     * <code>string user_message_key = 3 [json_name = "userMessageKey"];</code>
     * @return The userMessageKey.
     */
    public java.lang.String getUserMessageKey() {
      java.lang.Object ref = userMessageKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userMessageKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Localisation key the client resolves against its own string catalogue.
     * Empty when the error is not intended to be surfaced to the user at all.
     * </pre>
     *
     * <code>string user_message_key = 3 [json_name = "userMessageKey"];</code>
     * @return The bytes for userMessageKey.
     */
    public com.google.protobuf.ByteString
        getUserMessageKeyBytes() {
      java.lang.Object ref = userMessageKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userMessageKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Localisation key the client resolves against its own string catalogue.
     * Empty when the error is not intended to be surfaced to the user at all.
     * </pre>
     *
     * <code>string user_message_key = 3 [json_name = "userMessageKey"];</code>
     * @param value The userMessageKey to set.
     * @return This builder for chaining.
     */
    public Builder setUserMessageKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userMessageKey_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Localisation key the client resolves against its own string catalogue.
     * Empty when the error is not intended to be surfaced to the user at all.
     * </pre>
     *
     * <code>string user_message_key = 3 [json_name = "userMessageKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserMessageKey() {
      userMessageKey_ = getDefaultInstance().getUserMessageKey();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Localisation key the client resolves against its own string catalogue.
     * Empty when the error is not intended to be surfaced to the user at all.
     * </pre>
     *
     * <code>string user_message_key = 3 [json_name = "userMessageKey"];</code>
     * @param value The bytes for userMessageKey to set.
     * @return This builder for chaining.
     */
    public Builder setUserMessageKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userMessageKey_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object traceId_ = "";
    /**
     * <pre>
     * Correlation identifier tying this error to a distributed trace. Shown in
     * support flows so an engineer can locate the exact request.
     * </pre>
     *
     * <code>string trace_id = 4 [json_name = "traceId"];</code>
     * @return The traceId.
     */
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Correlation identifier tying this error to a distributed trace. Shown in
     * support flows so an engineer can locate the exact request.
     * </pre>
     *
     * <code>string trace_id = 4 [json_name = "traceId"];</code>
     * @return The bytes for traceId.
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Correlation identifier tying this error to a distributed trace. Shown in
     * support flows so an engineer can locate the exact request.
     * </pre>
     *
     * <code>string trace_id = 4 [json_name = "traceId"];</code>
     * @param value The traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      traceId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Correlation identifier tying this error to a distributed trace. Shown in
     * support flows so an engineer can locate the exact request.
     * </pre>
     *
     * <code>string trace_id = 4 [json_name = "traceId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceId() {
      traceId_ = getDefaultInstance().getTraceId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Correlation identifier tying this error to a distributed trace. Shown in
     * support flows so an engineer can locate the exact request.
     * </pre>
     *
     * <code>string trace_id = 4 [json_name = "traceId"];</code>
     * @param value The bytes for traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      traceId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private boolean retryable_ ;
    /**
     * <pre>
     * Whether retrying the identical request could succeed. Explicit rather than
     * inferred, so that retry behaviour is a contract and not a convention.
     * </pre>
     *
     * <code>bool retryable = 5 [json_name = "retryable"];</code>
     * @return The retryable.
     */
    @java.lang.Override
    public boolean getRetryable() {
      return retryable_;
    }
    /**
     * <pre>
     * Whether retrying the identical request could succeed. Explicit rather than
     * inferred, so that retry behaviour is a contract and not a convention.
     * </pre>
     *
     * <code>bool retryable = 5 [json_name = "retryable"];</code>
     * @param value The retryable to set.
     * @return This builder for chaining.
     */
    public Builder setRetryable(boolean value) {

      retryable_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether retrying the identical request could succeed. Explicit rather than
     * inferred, so that retry behaviour is a contract and not a convention.
     * </pre>
     *
     * <code>bool retryable = 5 [json_name = "retryable"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRetryable() {
      bitField0_ = (bitField0_ & ~0x00000010);
      retryable_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.Duration retryAfter_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> retryAfterBuilder_;
    /**
     * <pre>
     * How long the client should wait before retrying. Only meaningful when
     * `retryable` is true. Always populated for RATE_LIMITED.
     * </pre>
     *
     * <code>.google.protobuf.Duration retry_after = 6 [json_name = "retryAfter"];</code>
     * @return Whether the retryAfter field is set.
     */
    public boolean hasRetryAfter() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * How long the client should wait before retrying. Only meaningful when
     * `retryable` is true. Always populated for RATE_LIMITED.
     * </pre>
     *
     * <code>.google.protobuf.Duration retry_after = 6 [json_name = "retryAfter"];</code>
     * @return The retryAfter.
     */
    public com.google.protobuf.Duration getRetryAfter() {
      if (retryAfterBuilder_ == null) {
        return retryAfter_ == null ? com.google.protobuf.Duration.getDefaultInstance() : retryAfter_;
      } else {
        return retryAfterBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * How long the client should wait before retrying. Only meaningful when
     * `retryable` is true. Always populated for RATE_LIMITED.
     * </pre>
     *
     * <code>.google.protobuf.Duration retry_after = 6 [json_name = "retryAfter"];</code>
     */
    public Builder setRetryAfter(com.google.protobuf.Duration value) {
      if (retryAfterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        retryAfter_ = value;
      } else {
        retryAfterBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How long the client should wait before retrying. Only meaningful when
     * `retryable` is true. Always populated for RATE_LIMITED.
     * </pre>
     *
     * <code>.google.protobuf.Duration retry_after = 6 [json_name = "retryAfter"];</code>
     */
    public Builder setRetryAfter(
        com.google.protobuf.Duration.Builder builderForValue) {
      if (retryAfterBuilder_ == null) {
        retryAfter_ = builderForValue.build();
      } else {
        retryAfterBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How long the client should wait before retrying. Only meaningful when
     * `retryable` is true. Always populated for RATE_LIMITED.
     * </pre>
     *
     * <code>.google.protobuf.Duration retry_after = 6 [json_name = "retryAfter"];</code>
     */
    public Builder mergeRetryAfter(com.google.protobuf.Duration value) {
      if (retryAfterBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          retryAfter_ != null &&
          retryAfter_ != com.google.protobuf.Duration.getDefaultInstance()) {
          getRetryAfterBuilder().mergeFrom(value);
        } else {
          retryAfter_ = value;
        }
      } else {
        retryAfterBuilder_.mergeFrom(value);
      }
      if (retryAfter_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * How long the client should wait before retrying. Only meaningful when
     * `retryable` is true. Always populated for RATE_LIMITED.
     * </pre>
     *
     * <code>.google.protobuf.Duration retry_after = 6 [json_name = "retryAfter"];</code>
     */
    public Builder clearRetryAfter() {
      bitField0_ = (bitField0_ & ~0x00000020);
      retryAfter_ = null;
      if (retryAfterBuilder_ != null) {
        retryAfterBuilder_.dispose();
        retryAfterBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How long the client should wait before retrying. Only meaningful when
     * `retryable` is true. Always populated for RATE_LIMITED.
     * </pre>
     *
     * <code>.google.protobuf.Duration retry_after = 6 [json_name = "retryAfter"];</code>
     */
    public com.google.protobuf.Duration.Builder getRetryAfterBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getRetryAfterFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * How long the client should wait before retrying. Only meaningful when
     * `retryable` is true. Always populated for RATE_LIMITED.
     * </pre>
     *
     * <code>.google.protobuf.Duration retry_after = 6 [json_name = "retryAfter"];</code>
     */
    public com.google.protobuf.DurationOrBuilder getRetryAfterOrBuilder() {
      if (retryAfterBuilder_ != null) {
        return retryAfterBuilder_.getMessageOrBuilder();
      } else {
        return retryAfter_ == null ?
            com.google.protobuf.Duration.getDefaultInstance() : retryAfter_;
      }
    }
    /**
     * <pre>
     * How long the client should wait before retrying. Only meaningful when
     * `retryable` is true. Always populated for RATE_LIMITED.
     * </pre>
     *
     * <code>.google.protobuf.Duration retry_after = 6 [json_name = "retryAfter"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
        getRetryAfterFieldBuilder() {
      if (retryAfterBuilder_ == null) {
        retryAfterBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                getRetryAfter(),
                getParentForChildren(),
                isClean());
        retryAfter_ = null;
      }
      return retryAfterBuilder_;
    }

    private java.util.List<com.callscreen.contracts.callscreen.common.v1.FieldViolation> fieldViolations_ =
      java.util.Collections.emptyList();
    private void ensureFieldViolationsIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        fieldViolations_ = new java.util.ArrayList<com.callscreen.contracts.callscreen.common.v1.FieldViolation>(fieldViolations_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.callscreen.contracts.callscreen.common.v1.FieldViolation, com.callscreen.contracts.callscreen.common.v1.FieldViolation.Builder, com.callscreen.contracts.callscreen.common.v1.FieldViolationOrBuilder> fieldViolationsBuilder_;

    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public java.util.List<com.callscreen.contracts.callscreen.common.v1.FieldViolation> getFieldViolationsList() {
      if (fieldViolationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fieldViolations_);
      } else {
        return fieldViolationsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public int getFieldViolationsCount() {
      if (fieldViolationsBuilder_ == null) {
        return fieldViolations_.size();
      } else {
        return fieldViolationsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public com.callscreen.contracts.callscreen.common.v1.FieldViolation getFieldViolations(int index) {
      if (fieldViolationsBuilder_ == null) {
        return fieldViolations_.get(index);
      } else {
        return fieldViolationsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public Builder setFieldViolations(
        int index, com.callscreen.contracts.callscreen.common.v1.FieldViolation value) {
      if (fieldViolationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldViolationsIsMutable();
        fieldViolations_.set(index, value);
        onChanged();
      } else {
        fieldViolationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public Builder setFieldViolations(
        int index, com.callscreen.contracts.callscreen.common.v1.FieldViolation.Builder builderForValue) {
      if (fieldViolationsBuilder_ == null) {
        ensureFieldViolationsIsMutable();
        fieldViolations_.set(index, builderForValue.build());
        onChanged();
      } else {
        fieldViolationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public Builder addFieldViolations(com.callscreen.contracts.callscreen.common.v1.FieldViolation value) {
      if (fieldViolationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldViolationsIsMutable();
        fieldViolations_.add(value);
        onChanged();
      } else {
        fieldViolationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public Builder addFieldViolations(
        int index, com.callscreen.contracts.callscreen.common.v1.FieldViolation value) {
      if (fieldViolationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldViolationsIsMutable();
        fieldViolations_.add(index, value);
        onChanged();
      } else {
        fieldViolationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public Builder addFieldViolations(
        com.callscreen.contracts.callscreen.common.v1.FieldViolation.Builder builderForValue) {
      if (fieldViolationsBuilder_ == null) {
        ensureFieldViolationsIsMutable();
        fieldViolations_.add(builderForValue.build());
        onChanged();
      } else {
        fieldViolationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public Builder addFieldViolations(
        int index, com.callscreen.contracts.callscreen.common.v1.FieldViolation.Builder builderForValue) {
      if (fieldViolationsBuilder_ == null) {
        ensureFieldViolationsIsMutable();
        fieldViolations_.add(index, builderForValue.build());
        onChanged();
      } else {
        fieldViolationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public Builder addAllFieldViolations(
        java.lang.Iterable<? extends com.callscreen.contracts.callscreen.common.v1.FieldViolation> values) {
      if (fieldViolationsBuilder_ == null) {
        ensureFieldViolationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fieldViolations_);
        onChanged();
      } else {
        fieldViolationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public Builder clearFieldViolations() {
      if (fieldViolationsBuilder_ == null) {
        fieldViolations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        fieldViolationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public Builder removeFieldViolations(int index) {
      if (fieldViolationsBuilder_ == null) {
        ensureFieldViolationsIsMutable();
        fieldViolations_.remove(index);
        onChanged();
      } else {
        fieldViolationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public com.callscreen.contracts.callscreen.common.v1.FieldViolation.Builder getFieldViolationsBuilder(
        int index) {
      return getFieldViolationsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public com.callscreen.contracts.callscreen.common.v1.FieldViolationOrBuilder getFieldViolationsOrBuilder(
        int index) {
      if (fieldViolationsBuilder_ == null) {
        return fieldViolations_.get(index);  } else {
        return fieldViolationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public java.util.List<? extends com.callscreen.contracts.callscreen.common.v1.FieldViolationOrBuilder> 
         getFieldViolationsOrBuilderList() {
      if (fieldViolationsBuilder_ != null) {
        return fieldViolationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fieldViolations_);
      }
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public com.callscreen.contracts.callscreen.common.v1.FieldViolation.Builder addFieldViolationsBuilder() {
      return getFieldViolationsFieldBuilder().addBuilder(
          com.callscreen.contracts.callscreen.common.v1.FieldViolation.getDefaultInstance());
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public com.callscreen.contracts.callscreen.common.v1.FieldViolation.Builder addFieldViolationsBuilder(
        int index) {
      return getFieldViolationsFieldBuilder().addBuilder(
          index, com.callscreen.contracts.callscreen.common.v1.FieldViolation.getDefaultInstance());
    }
    /**
     * <pre>
     * Per-field detail for validation failures. Empty for non-validation errors.
     * </pre>
     *
     * <code>repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];</code>
     */
    public java.util.List<com.callscreen.contracts.callscreen.common.v1.FieldViolation.Builder> 
         getFieldViolationsBuilderList() {
      return getFieldViolationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.callscreen.contracts.callscreen.common.v1.FieldViolation, com.callscreen.contracts.callscreen.common.v1.FieldViolation.Builder, com.callscreen.contracts.callscreen.common.v1.FieldViolationOrBuilder> 
        getFieldViolationsFieldBuilder() {
      if (fieldViolationsBuilder_ == null) {
        fieldViolationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.callscreen.contracts.callscreen.common.v1.FieldViolation, com.callscreen.contracts.callscreen.common.v1.FieldViolation.Builder, com.callscreen.contracts.callscreen.common.v1.FieldViolationOrBuilder>(
                fieldViolations_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        fieldViolations_ = null;
      }
      return fieldViolationsBuilder_;
    }

    private java.lang.Object sourceService_ = "";
    /**
     * <pre>
     * Stable identifier of the service that produced the error, matching the
     * directory name under services/. Used to attribute error budget burn.
     * </pre>
     *
     * <code>string source_service = 8 [json_name = "sourceService"];</code>
     * @return The sourceService.
     */
    public java.lang.String getSourceService() {
      java.lang.Object ref = sourceService_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceService_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Stable identifier of the service that produced the error, matching the
     * directory name under services/. Used to attribute error budget burn.
     * </pre>
     *
     * <code>string source_service = 8 [json_name = "sourceService"];</code>
     * @return The bytes for sourceService.
     */
    public com.google.protobuf.ByteString
        getSourceServiceBytes() {
      java.lang.Object ref = sourceService_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceService_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Stable identifier of the service that produced the error, matching the
     * directory name under services/. Used to attribute error budget burn.
     * </pre>
     *
     * <code>string source_service = 8 [json_name = "sourceService"];</code>
     * @param value The sourceService to set.
     * @return This builder for chaining.
     */
    public Builder setSourceService(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceService_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stable identifier of the service that produced the error, matching the
     * directory name under services/. Used to attribute error budget burn.
     * </pre>
     *
     * <code>string source_service = 8 [json_name = "sourceService"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceService() {
      sourceService_ = getDefaultInstance().getSourceService();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stable identifier of the service that produced the error, matching the
     * directory name under services/. Used to attribute error budget burn.
     * </pre>
     *
     * <code>string source_service = 8 [json_name = "sourceService"];</code>
     * @param value The bytes for sourceService to set.
     * @return This builder for chaining.
     */
    public Builder setSourceServiceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceService_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:callscreen.common.v1.Error)
  }

  // @@protoc_insertion_point(class_scope:callscreen.common.v1.Error)
  private static final com.callscreen.contracts.callscreen.common.v1.Error DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.callscreen.contracts.callscreen.common.v1.Error();
  }

  public static com.callscreen.contracts.callscreen.common.v1.Error getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Error>
      PARSER = new com.google.protobuf.AbstractParser<Error>() {
    @java.lang.Override
    public Error parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Error> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Error> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.callscreen.contracts.callscreen.common.v1.Error getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

