// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/error.proto
// Protobuf Java Version: 4.29.3

package com.callscreen.contracts.callscreen.common.v1;

/**
 * <pre>
 * FieldViolation identifies a single invalid field within a request.
 * </pre>
 *
 * Protobuf type {@code callscreen.common.v1.FieldViolation}
 */
public final class FieldViolation extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:callscreen.common.v1.FieldViolation)
    FieldViolationOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      FieldViolation.class.getName());
  }
  // Use FieldViolation.newBuilder() to construct.
  private FieldViolation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FieldViolation() {
    field_ = "";
    description_ = "";
    userMessageKey_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.callscreen.contracts.callscreen.common.v1.ErrorProto.internal_static_callscreen_common_v1_FieldViolation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.callscreen.contracts.callscreen.common.v1.ErrorProto.internal_static_callscreen_common_v1_FieldViolation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.callscreen.contracts.callscreen.common.v1.FieldViolation.class, com.callscreen.contracts.callscreen.common.v1.FieldViolation.Builder.class);
  }

  public static final int FIELD_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object field_ = "";
  /**
   * <pre>
   * Dotted path to the offending field, for example "session.caller_number".
   * </pre>
   *
   * <code>string field = 1 [json_name = "field"];</code>
   * @return The field.
   */
  @java.lang.Override
  public java.lang.String getField() {
    java.lang.Object ref = field_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Dotted path to the offending field, for example "session.caller_number".
   * </pre>
   *
   * <code>string field = 1 [json_name = "field"];</code>
   * @return The bytes for field.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFieldBytes() {
    java.lang.Object ref = field_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <pre>
   * Engineer-facing description of why it was rejected.
   * </pre>
   *
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Engineer-facing description of why it was rejected.
   * </pre>
   *
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_MESSAGE_KEY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userMessageKey_ = "";
  /**
   * <pre>
   * Localisation key for the message shown to the user beside the input.
   * </pre>
   *
   * <code>string user_message_key = 3 [json_name = "userMessageKey"];</code>
   * @return The userMessageKey.
   */
  @java.lang.Override
  public java.lang.String getUserMessageKey() {
    java.lang.Object ref = userMessageKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userMessageKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Localisation key for the message shown to the user beside the input.
   * </pre>
   *
   * <code>string user_message_key = 3 [json_name = "userMessageKey"];</code>
   * @return The bytes for userMessageKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserMessageKeyBytes() {
    java.lang.Object ref = userMessageKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userMessageKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(field_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, field_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userMessageKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, userMessageKey_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(field_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, field_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userMessageKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, userMessageKey_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.callscreen.contracts.callscreen.common.v1.FieldViolation)) {
      return super.equals(obj);
    }
    com.callscreen.contracts.callscreen.common.v1.FieldViolation other = (com.callscreen.contracts.callscreen.common.v1.FieldViolation) obj;

    if (!getField()
        .equals(other.getField())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getUserMessageKey()
        .equals(other.getUserMessageKey())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FIELD_FIELD_NUMBER;
    hash = (53 * hash) + getField().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + USER_MESSAGE_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getUserMessageKey().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.callscreen.contracts.callscreen.common.v1.FieldViolation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldViolation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldViolation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldViolation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldViolation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldViolation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldViolation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldViolation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.callscreen.contracts.callscreen.common.v1.FieldViolation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.callscreen.contracts.callscreen.common.v1.FieldViolation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldViolation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldViolation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.callscreen.contracts.callscreen.common.v1.FieldViolation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * FieldViolation identifies a single invalid field within a request.
   * </pre>
   *
   * Protobuf type {@code callscreen.common.v1.FieldViolation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:callscreen.common.v1.FieldViolation)
      com.callscreen.contracts.callscreen.common.v1.FieldViolationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.callscreen.contracts.callscreen.common.v1.ErrorProto.internal_static_callscreen_common_v1_FieldViolation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.callscreen.contracts.callscreen.common.v1.ErrorProto.internal_static_callscreen_common_v1_FieldViolation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.callscreen.contracts.callscreen.common.v1.FieldViolation.class, com.callscreen.contracts.callscreen.common.v1.FieldViolation.Builder.class);
    }

    // Construct using com.callscreen.contracts.callscreen.common.v1.FieldViolation.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      field_ = "";
      description_ = "";
      userMessageKey_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.callscreen.contracts.callscreen.common.v1.ErrorProto.internal_static_callscreen_common_v1_FieldViolation_descriptor;
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.FieldViolation getDefaultInstanceForType() {
      return com.callscreen.contracts.callscreen.common.v1.FieldViolation.getDefaultInstance();
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.FieldViolation build() {
      com.callscreen.contracts.callscreen.common.v1.FieldViolation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.FieldViolation buildPartial() {
      com.callscreen.contracts.callscreen.common.v1.FieldViolation result = new com.callscreen.contracts.callscreen.common.v1.FieldViolation(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.callscreen.contracts.callscreen.common.v1.FieldViolation result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.field_ = field_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.userMessageKey_ = userMessageKey_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.callscreen.contracts.callscreen.common.v1.FieldViolation) {
        return mergeFrom((com.callscreen.contracts.callscreen.common.v1.FieldViolation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.callscreen.contracts.callscreen.common.v1.FieldViolation other) {
      if (other == com.callscreen.contracts.callscreen.common.v1.FieldViolation.getDefaultInstance()) return this;
      if (!other.getField().isEmpty()) {
        field_ = other.field_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getUserMessageKey().isEmpty()) {
        userMessageKey_ = other.userMessageKey_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              field_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              userMessageKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object field_ = "";
    /**
     * <pre>
     * Dotted path to the offending field, for example "session.caller_number".
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @return The field.
     */
    public java.lang.String getField() {
      java.lang.Object ref = field_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Dotted path to the offending field, for example "session.caller_number".
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @return The bytes for field.
     */
    public com.google.protobuf.ByteString
        getFieldBytes() {
      java.lang.Object ref = field_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Dotted path to the offending field, for example "session.caller_number".
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @param value The field to set.
     * @return This builder for chaining.
     */
    public Builder setField(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      field_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Dotted path to the offending field, for example "session.caller_number".
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @return This builder for chaining.
     */
    public Builder clearField() {
      field_ = getDefaultInstance().getField();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Dotted path to the offending field, for example "session.caller_number".
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @param value The bytes for field to set.
     * @return This builder for chaining.
     */
    public Builder setFieldBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      field_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * Engineer-facing description of why it was rejected.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Engineer-facing description of why it was rejected.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Engineer-facing description of why it was rejected.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Engineer-facing description of why it was rejected.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Engineer-facing description of why it was rejected.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object userMessageKey_ = "";
    /**
     * <pre>
     * Localisation key for the message shown to the user beside the input.
     * </pre>
     *
     * <code>string user_message_key = 3 [json_name = "userMessageKey"];</code>
     * @return The userMessageKey.
     */
    public java.lang.String getUserMessageKey() {
      java.lang.Object ref = userMessageKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userMessageKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Localisation key for the message shown to the user beside the input.
     * </pre>
     *
     * <code>string user_message_key = 3 [json_name = "userMessageKey"];</code>
     * @return The bytes for userMessageKey.
     */
    public com.google.protobuf.ByteString
        getUserMessageKeyBytes() {
      java.lang.Object ref = userMessageKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userMessageKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Localisation key for the message shown to the user beside the input.
     * </pre>
     *
     * <code>string user_message_key = 3 [json_name = "userMessageKey"];</code>
     * @param value The userMessageKey to set.
     * @return This builder for chaining.
     */
    public Builder setUserMessageKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userMessageKey_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Localisation key for the message shown to the user beside the input.
     * </pre>
     *
     * <code>string user_message_key = 3 [json_name = "userMessageKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserMessageKey() {
      userMessageKey_ = getDefaultInstance().getUserMessageKey();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Localisation key for the message shown to the user beside the input.
     * </pre>
     *
     * <code>string user_message_key = 3 [json_name = "userMessageKey"];</code>
     * @param value The bytes for userMessageKey to set.
     * @return This builder for chaining.
     */
    public Builder setUserMessageKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userMessageKey_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:callscreen.common.v1.FieldViolation)
  }

  // @@protoc_insertion_point(class_scope:callscreen.common.v1.FieldViolation)
  private static final com.callscreen.contracts.callscreen.common.v1.FieldViolation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.callscreen.contracts.callscreen.common.v1.FieldViolation();
  }

  public static com.callscreen.contracts.callscreen.common.v1.FieldViolation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FieldViolation>
      PARSER = new com.google.protobuf.AbstractParser<FieldViolation>() {
    @java.lang.Override
    public FieldViolation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FieldViolation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FieldViolation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.callscreen.contracts.callscreen.common.v1.FieldViolation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

