// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/annotations.proto
// Protobuf Java Version: 4.29.3

package com.callscreen.contracts.callscreen.common.v1;

/**
 * <pre>
 * FieldClassification is attached to individual fields.
 * </pre>
 *
 * Protobuf type {@code callscreen.common.v1.FieldClassification}
 */
public final class FieldClassification extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:callscreen.common.v1.FieldClassification)
    FieldClassificationOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      FieldClassification.class.getName());
  }
  // Use FieldClassification.newBuilder() to construct.
  private FieldClassification(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FieldClassification() {
    sensitivity_ = 0;
    redaction_ = 0;
    retention_ = 0;
    purpose_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.callscreen.contracts.callscreen.common.v1.AnnotationsProto.internal_static_callscreen_common_v1_FieldClassification_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.callscreen.contracts.callscreen.common.v1.AnnotationsProto.internal_static_callscreen_common_v1_FieldClassification_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.callscreen.contracts.callscreen.common.v1.FieldClassification.class, com.callscreen.contracts.callscreen.common.v1.FieldClassification.Builder.class);
  }

  public static final int SENSITIVITY_FIELD_NUMBER = 1;
  private int sensitivity_ = 0;
  /**
   * <pre>
   * How sensitive the field's contents are. Required for any field that could
   * carry user data; the lint rules in CI flag unclassified candidates.
   * </pre>
   *
   * <code>.callscreen.common.v1.Sensitivity sensitivity = 1 [json_name = "sensitivity"];</code>
   * @return The enum numeric value on the wire for sensitivity.
   */
  @java.lang.Override public int getSensitivityValue() {
    return sensitivity_;
  }
  /**
   * <pre>
   * How sensitive the field's contents are. Required for any field that could
   * carry user data; the lint rules in CI flag unclassified candidates.
   * </pre>
   *
   * <code>.callscreen.common.v1.Sensitivity sensitivity = 1 [json_name = "sensitivity"];</code>
   * @return The sensitivity.
   */
  @java.lang.Override public com.callscreen.contracts.callscreen.common.v1.Sensitivity getSensitivity() {
    com.callscreen.contracts.callscreen.common.v1.Sensitivity result = com.callscreen.contracts.callscreen.common.v1.Sensitivity.forNumber(sensitivity_);
    return result == null ? com.callscreen.contracts.callscreen.common.v1.Sensitivity.UNRECOGNIZED : result;
  }

  public static final int REDACTION_FIELD_NUMBER = 2;
  private int redaction_ = 0;
  /**
   * <pre>
   * How the field is rendered when logged. Defaults are derived from
   * `sensitivity` when this is left unset.
   * </pre>
   *
   * <code>.callscreen.common.v1.RedactionStrategy redaction = 2 [json_name = "redaction"];</code>
   * @return The enum numeric value on the wire for redaction.
   */
  @java.lang.Override public int getRedactionValue() {
    return redaction_;
  }
  /**
   * <pre>
   * How the field is rendered when logged. Defaults are derived from
   * `sensitivity` when this is left unset.
   * </pre>
   *
   * <code>.callscreen.common.v1.RedactionStrategy redaction = 2 [json_name = "redaction"];</code>
   * @return The redaction.
   */
  @java.lang.Override public com.callscreen.contracts.callscreen.common.v1.RedactionStrategy getRedaction() {
    com.callscreen.contracts.callscreen.common.v1.RedactionStrategy result = com.callscreen.contracts.callscreen.common.v1.RedactionStrategy.forNumber(redaction_);
    return result == null ? com.callscreen.contracts.callscreen.common.v1.RedactionStrategy.UNRECOGNIZED : result;
  }

  public static final int RETENTION_FIELD_NUMBER = 3;
  private int retention_ = 0;
  /**
   * <pre>
   * How long the field's value may be retained.
   * </pre>
   *
   * <code>.callscreen.common.v1.Retention retention = 3 [json_name = "retention"];</code>
   * @return The enum numeric value on the wire for retention.
   */
  @java.lang.Override public int getRetentionValue() {
    return retention_;
  }
  /**
   * <pre>
   * How long the field's value may be retained.
   * </pre>
   *
   * <code>.callscreen.common.v1.Retention retention = 3 [json_name = "retention"];</code>
   * @return The retention.
   */
  @java.lang.Override public com.callscreen.contracts.callscreen.common.v1.Retention getRetention() {
    com.callscreen.contracts.callscreen.common.v1.Retention result = com.callscreen.contracts.callscreen.common.v1.Retention.forNumber(retention_);
    return result == null ? com.callscreen.contracts.callscreen.common.v1.Retention.UNRECOGNIZED : result;
  }

  public static final int RESIDENCY_BOUND_FIELD_NUMBER = 4;
  private boolean residencyBound_ = false;
  /**
   * <pre>
   * When true, the field must never leave its origin region. Enforced by the
   * egress policy in the platform HTTP and Kafka clients.
   * </pre>
   *
   * <code>bool residency_bound = 4 [json_name = "residencyBound"];</code>
   * @return The residencyBound.
   */
  @java.lang.Override
  public boolean getResidencyBound() {
    return residencyBound_;
  }

  public static final int PURPOSE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object purpose_ = "";
  /**
   * <pre>
   * Free-text justification recorded in the generated data map. Required for
   * SENSITIVE and SECRET fields so that the compliance review has context.
   * </pre>
   *
   * <code>string purpose = 5 [json_name = "purpose"];</code>
   * @return The purpose.
   */
  @java.lang.Override
  public java.lang.String getPurpose() {
    java.lang.Object ref = purpose_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      purpose_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Free-text justification recorded in the generated data map. Required for
   * SENSITIVE and SECRET fields so that the compliance review has context.
   * </pre>
   *
   * <code>string purpose = 5 [json_name = "purpose"];</code>
   * @return The bytes for purpose.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPurposeBytes() {
    java.lang.Object ref = purpose_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      purpose_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sensitivity_ != com.callscreen.contracts.callscreen.common.v1.Sensitivity.SENSITIVITY_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, sensitivity_);
    }
    if (redaction_ != com.callscreen.contracts.callscreen.common.v1.RedactionStrategy.REDACTION_STRATEGY_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, redaction_);
    }
    if (retention_ != com.callscreen.contracts.callscreen.common.v1.Retention.RETENTION_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, retention_);
    }
    if (residencyBound_ != false) {
      output.writeBool(4, residencyBound_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(purpose_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, purpose_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sensitivity_ != com.callscreen.contracts.callscreen.common.v1.Sensitivity.SENSITIVITY_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, sensitivity_);
    }
    if (redaction_ != com.callscreen.contracts.callscreen.common.v1.RedactionStrategy.REDACTION_STRATEGY_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, redaction_);
    }
    if (retention_ != com.callscreen.contracts.callscreen.common.v1.Retention.RETENTION_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, retention_);
    }
    if (residencyBound_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, residencyBound_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(purpose_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, purpose_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.callscreen.contracts.callscreen.common.v1.FieldClassification)) {
      return super.equals(obj);
    }
    com.callscreen.contracts.callscreen.common.v1.FieldClassification other = (com.callscreen.contracts.callscreen.common.v1.FieldClassification) obj;

    if (sensitivity_ != other.sensitivity_) return false;
    if (redaction_ != other.redaction_) return false;
    if (retention_ != other.retention_) return false;
    if (getResidencyBound()
        != other.getResidencyBound()) return false;
    if (!getPurpose()
        .equals(other.getPurpose())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENSITIVITY_FIELD_NUMBER;
    hash = (53 * hash) + sensitivity_;
    hash = (37 * hash) + REDACTION_FIELD_NUMBER;
    hash = (53 * hash) + redaction_;
    hash = (37 * hash) + RETENTION_FIELD_NUMBER;
    hash = (53 * hash) + retention_;
    hash = (37 * hash) + RESIDENCY_BOUND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getResidencyBound());
    hash = (37 * hash) + PURPOSE_FIELD_NUMBER;
    hash = (53 * hash) + getPurpose().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.callscreen.contracts.callscreen.common.v1.FieldClassification parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldClassification parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldClassification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldClassification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldClassification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldClassification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldClassification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldClassification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.callscreen.contracts.callscreen.common.v1.FieldClassification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.callscreen.contracts.callscreen.common.v1.FieldClassification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldClassification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.callscreen.contracts.callscreen.common.v1.FieldClassification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.callscreen.contracts.callscreen.common.v1.FieldClassification prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * FieldClassification is attached to individual fields.
   * </pre>
   *
   * Protobuf type {@code callscreen.common.v1.FieldClassification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:callscreen.common.v1.FieldClassification)
      com.callscreen.contracts.callscreen.common.v1.FieldClassificationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.callscreen.contracts.callscreen.common.v1.AnnotationsProto.internal_static_callscreen_common_v1_FieldClassification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.callscreen.contracts.callscreen.common.v1.AnnotationsProto.internal_static_callscreen_common_v1_FieldClassification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.callscreen.contracts.callscreen.common.v1.FieldClassification.class, com.callscreen.contracts.callscreen.common.v1.FieldClassification.Builder.class);
    }

    // Construct using com.callscreen.contracts.callscreen.common.v1.FieldClassification.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sensitivity_ = 0;
      redaction_ = 0;
      retention_ = 0;
      residencyBound_ = false;
      purpose_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.callscreen.contracts.callscreen.common.v1.AnnotationsProto.internal_static_callscreen_common_v1_FieldClassification_descriptor;
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.FieldClassification getDefaultInstanceForType() {
      return com.callscreen.contracts.callscreen.common.v1.FieldClassification.getDefaultInstance();
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.FieldClassification build() {
      com.callscreen.contracts.callscreen.common.v1.FieldClassification result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.FieldClassification buildPartial() {
      com.callscreen.contracts.callscreen.common.v1.FieldClassification result = new com.callscreen.contracts.callscreen.common.v1.FieldClassification(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.callscreen.contracts.callscreen.common.v1.FieldClassification result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sensitivity_ = sensitivity_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.redaction_ = redaction_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.retention_ = retention_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.residencyBound_ = residencyBound_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.purpose_ = purpose_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.callscreen.contracts.callscreen.common.v1.FieldClassification) {
        return mergeFrom((com.callscreen.contracts.callscreen.common.v1.FieldClassification)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.callscreen.contracts.callscreen.common.v1.FieldClassification other) {
      if (other == com.callscreen.contracts.callscreen.common.v1.FieldClassification.getDefaultInstance()) return this;
      if (other.sensitivity_ != 0) {
        setSensitivityValue(other.getSensitivityValue());
      }
      if (other.redaction_ != 0) {
        setRedactionValue(other.getRedactionValue());
      }
      if (other.retention_ != 0) {
        setRetentionValue(other.getRetentionValue());
      }
      if (other.getResidencyBound() != false) {
        setResidencyBound(other.getResidencyBound());
      }
      if (!other.getPurpose().isEmpty()) {
        purpose_ = other.purpose_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              sensitivity_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              redaction_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              retention_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              residencyBound_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              purpose_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int sensitivity_ = 0;
    /**
     * <pre>
     * How sensitive the field's contents are. Required for any field that could
     * carry user data; the lint rules in CI flag unclassified candidates.
     * </pre>
     *
     * <code>.callscreen.common.v1.Sensitivity sensitivity = 1 [json_name = "sensitivity"];</code>
     * @return The enum numeric value on the wire for sensitivity.
     */
    @java.lang.Override public int getSensitivityValue() {
      return sensitivity_;
    }
    /**
     * <pre>
     * How sensitive the field's contents are. Required for any field that could
     * carry user data; the lint rules in CI flag unclassified candidates.
     * </pre>
     *
     * <code>.callscreen.common.v1.Sensitivity sensitivity = 1 [json_name = "sensitivity"];</code>
     * @param value The enum numeric value on the wire for sensitivity to set.
     * @return This builder for chaining.
     */
    public Builder setSensitivityValue(int value) {
      sensitivity_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How sensitive the field's contents are. Required for any field that could
     * carry user data; the lint rules in CI flag unclassified candidates.
     * </pre>
     *
     * <code>.callscreen.common.v1.Sensitivity sensitivity = 1 [json_name = "sensitivity"];</code>
     * @return The sensitivity.
     */
    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.Sensitivity getSensitivity() {
      com.callscreen.contracts.callscreen.common.v1.Sensitivity result = com.callscreen.contracts.callscreen.common.v1.Sensitivity.forNumber(sensitivity_);
      return result == null ? com.callscreen.contracts.callscreen.common.v1.Sensitivity.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * How sensitive the field's contents are. Required for any field that could
     * carry user data; the lint rules in CI flag unclassified candidates.
     * </pre>
     *
     * <code>.callscreen.common.v1.Sensitivity sensitivity = 1 [json_name = "sensitivity"];</code>
     * @param value The sensitivity to set.
     * @return This builder for chaining.
     */
    public Builder setSensitivity(com.callscreen.contracts.callscreen.common.v1.Sensitivity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      sensitivity_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How sensitive the field's contents are. Required for any field that could
     * carry user data; the lint rules in CI flag unclassified candidates.
     * </pre>
     *
     * <code>.callscreen.common.v1.Sensitivity sensitivity = 1 [json_name = "sensitivity"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSensitivity() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sensitivity_ = 0;
      onChanged();
      return this;
    }

    private int redaction_ = 0;
    /**
     * <pre>
     * How the field is rendered when logged. Defaults are derived from
     * `sensitivity` when this is left unset.
     * </pre>
     *
     * <code>.callscreen.common.v1.RedactionStrategy redaction = 2 [json_name = "redaction"];</code>
     * @return The enum numeric value on the wire for redaction.
     */
    @java.lang.Override public int getRedactionValue() {
      return redaction_;
    }
    /**
     * <pre>
     * How the field is rendered when logged. Defaults are derived from
     * `sensitivity` when this is left unset.
     * </pre>
     *
     * <code>.callscreen.common.v1.RedactionStrategy redaction = 2 [json_name = "redaction"];</code>
     * @param value The enum numeric value on the wire for redaction to set.
     * @return This builder for chaining.
     */
    public Builder setRedactionValue(int value) {
      redaction_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How the field is rendered when logged. Defaults are derived from
     * `sensitivity` when this is left unset.
     * </pre>
     *
     * <code>.callscreen.common.v1.RedactionStrategy redaction = 2 [json_name = "redaction"];</code>
     * @return The redaction.
     */
    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.RedactionStrategy getRedaction() {
      com.callscreen.contracts.callscreen.common.v1.RedactionStrategy result = com.callscreen.contracts.callscreen.common.v1.RedactionStrategy.forNumber(redaction_);
      return result == null ? com.callscreen.contracts.callscreen.common.v1.RedactionStrategy.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * How the field is rendered when logged. Defaults are derived from
     * `sensitivity` when this is left unset.
     * </pre>
     *
     * <code>.callscreen.common.v1.RedactionStrategy redaction = 2 [json_name = "redaction"];</code>
     * @param value The redaction to set.
     * @return This builder for chaining.
     */
    public Builder setRedaction(com.callscreen.contracts.callscreen.common.v1.RedactionStrategy value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      redaction_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How the field is rendered when logged. Defaults are derived from
     * `sensitivity` when this is left unset.
     * </pre>
     *
     * <code>.callscreen.common.v1.RedactionStrategy redaction = 2 [json_name = "redaction"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRedaction() {
      bitField0_ = (bitField0_ & ~0x00000002);
      redaction_ = 0;
      onChanged();
      return this;
    }

    private int retention_ = 0;
    /**
     * <pre>
     * How long the field's value may be retained.
     * </pre>
     *
     * <code>.callscreen.common.v1.Retention retention = 3 [json_name = "retention"];</code>
     * @return The enum numeric value on the wire for retention.
     */
    @java.lang.Override public int getRetentionValue() {
      return retention_;
    }
    /**
     * <pre>
     * How long the field's value may be retained.
     * </pre>
     *
     * <code>.callscreen.common.v1.Retention retention = 3 [json_name = "retention"];</code>
     * @param value The enum numeric value on the wire for retention to set.
     * @return This builder for chaining.
     */
    public Builder setRetentionValue(int value) {
      retention_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How long the field's value may be retained.
     * </pre>
     *
     * <code>.callscreen.common.v1.Retention retention = 3 [json_name = "retention"];</code>
     * @return The retention.
     */
    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.Retention getRetention() {
      com.callscreen.contracts.callscreen.common.v1.Retention result = com.callscreen.contracts.callscreen.common.v1.Retention.forNumber(retention_);
      return result == null ? com.callscreen.contracts.callscreen.common.v1.Retention.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * How long the field's value may be retained.
     * </pre>
     *
     * <code>.callscreen.common.v1.Retention retention = 3 [json_name = "retention"];</code>
     * @param value The retention to set.
     * @return This builder for chaining.
     */
    public Builder setRetention(com.callscreen.contracts.callscreen.common.v1.Retention value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      retention_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How long the field's value may be retained.
     * </pre>
     *
     * <code>.callscreen.common.v1.Retention retention = 3 [json_name = "retention"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRetention() {
      bitField0_ = (bitField0_ & ~0x00000004);
      retention_ = 0;
      onChanged();
      return this;
    }

    private boolean residencyBound_ ;
    /**
     * <pre>
     * When true, the field must never leave its origin region. Enforced by the
     * egress policy in the platform HTTP and Kafka clients.
     * </pre>
     *
     * <code>bool residency_bound = 4 [json_name = "residencyBound"];</code>
     * @return The residencyBound.
     */
    @java.lang.Override
    public boolean getResidencyBound() {
      return residencyBound_;
    }
    /**
     * <pre>
     * When true, the field must never leave its origin region. Enforced by the
     * egress policy in the platform HTTP and Kafka clients.
     * </pre>
     *
     * <code>bool residency_bound = 4 [json_name = "residencyBound"];</code>
     * @param value The residencyBound to set.
     * @return This builder for chaining.
     */
    public Builder setResidencyBound(boolean value) {

      residencyBound_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When true, the field must never leave its origin region. Enforced by the
     * egress policy in the platform HTTP and Kafka clients.
     * </pre>
     *
     * <code>bool residency_bound = 4 [json_name = "residencyBound"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResidencyBound() {
      bitField0_ = (bitField0_ & ~0x00000008);
      residencyBound_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object purpose_ = "";
    /**
     * <pre>
     * Free-text justification recorded in the generated data map. Required for
     * SENSITIVE and SECRET fields so that the compliance review has context.
     * </pre>
     *
     * <code>string purpose = 5 [json_name = "purpose"];</code>
     * @return The purpose.
     */
    public java.lang.String getPurpose() {
      java.lang.Object ref = purpose_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        purpose_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Free-text justification recorded in the generated data map. Required for
     * SENSITIVE and SECRET fields so that the compliance review has context.
     * </pre>
     *
     * <code>string purpose = 5 [json_name = "purpose"];</code>
     * @return The bytes for purpose.
     */
    public com.google.protobuf.ByteString
        getPurposeBytes() {
      java.lang.Object ref = purpose_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        purpose_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Free-text justification recorded in the generated data map. Required for
     * SENSITIVE and SECRET fields so that the compliance review has context.
     * </pre>
     *
     * <code>string purpose = 5 [json_name = "purpose"];</code>
     * @param value The purpose to set.
     * @return This builder for chaining.
     */
    public Builder setPurpose(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      purpose_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Free-text justification recorded in the generated data map. Required for
     * SENSITIVE and SECRET fields so that the compliance review has context.
     * </pre>
     *
     * <code>string purpose = 5 [json_name = "purpose"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPurpose() {
      purpose_ = getDefaultInstance().getPurpose();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Free-text justification recorded in the generated data map. Required for
     * SENSITIVE and SECRET fields so that the compliance review has context.
     * </pre>
     *
     * <code>string purpose = 5 [json_name = "purpose"];</code>
     * @param value The bytes for purpose to set.
     * @return This builder for chaining.
     */
    public Builder setPurposeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      purpose_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:callscreen.common.v1.FieldClassification)
  }

  // @@protoc_insertion_point(class_scope:callscreen.common.v1.FieldClassification)
  private static final com.callscreen.contracts.callscreen.common.v1.FieldClassification DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.callscreen.contracts.callscreen.common.v1.FieldClassification();
  }

  public static com.callscreen.contracts.callscreen.common.v1.FieldClassification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FieldClassification>
      PARSER = new com.google.protobuf.AbstractParser<FieldClassification>() {
    @java.lang.Override
    public FieldClassification parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FieldClassification> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FieldClassification> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.callscreen.contracts.callscreen.common.v1.FieldClassification getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

