// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/annotations.proto
// Protobuf Java Version: 4.29.3

package com.callscreen.contracts.callscreen.common.v1;

public interface FieldClassificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:callscreen.common.v1.FieldClassification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * How sensitive the field's contents are. Required for any field that could
   * carry user data; the lint rules in CI flag unclassified candidates.
   * </pre>
   *
   * <code>.callscreen.common.v1.Sensitivity sensitivity = 1 [json_name = "sensitivity"];</code>
   * @return The enum numeric value on the wire for sensitivity.
   */
  int getSensitivityValue();
  /**
   * <pre>
   * How sensitive the field's contents are. Required for any field that could
   * carry user data; the lint rules in CI flag unclassified candidates.
   * </pre>
   *
   * <code>.callscreen.common.v1.Sensitivity sensitivity = 1 [json_name = "sensitivity"];</code>
   * @return The sensitivity.
   */
  com.callscreen.contracts.callscreen.common.v1.Sensitivity getSensitivity();

  /**
   * <pre>
   * How the field is rendered when logged. Defaults are derived from
   * `sensitivity` when this is left unset.
   * </pre>
   *
   * <code>.callscreen.common.v1.RedactionStrategy redaction = 2 [json_name = "redaction"];</code>
   * @return The enum numeric value on the wire for redaction.
   */
  int getRedactionValue();
  /**
   * <pre>
   * How the field is rendered when logged. Defaults are derived from
   * `sensitivity` when this is left unset.
   * </pre>
   *
   * <code>.callscreen.common.v1.RedactionStrategy redaction = 2 [json_name = "redaction"];</code>
   * @return The redaction.
   */
  com.callscreen.contracts.callscreen.common.v1.RedactionStrategy getRedaction();

  /**
   * <pre>
   * How long the field's value may be retained.
   * </pre>
   *
   * <code>.callscreen.common.v1.Retention retention = 3 [json_name = "retention"];</code>
   * @return The enum numeric value on the wire for retention.
   */
  int getRetentionValue();
  /**
   * <pre>
   * How long the field's value may be retained.
   * </pre>
   *
   * <code>.callscreen.common.v1.Retention retention = 3 [json_name = "retention"];</code>
   * @return The retention.
   */
  com.callscreen.contracts.callscreen.common.v1.Retention getRetention();

  /**
   * <pre>
   * When true, the field must never leave its origin region. Enforced by the
   * egress policy in the platform HTTP and Kafka clients.
   * </pre>
   *
   * <code>bool residency_bound = 4 [json_name = "residencyBound"];</code>
   * @return The residencyBound.
   */
  boolean getResidencyBound();

  /**
   * <pre>
   * Free-text justification recorded in the generated data map. Required for
   * SENSITIVE and SECRET fields so that the compliance review has context.
   * </pre>
   *
   * <code>string purpose = 5 [json_name = "purpose"];</code>
   * @return The purpose.
   */
  java.lang.String getPurpose();
  /**
   * <pre>
   * Free-text justification recorded in the generated data map. Required for
   * SENSITIVE and SECRET fields so that the compliance review has context.
   * </pre>
   *
   * <code>string purpose = 5 [json_name = "purpose"];</code>
   * @return The bytes for purpose.
   */
  com.google.protobuf.ByteString
      getPurposeBytes();
}
