// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/annotations.proto
// Protobuf Java Version: 4.29.3

package com.callscreen.contracts.callscreen.common.v1;

public interface MessageClassificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:callscreen.common.v1.MessageClassification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Baseline sensitivity for every field in the message.
   * </pre>
   *
   * <code>.callscreen.common.v1.Sensitivity default_sensitivity = 1 [json_name = "defaultSensitivity"];</code>
   * @return The enum numeric value on the wire for defaultSensitivity.
   */
  int getDefaultSensitivityValue();
  /**
   * <pre>
   * Baseline sensitivity for every field in the message.
   * </pre>
   *
   * <code>.callscreen.common.v1.Sensitivity default_sensitivity = 1 [json_name = "defaultSensitivity"];</code>
   * @return The defaultSensitivity.
   */
  com.callscreen.contracts.callscreen.common.v1.Sensitivity getDefaultSensitivity();

  /**
   * <pre>
   * Baseline retention for the message as a persisted record.
   * </pre>
   *
   * <code>.callscreen.common.v1.Retention default_retention = 2 [json_name = "defaultRetention"];</code>
   * @return The enum numeric value on the wire for defaultRetention.
   */
  int getDefaultRetentionValue();
  /**
   * <pre>
   * Baseline retention for the message as a persisted record.
   * </pre>
   *
   * <code>.callscreen.common.v1.Retention default_retention = 2 [json_name = "defaultRetention"];</code>
   * @return The defaultRetention.
   */
  com.callscreen.contracts.callscreen.common.v1.Retention getDefaultRetention();

  /**
   * <pre>
   * Name of the team accountable for this data under the compliance programme.
   * Mirrors a team handle in .github/CODEOWNERS.
   * </pre>
   *
   * <code>string data_owner = 3 [json_name = "dataOwner"];</code>
   * @return The dataOwner.
   */
  java.lang.String getDataOwner();
  /**
   * <pre>
   * Name of the team accountable for this data under the compliance programme.
   * Mirrors a team handle in .github/CODEOWNERS.
   * </pre>
   *
   * <code>string data_owner = 3 [json_name = "dataOwner"];</code>
   * @return The bytes for dataOwner.
   */
  com.google.protobuf.ByteString
      getDataOwnerBytes();
}
