// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/types.proto
// Protobuf Java Version: 4.29.3

package com.callscreen.contracts.callscreen.common.v1;

/**
 * <pre>
 * Money represents an exact monetary amount.
 *
 * Never a float. Floating point cannot represent decimal currency exactly, and
 * rounding drift in a billing system is both a correctness bug and an audit
 * finding. Stored as minor units (paise for INR) in an integer.
 * </pre>
 *
 * Protobuf type {@code callscreen.common.v1.Money}
 */
public final class Money extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:callscreen.common.v1.Money)
    MoneyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Money.class.getName());
  }
  // Use Money.newBuilder() to construct.
  private Money(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Money() {
    currencyCode_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_Money_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_Money_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.callscreen.contracts.callscreen.common.v1.Money.class, com.callscreen.contracts.callscreen.common.v1.Money.Builder.class);
  }

  public static final int CURRENCY_CODE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object currencyCode_ = "";
  /**
   * <pre>
   * ISO 4217 currency code, uppercase. For example "INR".
   * </pre>
   *
   * <code>string currency_code = 1 [json_name = "currencyCode"];</code>
   * @return The currencyCode.
   */
  @java.lang.Override
  public java.lang.String getCurrencyCode() {
    java.lang.Object ref = currencyCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currencyCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ISO 4217 currency code, uppercase. For example "INR".
   * </pre>
   *
   * <code>string currency_code = 1 [json_name = "currencyCode"];</code>
   * @return The bytes for currencyCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrencyCodeBytes() {
    java.lang.Object ref = currencyCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currencyCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_MINOR_FIELD_NUMBER = 2;
  private long amountMinor_ = 0L;
  /**
   * <pre>
   * Amount in the currency's minor unit. 12550 with currency_code "INR" is
   * ₹125.50. Negative values represent credits and refunds.
   * </pre>
   *
   * <code>int64 amount_minor = 2 [json_name = "amountMinor"];</code>
   * @return The amountMinor.
   */
  @java.lang.Override
  public long getAmountMinor() {
    return amountMinor_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(currencyCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, currencyCode_);
    }
    if (amountMinor_ != 0L) {
      output.writeInt64(2, amountMinor_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(currencyCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, currencyCode_);
    }
    if (amountMinor_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, amountMinor_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.callscreen.contracts.callscreen.common.v1.Money)) {
      return super.equals(obj);
    }
    com.callscreen.contracts.callscreen.common.v1.Money other = (com.callscreen.contracts.callscreen.common.v1.Money) obj;

    if (!getCurrencyCode()
        .equals(other.getCurrencyCode())) return false;
    if (getAmountMinor()
        != other.getAmountMinor()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENCY_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCurrencyCode().hashCode();
    hash = (37 * hash) + AMOUNT_MINOR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmountMinor());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.callscreen.contracts.callscreen.common.v1.Money parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Money parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Money parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Money parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Money parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Money parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Money parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Money parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.callscreen.contracts.callscreen.common.v1.Money parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.callscreen.contracts.callscreen.common.v1.Money parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Money parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.callscreen.contracts.callscreen.common.v1.Money parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.callscreen.contracts.callscreen.common.v1.Money prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Money represents an exact monetary amount.
   *
   * Never a float. Floating point cannot represent decimal currency exactly, and
   * rounding drift in a billing system is both a correctness bug and an audit
   * finding. Stored as minor units (paise for INR) in an integer.
   * </pre>
   *
   * Protobuf type {@code callscreen.common.v1.Money}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:callscreen.common.v1.Money)
      com.callscreen.contracts.callscreen.common.v1.MoneyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_Money_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_Money_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.callscreen.contracts.callscreen.common.v1.Money.class, com.callscreen.contracts.callscreen.common.v1.Money.Builder.class);
    }

    // Construct using com.callscreen.contracts.callscreen.common.v1.Money.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      currencyCode_ = "";
      amountMinor_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_Money_descriptor;
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.Money getDefaultInstanceForType() {
      return com.callscreen.contracts.callscreen.common.v1.Money.getDefaultInstance();
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.Money build() {
      com.callscreen.contracts.callscreen.common.v1.Money result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.Money buildPartial() {
      com.callscreen.contracts.callscreen.common.v1.Money result = new com.callscreen.contracts.callscreen.common.v1.Money(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.callscreen.contracts.callscreen.common.v1.Money result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.currencyCode_ = currencyCode_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.amountMinor_ = amountMinor_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.callscreen.contracts.callscreen.common.v1.Money) {
        return mergeFrom((com.callscreen.contracts.callscreen.common.v1.Money)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.callscreen.contracts.callscreen.common.v1.Money other) {
      if (other == com.callscreen.contracts.callscreen.common.v1.Money.getDefaultInstance()) return this;
      if (!other.getCurrencyCode().isEmpty()) {
        currencyCode_ = other.currencyCode_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getAmountMinor() != 0L) {
        setAmountMinor(other.getAmountMinor());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              currencyCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              amountMinor_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object currencyCode_ = "";
    /**
     * <pre>
     * ISO 4217 currency code, uppercase. For example "INR".
     * </pre>
     *
     * <code>string currency_code = 1 [json_name = "currencyCode"];</code>
     * @return The currencyCode.
     */
    public java.lang.String getCurrencyCode() {
      java.lang.Object ref = currencyCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currencyCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ISO 4217 currency code, uppercase. For example "INR".
     * </pre>
     *
     * <code>string currency_code = 1 [json_name = "currencyCode"];</code>
     * @return The bytes for currencyCode.
     */
    public com.google.protobuf.ByteString
        getCurrencyCodeBytes() {
      java.lang.Object ref = currencyCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ISO 4217 currency code, uppercase. For example "INR".
     * </pre>
     *
     * <code>string currency_code = 1 [json_name = "currencyCode"];</code>
     * @param value The currencyCode to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      currencyCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ISO 4217 currency code, uppercase. For example "INR".
     * </pre>
     *
     * <code>string currency_code = 1 [json_name = "currencyCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrencyCode() {
      currencyCode_ = getDefaultInstance().getCurrencyCode();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ISO 4217 currency code, uppercase. For example "INR".
     * </pre>
     *
     * <code>string currency_code = 1 [json_name = "currencyCode"];</code>
     * @param value The bytes for currencyCode to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      currencyCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long amountMinor_ ;
    /**
     * <pre>
     * Amount in the currency's minor unit. 12550 with currency_code "INR" is
     * ₹125.50. Negative values represent credits and refunds.
     * </pre>
     *
     * <code>int64 amount_minor = 2 [json_name = "amountMinor"];</code>
     * @return The amountMinor.
     */
    @java.lang.Override
    public long getAmountMinor() {
      return amountMinor_;
    }
    /**
     * <pre>
     * Amount in the currency's minor unit. 12550 with currency_code "INR" is
     * ₹125.50. Negative values represent credits and refunds.
     * </pre>
     *
     * <code>int64 amount_minor = 2 [json_name = "amountMinor"];</code>
     * @param value The amountMinor to set.
     * @return This builder for chaining.
     */
    public Builder setAmountMinor(long value) {

      amountMinor_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Amount in the currency's minor unit. 12550 with currency_code "INR" is
     * ₹125.50. Negative values represent credits and refunds.
     * </pre>
     *
     * <code>int64 amount_minor = 2 [json_name = "amountMinor"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAmountMinor() {
      bitField0_ = (bitField0_ & ~0x00000002);
      amountMinor_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:callscreen.common.v1.Money)
  }

  // @@protoc_insertion_point(class_scope:callscreen.common.v1.Money)
  private static final com.callscreen.contracts.callscreen.common.v1.Money DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.callscreen.contracts.callscreen.common.v1.Money();
  }

  public static com.callscreen.contracts.callscreen.common.v1.Money getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Money>
      PARSER = new com.google.protobuf.AbstractParser<Money>() {
    @java.lang.Override
    public Money parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Money> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Money> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.callscreen.contracts.callscreen.common.v1.Money getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

