// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/types.proto
// Protobuf Java Version: 4.29.3

package com.callscreen.contracts.callscreen.common.v1;

public interface PageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:callscreen.common.v1.PageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Cursor for the next page. Empty means the caller has reached the end.
   * </pre>
   *
   * <code>string next_page_token = 1 [json_name = "nextPageToken"];</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * Cursor for the next page. Empty means the caller has reached the end.
   * </pre>
   *
   * <code>string next_page_token = 1 [json_name = "nextPageToken"];</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();

  /**
   * <pre>
   * Total matching items, when the owning service can compute it cheaply.
   * Negative means "not computed" — deliberately distinguishable from zero,
   * because "no results" and "we did not count" are different facts.
   * </pre>
   *
   * <code>int64 total_size = 2 [json_name = "totalSize"];</code>
   * @return The totalSize.
   */
  long getTotalSize();
}
