// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/types.proto
// Protobuf Java Version: 4.29.3

package com.callscreen.contracts.callscreen.common.v1;

/**
 * <pre>
 * RequestMetadata is attached to mutating requests to make them safely
 * retryable across an unreliable mobile network.
 * </pre>
 *
 * Protobuf type {@code callscreen.common.v1.RequestMetadata}
 */
public final class RequestMetadata extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:callscreen.common.v1.RequestMetadata)
    RequestMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      RequestMetadata.class.getName());
  }
  // Use RequestMetadata.newBuilder() to construct.
  private RequestMetadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RequestMetadata() {
    idempotencyKey_ = "";
    traceparent_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_RequestMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_RequestMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.callscreen.contracts.callscreen.common.v1.RequestMetadata.class, com.callscreen.contracts.callscreen.common.v1.RequestMetadata.Builder.class);
  }

  private int bitField0_;
  public static final int IDEMPOTENCY_KEY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object idempotencyKey_ = "";
  /**
   * <pre>
   * Client-generated idempotency key. The server guarantees that two requests
   * bearing the same key and the same payload produce one effect. Reusing a key
   * with a different payload returns ERROR_CODE_IDEMPOTENCY_CONFLICT.
   *
   * This is mandatory on mutations rather than optional: on a mobile network a
   * response is lost often enough that a client which cannot safely retry will
   * either lose writes or duplicate them.
   * </pre>
   *
   * <code>string idempotency_key = 1 [json_name = "idempotencyKey"];</code>
   * @return The idempotencyKey.
   */
  @java.lang.Override
  public java.lang.String getIdempotencyKey() {
    java.lang.Object ref = idempotencyKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idempotencyKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Client-generated idempotency key. The server guarantees that two requests
   * bearing the same key and the same payload produce one effect. Reusing a key
   * with a different payload returns ERROR_CODE_IDEMPOTENCY_CONFLICT.
   *
   * This is mandatory on mutations rather than optional: on a mobile network a
   * response is lost often enough that a client which cannot safely retry will
   * either lose writes or duplicate them.
   * </pre>
   *
   * <code>string idempotency_key = 1 [json_name = "idempotencyKey"];</code>
   * @return The bytes for idempotencyKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdempotencyKeyBytes() {
    java.lang.Object ref = idempotencyKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idempotencyKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_SENT_AT_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp clientSentAt_;
  /**
   * <pre>
   * Client-side timestamp of request creation. Used to measure true end-to-end
   * latency including network time, which server-side timing cannot see. Never
   * trusted for ordering or authorisation — device clocks are not reliable.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp client_sent_at = 2 [json_name = "clientSentAt"];</code>
   * @return Whether the clientSentAt field is set.
   */
  @java.lang.Override
  public boolean hasClientSentAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Client-side timestamp of request creation. Used to measure true end-to-end
   * latency including network time, which server-side timing cannot see. Never
   * trusted for ordering or authorisation — device clocks are not reliable.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp client_sent_at = 2 [json_name = "clientSentAt"];</code>
   * @return The clientSentAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getClientSentAt() {
    return clientSentAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : clientSentAt_;
  }
  /**
   * <pre>
   * Client-side timestamp of request creation. Used to measure true end-to-end
   * latency including network time, which server-side timing cannot see. Never
   * trusted for ordering or authorisation — device clocks are not reliable.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp client_sent_at = 2 [json_name = "clientSentAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getClientSentAtOrBuilder() {
    return clientSentAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : clientSentAt_;
  }

  public static final int TRACEPARENT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object traceparent_ = "";
  /**
   * <pre>
   * W3C traceparent header value, propagating an existing distributed trace.
   * </pre>
   *
   * <code>string traceparent = 3 [json_name = "traceparent"];</code>
   * @return The traceparent.
   */
  @java.lang.Override
  public java.lang.String getTraceparent() {
    java.lang.Object ref = traceparent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceparent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * W3C traceparent header value, propagating an existing distributed trace.
   * </pre>
   *
   * <code>string traceparent = 3 [json_name = "traceparent"];</code>
   * @return The bytes for traceparent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTraceparentBytes() {
    java.lang.Object ref = traceparent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceparent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(idempotencyKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, idempotencyKey_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getClientSentAt());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(traceparent_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, traceparent_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(idempotencyKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, idempotencyKey_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getClientSentAt());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(traceparent_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, traceparent_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.callscreen.contracts.callscreen.common.v1.RequestMetadata)) {
      return super.equals(obj);
    }
    com.callscreen.contracts.callscreen.common.v1.RequestMetadata other = (com.callscreen.contracts.callscreen.common.v1.RequestMetadata) obj;

    if (!getIdempotencyKey()
        .equals(other.getIdempotencyKey())) return false;
    if (hasClientSentAt() != other.hasClientSentAt()) return false;
    if (hasClientSentAt()) {
      if (!getClientSentAt()
          .equals(other.getClientSentAt())) return false;
    }
    if (!getTraceparent()
        .equals(other.getTraceparent())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDEMPOTENCY_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getIdempotencyKey().hashCode();
    if (hasClientSentAt()) {
      hash = (37 * hash) + CLIENT_SENT_AT_FIELD_NUMBER;
      hash = (53 * hash) + getClientSentAt().hashCode();
    }
    hash = (37 * hash) + TRACEPARENT_FIELD_NUMBER;
    hash = (53 * hash) + getTraceparent().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.callscreen.contracts.callscreen.common.v1.RequestMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.RequestMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.RequestMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.RequestMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.RequestMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.callscreen.contracts.callscreen.common.v1.RequestMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.RequestMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.callscreen.contracts.callscreen.common.v1.RequestMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.callscreen.contracts.callscreen.common.v1.RequestMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.callscreen.contracts.callscreen.common.v1.RequestMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.callscreen.contracts.callscreen.common.v1.RequestMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.callscreen.contracts.callscreen.common.v1.RequestMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.callscreen.contracts.callscreen.common.v1.RequestMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * RequestMetadata is attached to mutating requests to make them safely
   * retryable across an unreliable mobile network.
   * </pre>
   *
   * Protobuf type {@code callscreen.common.v1.RequestMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:callscreen.common.v1.RequestMetadata)
      com.callscreen.contracts.callscreen.common.v1.RequestMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_RequestMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_RequestMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.callscreen.contracts.callscreen.common.v1.RequestMetadata.class, com.callscreen.contracts.callscreen.common.v1.RequestMetadata.Builder.class);
    }

    // Construct using com.callscreen.contracts.callscreen.common.v1.RequestMetadata.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getClientSentAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      idempotencyKey_ = "";
      clientSentAt_ = null;
      if (clientSentAtBuilder_ != null) {
        clientSentAtBuilder_.dispose();
        clientSentAtBuilder_ = null;
      }
      traceparent_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.callscreen.contracts.callscreen.common.v1.TypesProto.internal_static_callscreen_common_v1_RequestMetadata_descriptor;
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.RequestMetadata getDefaultInstanceForType() {
      return com.callscreen.contracts.callscreen.common.v1.RequestMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.RequestMetadata build() {
      com.callscreen.contracts.callscreen.common.v1.RequestMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.callscreen.contracts.callscreen.common.v1.RequestMetadata buildPartial() {
      com.callscreen.contracts.callscreen.common.v1.RequestMetadata result = new com.callscreen.contracts.callscreen.common.v1.RequestMetadata(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.callscreen.contracts.callscreen.common.v1.RequestMetadata result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.idempotencyKey_ = idempotencyKey_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.clientSentAt_ = clientSentAtBuilder_ == null
            ? clientSentAt_
            : clientSentAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.traceparent_ = traceparent_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.callscreen.contracts.callscreen.common.v1.RequestMetadata) {
        return mergeFrom((com.callscreen.contracts.callscreen.common.v1.RequestMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.callscreen.contracts.callscreen.common.v1.RequestMetadata other) {
      if (other == com.callscreen.contracts.callscreen.common.v1.RequestMetadata.getDefaultInstance()) return this;
      if (!other.getIdempotencyKey().isEmpty()) {
        idempotencyKey_ = other.idempotencyKey_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasClientSentAt()) {
        mergeClientSentAt(other.getClientSentAt());
      }
      if (!other.getTraceparent().isEmpty()) {
        traceparent_ = other.traceparent_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              idempotencyKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getClientSentAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              traceparent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object idempotencyKey_ = "";
    /**
     * <pre>
     * Client-generated idempotency key. The server guarantees that two requests
     * bearing the same key and the same payload produce one effect. Reusing a key
     * with a different payload returns ERROR_CODE_IDEMPOTENCY_CONFLICT.
     *
     * This is mandatory on mutations rather than optional: on a mobile network a
     * response is lost often enough that a client which cannot safely retry will
     * either lose writes or duplicate them.
     * </pre>
     *
     * <code>string idempotency_key = 1 [json_name = "idempotencyKey"];</code>
     * @return The idempotencyKey.
     */
    public java.lang.String getIdempotencyKey() {
      java.lang.Object ref = idempotencyKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idempotencyKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Client-generated idempotency key. The server guarantees that two requests
     * bearing the same key and the same payload produce one effect. Reusing a key
     * with a different payload returns ERROR_CODE_IDEMPOTENCY_CONFLICT.
     *
     * This is mandatory on mutations rather than optional: on a mobile network a
     * response is lost often enough that a client which cannot safely retry will
     * either lose writes or duplicate them.
     * </pre>
     *
     * <code>string idempotency_key = 1 [json_name = "idempotencyKey"];</code>
     * @return The bytes for idempotencyKey.
     */
    public com.google.protobuf.ByteString
        getIdempotencyKeyBytes() {
      java.lang.Object ref = idempotencyKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idempotencyKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Client-generated idempotency key. The server guarantees that two requests
     * bearing the same key and the same payload produce one effect. Reusing a key
     * with a different payload returns ERROR_CODE_IDEMPOTENCY_CONFLICT.
     *
     * This is mandatory on mutations rather than optional: on a mobile network a
     * response is lost often enough that a client which cannot safely retry will
     * either lose writes or duplicate them.
     * </pre>
     *
     * <code>string idempotency_key = 1 [json_name = "idempotencyKey"];</code>
     * @param value The idempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdempotencyKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      idempotencyKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Client-generated idempotency key. The server guarantees that two requests
     * bearing the same key and the same payload produce one effect. Reusing a key
     * with a different payload returns ERROR_CODE_IDEMPOTENCY_CONFLICT.
     *
     * This is mandatory on mutations rather than optional: on a mobile network a
     * response is lost often enough that a client which cannot safely retry will
     * either lose writes or duplicate them.
     * </pre>
     *
     * <code>string idempotency_key = 1 [json_name = "idempotencyKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIdempotencyKey() {
      idempotencyKey_ = getDefaultInstance().getIdempotencyKey();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Client-generated idempotency key. The server guarantees that two requests
     * bearing the same key and the same payload produce one effect. Reusing a key
     * with a different payload returns ERROR_CODE_IDEMPOTENCY_CONFLICT.
     *
     * This is mandatory on mutations rather than optional: on a mobile network a
     * response is lost often enough that a client which cannot safely retry will
     * either lose writes or duplicate them.
     * </pre>
     *
     * <code>string idempotency_key = 1 [json_name = "idempotencyKey"];</code>
     * @param value The bytes for idempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdempotencyKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      idempotencyKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp clientSentAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> clientSentAtBuilder_;
    /**
     * <pre>
     * Client-side timestamp of request creation. Used to measure true end-to-end
     * latency including network time, which server-side timing cannot see. Never
     * trusted for ordering or authorisation — device clocks are not reliable.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp client_sent_at = 2 [json_name = "clientSentAt"];</code>
     * @return Whether the clientSentAt field is set.
     */
    public boolean hasClientSentAt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Client-side timestamp of request creation. Used to measure true end-to-end
     * latency including network time, which server-side timing cannot see. Never
     * trusted for ordering or authorisation — device clocks are not reliable.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp client_sent_at = 2 [json_name = "clientSentAt"];</code>
     * @return The clientSentAt.
     */
    public com.google.protobuf.Timestamp getClientSentAt() {
      if (clientSentAtBuilder_ == null) {
        return clientSentAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : clientSentAt_;
      } else {
        return clientSentAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Client-side timestamp of request creation. Used to measure true end-to-end
     * latency including network time, which server-side timing cannot see. Never
     * trusted for ordering or authorisation — device clocks are not reliable.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp client_sent_at = 2 [json_name = "clientSentAt"];</code>
     */
    public Builder setClientSentAt(com.google.protobuf.Timestamp value) {
      if (clientSentAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clientSentAt_ = value;
      } else {
        clientSentAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Client-side timestamp of request creation. Used to measure true end-to-end
     * latency including network time, which server-side timing cannot see. Never
     * trusted for ordering or authorisation — device clocks are not reliable.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp client_sent_at = 2 [json_name = "clientSentAt"];</code>
     */
    public Builder setClientSentAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (clientSentAtBuilder_ == null) {
        clientSentAt_ = builderForValue.build();
      } else {
        clientSentAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Client-side timestamp of request creation. Used to measure true end-to-end
     * latency including network time, which server-side timing cannot see. Never
     * trusted for ordering or authorisation — device clocks are not reliable.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp client_sent_at = 2 [json_name = "clientSentAt"];</code>
     */
    public Builder mergeClientSentAt(com.google.protobuf.Timestamp value) {
      if (clientSentAtBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          clientSentAt_ != null &&
          clientSentAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getClientSentAtBuilder().mergeFrom(value);
        } else {
          clientSentAt_ = value;
        }
      } else {
        clientSentAtBuilder_.mergeFrom(value);
      }
      if (clientSentAt_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Client-side timestamp of request creation. Used to measure true end-to-end
     * latency including network time, which server-side timing cannot see. Never
     * trusted for ordering or authorisation — device clocks are not reliable.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp client_sent_at = 2 [json_name = "clientSentAt"];</code>
     */
    public Builder clearClientSentAt() {
      bitField0_ = (bitField0_ & ~0x00000002);
      clientSentAt_ = null;
      if (clientSentAtBuilder_ != null) {
        clientSentAtBuilder_.dispose();
        clientSentAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Client-side timestamp of request creation. Used to measure true end-to-end
     * latency including network time, which server-side timing cannot see. Never
     * trusted for ordering or authorisation — device clocks are not reliable.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp client_sent_at = 2 [json_name = "clientSentAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getClientSentAtBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getClientSentAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Client-side timestamp of request creation. Used to measure true end-to-end
     * latency including network time, which server-side timing cannot see. Never
     * trusted for ordering or authorisation — device clocks are not reliable.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp client_sent_at = 2 [json_name = "clientSentAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getClientSentAtOrBuilder() {
      if (clientSentAtBuilder_ != null) {
        return clientSentAtBuilder_.getMessageOrBuilder();
      } else {
        return clientSentAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : clientSentAt_;
      }
    }
    /**
     * <pre>
     * Client-side timestamp of request creation. Used to measure true end-to-end
     * latency including network time, which server-side timing cannot see. Never
     * trusted for ordering or authorisation — device clocks are not reliable.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp client_sent_at = 2 [json_name = "clientSentAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getClientSentAtFieldBuilder() {
      if (clientSentAtBuilder_ == null) {
        clientSentAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getClientSentAt(),
                getParentForChildren(),
                isClean());
        clientSentAt_ = null;
      }
      return clientSentAtBuilder_;
    }

    private java.lang.Object traceparent_ = "";
    /**
     * <pre>
     * W3C traceparent header value, propagating an existing distributed trace.
     * </pre>
     *
     * <code>string traceparent = 3 [json_name = "traceparent"];</code>
     * @return The traceparent.
     */
    public java.lang.String getTraceparent() {
      java.lang.Object ref = traceparent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceparent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * W3C traceparent header value, propagating an existing distributed trace.
     * </pre>
     *
     * <code>string traceparent = 3 [json_name = "traceparent"];</code>
     * @return The bytes for traceparent.
     */
    public com.google.protobuf.ByteString
        getTraceparentBytes() {
      java.lang.Object ref = traceparent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceparent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * W3C traceparent header value, propagating an existing distributed trace.
     * </pre>
     *
     * <code>string traceparent = 3 [json_name = "traceparent"];</code>
     * @param value The traceparent to set.
     * @return This builder for chaining.
     */
    public Builder setTraceparent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      traceparent_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * W3C traceparent header value, propagating an existing distributed trace.
     * </pre>
     *
     * <code>string traceparent = 3 [json_name = "traceparent"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceparent() {
      traceparent_ = getDefaultInstance().getTraceparent();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * W3C traceparent header value, propagating an existing distributed trace.
     * </pre>
     *
     * <code>string traceparent = 3 [json_name = "traceparent"];</code>
     * @param value The bytes for traceparent to set.
     * @return This builder for chaining.
     */
    public Builder setTraceparentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      traceparent_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:callscreen.common.v1.RequestMetadata)
  }

  // @@protoc_insertion_point(class_scope:callscreen.common.v1.RequestMetadata)
  private static final com.callscreen.contracts.callscreen.common.v1.RequestMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.callscreen.contracts.callscreen.common.v1.RequestMetadata();
  }

  public static com.callscreen.contracts.callscreen.common.v1.RequestMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestMetadata>
      PARSER = new com.google.protobuf.AbstractParser<RequestMetadata>() {
    @java.lang.Override
    public RequestMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RequestMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.callscreen.contracts.callscreen.common.v1.RequestMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

