// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/types.proto
// Protobuf Java Version: 4.29.3

package com.callscreen.contracts.callscreen.common.v1;

public interface ResourceIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:callscreen.common.v1.ResourceId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Short lowercase noun naming what this identifies, for example "user",
   * "call_session", "subscription". Matches the owning service's domain.
   * </pre>
   *
   * <code>string type = 1 [json_name = "type"];</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * Short lowercase noun naming what this identifies, for example "user",
   * "call_session", "subscription". Matches the owning service's domain.
   * </pre>
   *
   * <code>string type = 1 [json_name = "type"];</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * The opaque value. Generation strategy is an implementation detail of the
   * owning service; consumers must treat it as an unparseable string.
   * </pre>
   *
   * <code>string value = 2 [json_name = "value"];</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <pre>
   * The opaque value. Generation strategy is an implementation detail of the
   * owning service; consumers must treat it as an unparseable string.
   * </pre>
   *
   * <code>string value = 2 [json_name = "value"];</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
