// =============================================================================
// :contracts — generated protobuf bindings for the Android client.
//
// Included into the Android build from outside the android/ tree (see
// android/settings.gradle.kts) so that the client consumes exactly the same
// generated bindings as the Go and Python tiers, from one source of truth.
// Duplicating them under android/ would let the client contract drift from the
// server contract silently, which is the single failure mode that contract-first
// development exists to prevent.
//
// Everything under src/ is GENERATED by `task contracts:generate`. Hand edits
// are reverted by the next generation and fail the CI drift gate.
//
// This is a plain JVM module rather than an Android library: protobuf message
// classes have no Android dependency, and keeping them off the Android toolchain
// means they compile faster and can be unit-tested on a bare JVM.
// =============================================================================

plugins {
    id("callscreen.jvm.library")
}

dependencies {
    // `api` rather than `implementation`: consumers of this module handle the
    // generated message types directly, so those types must appear on their
    // compile classpath. With `implementation` every consumer would fail to
    // compile against its own dependency's public API.
    api(libs.protobuf.java)
    api(libs.protobuf.kotlin)
}

// Generated sources are exempt from the static-analysis policy. Linting code we
// did not write produces findings nobody can act on, and suppressing them
// individually would mean editing generated files — which the drift gate
// forbids. The .proto source is linted instead, by `buf lint`, which is where
// the defect would actually originate.
tasks.named("ktlintMainSourceSetCheck") { enabled = false }
tasks.named("ktlintKotlinScriptCheck") { enabled = false }
tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach { enabled = false }
