package toolruntime

import (
	"fmt"
	"sort"
	"time"
)

// ToolIntent is what the conversation engine emits.
//
// IT NAMES CAPABILITIES, NOT TOOLS. That is the load-bearing decision of this
// module and the reason it is provider agnostic; see the package documentation.
//
// It is also a plain struct with no methods that reach anywhere. The
// conversation engine does not import this package to build one — it builds a
// value. That keeps the dependency arrow pointing one way and means a scheduled
// job, an operator console or a future multi-agent planner can produce intents
// without going near a dialogue.
type ToolIntent struct {
	// ID identifies the intent. Generated by the caller so the caller can log
	// it before the runtime has seen it.
	ID IntentID

	// Correlation ties everything from one conversation turn together.
	Correlation CorrelationID

	// Session identifies the conversation, for audit only. Never used for
	// routing: routing on a session identifier is how a runtime accidentally
	// acquires session affinity and stops being horizontally scalable.
	Session SessionID

	// Actor is on whose behalf this runs.
	Actor ActorID

	// Requests are what is wanted. One for a single tool call, several for a
	// composite.
	Requests []CapabilityRequest

	// Grant is what the actor holds. Supplied by the caller rather than
	// fetched: fetching would put an availability dependency on Identity in
	// the middle of a conversation.
	Grant Grant

	// Deadline bounds the whole intent. Zero takes the runtime default.
	Deadline time.Time

	// Budget bounds the whole intent. Zero fields take the runtime default.
	// Tightening only — an intent cannot raise a runtime ceiling.
	Budget Budget

	// Metadata carries caller annotations for audit. Never used for routing,
	// for the same reason Contract.Tags is not: a field that affects behaviour
	// without a type is an untyped configuration channel.
	Metadata map[string]string
}

// CapabilityRequest is one thing the caller wants done.
type CapabilityRequest struct {
	// Ref names this request within the intent, so other requests can depend
	// on it and bind its outputs. Required when the intent has more than one
	// request; a dependency graph with anonymous nodes cannot be expressed.
	Ref string

	// Capability is what is needed.
	Capability CapabilityID

	// Version constrains which versions may serve it.
	Version VersionConstraint

	// Args are the statically-known arguments. Arguments produced by an
	// earlier step arrive through Bindings instead.
	Args Arguments

	// DependsOn lists refs that must complete first. The planner derives
	// sequencing from this rather than from declaration order, because
	// declaration order is a formatting decision and dependencies are a
	// correctness one.
	DependsOn []string

	// Bindings map earlier steps' outputs into this step's arguments.
	Bindings []Binding

	// Condition, when set, makes this step conditional on an earlier result.
	Condition *Condition

	// Fallback builds a fallback chain from every discovered candidate rather
	// than pinning the single best. Costs nothing when the first candidate
	// works.
	Fallback bool

	// Optional means a failure here does not fail the plan. Used for
	// enrichment: failing to look up a caller's history should not stop the
	// call being answered.
	Optional bool

	// PreferTool nudges selection without requiring it.
	PreferTool ToolID
}

// Binding wires one step's output into another step's argument.
//
// Data, not a closure. A closure would be unserialisable, unreviewable and
// impossible to compare between two plans — and comparing two plans is exactly
// what an operator does when asking why today's execution differed from
// yesterday's.
type Binding struct {
	// FromRef is the producing request's Ref.
	FromRef string
	// FromField is the output field to read.
	FromField string
	// ToArg is the argument to populate.
	ToArg string
	// Required fails the step when the source field is absent. When false, an
	// absent source simply leaves the argument unset and the contract's own
	// required/default rules then apply.
	Required bool
}

func (b Binding) validate(where string) []string {
	var problems []string
	if b.FromRef == "" {
		problems = append(problems, where+": binding FromRef is required")
	}
	if b.FromField == "" {
		problems = append(problems, where+": binding FromField is required")
	}
	if b.ToArg == "" {
		problems = append(problems, where+": binding ToArg is required")
	}
	return problems
}

// CondOp is a comparison in a [Condition].
type CondOp uint8

// The comparisons. Six, and deliberately no arithmetic, no regular expressions
// and no boolean algebra.
//
// A condition language grows until it is a programming language, and then the
// plan is a program nobody reviews. Anything more complex than these six
// belongs in a tool, where it is testable, ownable and named.
const (
	CondExists CondOp = iota
	CondAbsent
	CondEquals
	CondNotEquals
	CondGreaterThan
	CondLessThan
)

// String renders the operator.
func (o CondOp) String() string {
	switch o {
	case CondAbsent:
		return "absent"
	case CondEquals:
		return "=="
	case CondNotEquals:
		return "!="
	case CondGreaterThan:
		return ">"
	case CondLessThan:
		return "<"
	default:
		return "exists"
	}
}

// Condition gates a step on an earlier step's result.
type Condition struct {
	// FromRef is the producing request's Ref.
	FromRef string
	// Field is the output field to test.
	Field string
	// Op is the comparison.
	Op CondOp
	// Value is the right-hand side, unused by Exists and Absent.
	Value Value
}

func (c Condition) validate(where string) []string {
	var problems []string
	if c.FromRef == "" {
		problems = append(problems, where+": condition FromRef is required")
	}
	if c.Field == "" {
		problems = append(problems, where+": condition Field is required")
	}
	if c.Op > CondLessThan {
		problems = append(problems, fmt.Sprintf("%s: condition has unknown operator %d", where, c.Op))
	}
	return problems
}

// Evaluate tests the condition against a produced result.
//
// A missing source result evaluates FALSE for every operator except Absent.
// The alternative — treating a missing dependency as an error — would turn a
// skipped optional step into a plan failure, which is the opposite of what
// "optional" means.
func (c Condition) Evaluate(results map[string]Result) bool {
	res, ok := results[c.FromRef]
	if !ok {
		return c.Op == CondAbsent
	}
	v, present := res[c.Field]

	switch c.Op {
	case CondExists:
		return present && !v.IsNull()
	case CondAbsent:
		return !present || v.IsNull()
	case CondEquals:
		return present && v.Equal(c.Value)
	case CondNotEquals:
		return !present || !v.Equal(c.Value)
	case CondGreaterThan, CondLessThan:
		if !present {
			return false
		}
		a, aok := v.Flt()
		b, bok := c.Value.Flt()
		if !aok || !bok {
			// A non-numeric comparison is FALSE rather than an error. A plan
			// that fails because a tool returned a string where a number was
			// expected is a plan failing for the contract validator's reason,
			// reported at the wrong place.
			return false
		}
		if c.Op == CondGreaterThan {
			return a > b
		}
		return a < b
	default:
		return false
	}
}

func (r CapabilityRequest) validate(index int, refs map[string]bool, multi bool) []string {
	where := fmt.Sprintf("request %d", index)
	if r.Ref != "" {
		where = "request " + r.Ref
	}

	var problems []string
	if r.Capability == "" {
		problems = append(problems, where+": capability is required")
	}
	if multi && r.Ref == "" {
		problems = append(problems, where+
			": ref is required when an intent has several requests; a dependency "+
			"graph cannot reference an anonymous node")
	}
	for _, dep := range r.DependsOn {
		if !refs[dep] {
			problems = append(problems, fmt.Sprintf("%s: depends on unknown ref %q", where, dep))
		}
		if dep == r.Ref {
			problems = append(problems, fmt.Sprintf("%s: depends on itself", where))
		}
	}
	for _, b := range r.Bindings {
		problems = append(problems, b.validate(where)...)
		if b.FromRef != "" && !refs[b.FromRef] {
			problems = append(problems, fmt.Sprintf("%s: binds from unknown ref %q", where, b.FromRef))
		}
	}
	if r.Condition != nil {
		problems = append(problems, r.Condition.validate(where)...)
		if r.Condition.FromRef != "" && !refs[r.Condition.FromRef] {
			problems = append(problems, fmt.Sprintf(
				"%s: conditions on unknown ref %q", where, r.Condition.FromRef))
		}
	}
	return problems
}

// Validate checks the intent's internal consistency.
//
// Structure only — nothing here consults the registry, so an intent can be
// validated by a caller before the runtime is even reachable. Capability
// resolution failures are the planner's business and produce different errors,
// because "this intent is malformed" and "nothing can serve this today" call
// for entirely different responses.
func (i ToolIntent) Validate() error {
	var problems []string

	if len(i.Requests) == 0 {
		problems = append(problems, "intent: at least one request is required")
	}
	if i.Actor == "" {
		problems = append(problems, "intent: actor is required; an execution with "+
			"no actor cannot be permitted or audited")
	}

	refs := make(map[string]bool, len(i.Requests))
	for _, r := range i.Requests {
		if r.Ref == "" {
			continue
		}
		if refs[r.Ref] {
			problems = append(problems, fmt.Sprintf("intent: duplicate ref %q", r.Ref))
		}
		refs[r.Ref] = true
	}

	multi := len(i.Requests) > 1
	for idx, r := range i.Requests {
		problems = append(problems, r.validate(idx, refs, multi)...)
	}

	if cycle := findCycle(i.Requests); cycle != "" {
		problems = append(problems, "intent: dependency cycle through "+cycle)
	}
	problems = append(problems, i.Budget.validate(Descriptor{Tool: "intent", Version: "0.0.0"})...)

	if len(problems) > 0 {
		sort.Strings(problems)
		return &ConfigError{Problems: problems}
	}
	return nil
}

// findCycle reports a ref involved in a dependency cycle, or empty.
//
// Depth-first with a three-colour marking. A cycle detected here is a caller
// bug caught before any tool runs; a cycle detected during execution would be
// caught by a step waiting forever for a dependency that is waiting for it.
func findCycle(reqs []CapabilityRequest) string {
	deps := make(map[string][]string, len(reqs))
	for _, r := range reqs {
		if r.Ref == "" {
			continue
		}
		edges := append([]string(nil), r.DependsOn...)
		for _, b := range r.Bindings {
			edges = append(edges, b.FromRef)
		}
		if r.Condition != nil {
			edges = append(edges, r.Condition.FromRef)
		}
		deps[r.Ref] = edges
	}

	const (
		white = 0
		grey  = 1
		black = 2
	)
	colour := make(map[string]int, len(deps))

	refs := make([]string, 0, len(deps))
	for ref := range deps {
		refs = append(refs, ref)
	}
	sort.Strings(refs) // deterministic: the same cycle is always reported

	var visit func(string) string
	visit = func(ref string) string {
		switch colour[ref] {
		case grey:
			return ref
		case black:
			return ""
		}
		colour[ref] = grey
		edges := append([]string(nil), deps[ref]...)
		sort.Strings(edges)
		for _, next := range edges {
			if _, known := deps[next]; !known {
				continue
			}
			if found := visit(next); found != "" {
				return found
			}
		}
		colour[ref] = black
		return ""
	}

	for _, ref := range refs {
		if found := visit(ref); found != "" {
			return found
		}
	}
	return ""
}

// Fingerprint returns a stable fingerprint of what the intent asks for.
//
// Covers capability, version constraint and arguments for every request — the
// things that determine what will happen — and deliberately excludes the intent
// ID, correlation and session, which differ between two identical asks. That is
// what makes it usable for deduplication.
func (i ToolIntent) Fingerprint() Fingerprint {
	reqs := append([]CapabilityRequest(nil), i.Requests...)
	sort.Slice(reqs, func(a, b int) bool {
		if reqs[a].Ref != reqs[b].Ref {
			return reqs[a].Ref < reqs[b].Ref
		}
		return reqs[a].Capability < reqs[b].Capability
	})

	var buf []byte
	for _, r := range reqs {
		buf = append(buf, r.Ref...)
		buf = append(buf, '|')
		buf = append(buf, r.Capability...)
		buf = append(buf, '|')
		buf = append(buf, r.Version.String()...)
		buf = append(buf, '|')
		buf = append(buf, r.Args.canonicalBytes()...)
		buf = append(buf, ';')
	}
	return fingerprintOf(buf)
}
