// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/annotations.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.callscreen.contracts.callscreen.common.v1;

