// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/error.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.callscreen.contracts.callscreen.common.v1;

@kotlin.jvm.JvmName("-initializeerror")
public inline fun error(block: com.callscreen.contracts.callscreen.common.v1.ErrorKt.Dsl.() -> kotlin.Unit): com.callscreen.contracts.callscreen.common.v1.Error =
  com.callscreen.contracts.callscreen.common.v1.ErrorKt.Dsl._create(com.callscreen.contracts.callscreen.common.v1.Error.newBuilder()).apply { block() }._build()
/**
 * ```
 * Error is the single error shape returned by every service in the platform.
 * ```
 *
 * Protobuf type `callscreen.common.v1.Error`
 */
public object ErrorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.callscreen.contracts.callscreen.common.v1.Error.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.callscreen.contracts.callscreen.common.v1.Error.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.callscreen.contracts.callscreen.common.v1.Error = _builder.build()

    /**
     * ```
     * Machine-readable classification. Clients branch on this and nothing else.
     * ```
     *
     * `.callscreen.common.v1.ErrorCode code = 1 [json_name = "code"];`
     */
    public var code: com.callscreen.contracts.callscreen.common.v1.ErrorCode
      @JvmName("getCode")
      get() = _builder.code
      @JvmName("setCode")
      set(value) {
        _builder.code = value
      }
    public var codeValue: kotlin.Int
      @JvmName("getCodeValue")
      get() = _builder.codeValue
      @JvmName("setCodeValue")
      set(value) {
        _builder.codeValue = value
      }
    /**
     * ```
     * Machine-readable classification. Clients branch on this and nothing else.
     * ```
     *
     * `.callscreen.common.v1.ErrorCode code = 1 [json_name = "code"];`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * ```
     * Engineer-facing detail. English, never localised, never shown to a user.
     * May name internal components; treated as INTERNAL sensitivity and therefore
     * excluded from any client-visible surface in release builds.
     * ```
     *
     * `string message = 2 [json_name = "message"];`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.message
      @JvmName("setMessage")
      set(value) {
        _builder.message = value
      }
    /**
     * ```
     * Engineer-facing detail. English, never localised, never shown to a user.
     * May name internal components; treated as INTERNAL sensitivity and therefore
     * excluded from any client-visible surface in release builds.
     * ```
     *
     * `string message = 2 [json_name = "message"];`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * ```
     * Localisation key the client resolves against its own string catalogue.
     * Empty when the error is not intended to be surfaced to the user at all.
     * ```
     *
     * `string user_message_key = 3 [json_name = "userMessageKey"];`
     */
    public var userMessageKey: kotlin.String
      @JvmName("getUserMessageKey")
      get() = _builder.userMessageKey
      @JvmName("setUserMessageKey")
      set(value) {
        _builder.userMessageKey = value
      }
    /**
     * ```
     * Localisation key the client resolves against its own string catalogue.
     * Empty when the error is not intended to be surfaced to the user at all.
     * ```
     *
     * `string user_message_key = 3 [json_name = "userMessageKey"];`
     */
    public fun clearUserMessageKey() {
      _builder.clearUserMessageKey()
    }

    /**
     * ```
     * Correlation identifier tying this error to a distributed trace. Shown in
     * support flows so an engineer can locate the exact request.
     * ```
     *
     * `string trace_id = 4 [json_name = "traceId"];`
     */
    public var traceId: kotlin.String
      @JvmName("getTraceId")
      get() = _builder.traceId
      @JvmName("setTraceId")
      set(value) {
        _builder.traceId = value
      }
    /**
     * ```
     * Correlation identifier tying this error to a distributed trace. Shown in
     * support flows so an engineer can locate the exact request.
     * ```
     *
     * `string trace_id = 4 [json_name = "traceId"];`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }

    /**
     * ```
     * Whether retrying the identical request could succeed. Explicit rather than
     * inferred, so that retry behaviour is a contract and not a convention.
     * ```
     *
     * `bool retryable = 5 [json_name = "retryable"];`
     */
    public var retryable: kotlin.Boolean
      @JvmName("getRetryable")
      get() = _builder.retryable
      @JvmName("setRetryable")
      set(value) {
        _builder.retryable = value
      }
    /**
     * ```
     * Whether retrying the identical request could succeed. Explicit rather than
     * inferred, so that retry behaviour is a contract and not a convention.
     * ```
     *
     * `bool retryable = 5 [json_name = "retryable"];`
     */
    public fun clearRetryable() {
      _builder.clearRetryable()
    }

    /**
     * ```
     * How long the client should wait before retrying. Only meaningful when
     * `retryable` is true. Always populated for RATE_LIMITED.
     * ```
     *
     * `.google.protobuf.Duration retry_after = 6 [json_name = "retryAfter"];`
     */
    public var retryAfter: com.google.protobuf.Duration
      @JvmName("getRetryAfter")
      get() = _builder.retryAfter
      @JvmName("setRetryAfter")
      set(value) {
        _builder.retryAfter = value
      }
    /**
     * ```
     * How long the client should wait before retrying. Only meaningful when
     * `retryable` is true. Always populated for RATE_LIMITED.
     * ```
     *
     * `.google.protobuf.Duration retry_after = 6 [json_name = "retryAfter"];`
     */
    public fun clearRetryAfter() {
      _builder.clearRetryAfter()
    }
    /**
     * ```
     * How long the client should wait before retrying. Only meaningful when
     * `retryable` is true. Always populated for RATE_LIMITED.
     * ```
     *
     * `.google.protobuf.Duration retry_after = 6 [json_name = "retryAfter"];`
     * @return Whether the retryAfter field is set.
     */
    public fun hasRetryAfter(): kotlin.Boolean {
      return _builder.hasRetryAfter()
    }

    public val ErrorKt.Dsl.retryAfterOrNull: com.google.protobuf.Duration?
      get() = _builder.retryAfterOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class FieldViolationsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Per-field detail for validation failures. Empty for non-validation errors.
     * ```
     *
     * `repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];`
     */
     public val fieldViolations: com.google.protobuf.kotlin.DslList<com.callscreen.contracts.callscreen.common.v1.FieldViolation, FieldViolationsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.fieldViolationsList
      )
    /**
     * ```
     * Per-field detail for validation failures. Empty for non-validation errors.
     * ```
     *
     * `repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];`
     * @param value The fieldViolations to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addFieldViolations")
    public fun com.google.protobuf.kotlin.DslList<com.callscreen.contracts.callscreen.common.v1.FieldViolation, FieldViolationsProxy>.add(value: com.callscreen.contracts.callscreen.common.v1.FieldViolation) {
      _builder.addFieldViolations(value)
    }
    /**
     * ```
     * Per-field detail for validation failures. Empty for non-validation errors.
     * ```
     *
     * `repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];`
     * @param value The fieldViolations to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignFieldViolations")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.callscreen.contracts.callscreen.common.v1.FieldViolation, FieldViolationsProxy>.plusAssign(value: com.callscreen.contracts.callscreen.common.v1.FieldViolation) {
      add(value)
    }
    /**
     * ```
     * Per-field detail for validation failures. Empty for non-validation errors.
     * ```
     *
     * `repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];`
     * @param values The fieldViolations to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllFieldViolations")
    public fun com.google.protobuf.kotlin.DslList<com.callscreen.contracts.callscreen.common.v1.FieldViolation, FieldViolationsProxy>.addAll(values: kotlin.collections.Iterable<com.callscreen.contracts.callscreen.common.v1.FieldViolation>) {
      _builder.addAllFieldViolations(values)
    }
    /**
     * ```
     * Per-field detail for validation failures. Empty for non-validation errors.
     * ```
     *
     * `repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];`
     * @param values The fieldViolations to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllFieldViolations")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.callscreen.contracts.callscreen.common.v1.FieldViolation, FieldViolationsProxy>.plusAssign(values: kotlin.collections.Iterable<com.callscreen.contracts.callscreen.common.v1.FieldViolation>) {
      addAll(values)
    }
    /**
     * ```
     * Per-field detail for validation failures. Empty for non-validation errors.
     * ```
     *
     * `repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];`
     * @param index The index to set the value at.
     * @param value The fieldViolations to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setFieldViolations")
    public operator fun com.google.protobuf.kotlin.DslList<com.callscreen.contracts.callscreen.common.v1.FieldViolation, FieldViolationsProxy>.set(index: kotlin.Int, value: com.callscreen.contracts.callscreen.common.v1.FieldViolation) {
      _builder.setFieldViolations(index, value)
    }
    /**
     * ```
     * Per-field detail for validation failures. Empty for non-validation errors.
     * ```
     *
     * `repeated .callscreen.common.v1.FieldViolation field_violations = 7 [json_name = "fieldViolations"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearFieldViolations")
    public fun com.google.protobuf.kotlin.DslList<com.callscreen.contracts.callscreen.common.v1.FieldViolation, FieldViolationsProxy>.clear() {
      _builder.clearFieldViolations()
    }


    /**
     * ```
     * Stable identifier of the service that produced the error, matching the
     * directory name under services/. Used to attribute error budget burn.
     * ```
     *
     * `string source_service = 8 [json_name = "sourceService"];`
     */
    public var sourceService: kotlin.String
      @JvmName("getSourceService")
      get() = _builder.sourceService
      @JvmName("setSourceService")
      set(value) {
        _builder.sourceService = value
      }
    /**
     * ```
     * Stable identifier of the service that produced the error, matching the
     * directory name under services/. Used to attribute error budget burn.
     * ```
     *
     * `string source_service = 8 [json_name = "sourceService"];`
     */
    public fun clearSourceService() {
      _builder.clearSourceService()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.callscreen.contracts.callscreen.common.v1.Error.copy(block: `com.callscreen.contracts.callscreen.common.v1`.ErrorKt.Dsl.() -> kotlin.Unit): com.callscreen.contracts.callscreen.common.v1.Error =
  `com.callscreen.contracts.callscreen.common.v1`.ErrorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.callscreen.contracts.callscreen.common.v1.ErrorOrBuilder.retryAfterOrNull: com.google.protobuf.Duration?
  get() = if (hasRetryAfter()) getRetryAfter() else null

