// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/error.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.callscreen.contracts.callscreen.common.v1;

@kotlin.jvm.JvmName("-initializefieldViolation")
public inline fun fieldViolation(block: com.callscreen.contracts.callscreen.common.v1.FieldViolationKt.Dsl.() -> kotlin.Unit): com.callscreen.contracts.callscreen.common.v1.FieldViolation =
  com.callscreen.contracts.callscreen.common.v1.FieldViolationKt.Dsl._create(com.callscreen.contracts.callscreen.common.v1.FieldViolation.newBuilder()).apply { block() }._build()
/**
 * ```
 * FieldViolation identifies a single invalid field within a request.
 * ```
 *
 * Protobuf type `callscreen.common.v1.FieldViolation`
 */
public object FieldViolationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.callscreen.contracts.callscreen.common.v1.FieldViolation.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.callscreen.contracts.callscreen.common.v1.FieldViolation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.callscreen.contracts.callscreen.common.v1.FieldViolation = _builder.build()

    /**
     * ```
     * Dotted path to the offending field, for example "session.caller_number".
     * ```
     *
     * `string field = 1 [json_name = "field"];`
     */
    public var field: kotlin.String
      @JvmName("getField")
      get() = _builder.field
      @JvmName("setField")
      set(value) {
        _builder.field = value
      }
    /**
     * ```
     * Dotted path to the offending field, for example "session.caller_number".
     * ```
     *
     * `string field = 1 [json_name = "field"];`
     */
    public fun clearField() {
      _builder.clearField()
    }

    /**
     * ```
     * Engineer-facing description of why it was rejected.
     * ```
     *
     * `string description = 2 [json_name = "description"];`
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.description
      @JvmName("setDescription")
      set(value) {
        _builder.description = value
      }
    /**
     * ```
     * Engineer-facing description of why it was rejected.
     * ```
     *
     * `string description = 2 [json_name = "description"];`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * ```
     * Localisation key for the message shown to the user beside the input.
     * ```
     *
     * `string user_message_key = 3 [json_name = "userMessageKey"];`
     */
    public var userMessageKey: kotlin.String
      @JvmName("getUserMessageKey")
      get() = _builder.userMessageKey
      @JvmName("setUserMessageKey")
      set(value) {
        _builder.userMessageKey = value
      }
    /**
     * ```
     * Localisation key for the message shown to the user beside the input.
     * ```
     *
     * `string user_message_key = 3 [json_name = "userMessageKey"];`
     */
    public fun clearUserMessageKey() {
      _builder.clearUserMessageKey()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.callscreen.contracts.callscreen.common.v1.FieldViolation.copy(block: `com.callscreen.contracts.callscreen.common.v1`.FieldViolationKt.Dsl.() -> kotlin.Unit): com.callscreen.contracts.callscreen.common.v1.FieldViolation =
  `com.callscreen.contracts.callscreen.common.v1`.FieldViolationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

