// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/annotations.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.callscreen.contracts.callscreen.common.v1;

@kotlin.jvm.JvmName("-initializefieldClassification")
public inline fun fieldClassification(block: com.callscreen.contracts.callscreen.common.v1.FieldClassificationKt.Dsl.() -> kotlin.Unit): com.callscreen.contracts.callscreen.common.v1.FieldClassification =
  com.callscreen.contracts.callscreen.common.v1.FieldClassificationKt.Dsl._create(com.callscreen.contracts.callscreen.common.v1.FieldClassification.newBuilder()).apply { block() }._build()
/**
 * ```
 * FieldClassification is attached to individual fields.
 * ```
 *
 * Protobuf type `callscreen.common.v1.FieldClassification`
 */
public object FieldClassificationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.callscreen.contracts.callscreen.common.v1.FieldClassification.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.callscreen.contracts.callscreen.common.v1.FieldClassification.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.callscreen.contracts.callscreen.common.v1.FieldClassification = _builder.build()

    /**
     * ```
     * How sensitive the field's contents are. Required for any field that could
     * carry user data; the lint rules in CI flag unclassified candidates.
     * ```
     *
     * `.callscreen.common.v1.Sensitivity sensitivity = 1 [json_name = "sensitivity"];`
     */
    public var sensitivity: com.callscreen.contracts.callscreen.common.v1.Sensitivity
      @JvmName("getSensitivity")
      get() = _builder.sensitivity
      @JvmName("setSensitivity")
      set(value) {
        _builder.sensitivity = value
      }
    public var sensitivityValue: kotlin.Int
      @JvmName("getSensitivityValue")
      get() = _builder.sensitivityValue
      @JvmName("setSensitivityValue")
      set(value) {
        _builder.sensitivityValue = value
      }
    /**
     * ```
     * How sensitive the field's contents are. Required for any field that could
     * carry user data; the lint rules in CI flag unclassified candidates.
     * ```
     *
     * `.callscreen.common.v1.Sensitivity sensitivity = 1 [json_name = "sensitivity"];`
     */
    public fun clearSensitivity() {
      _builder.clearSensitivity()
    }

    /**
     * ```
     * How the field is rendered when logged. Defaults are derived from
     * `sensitivity` when this is left unset.
     * ```
     *
     * `.callscreen.common.v1.RedactionStrategy redaction = 2 [json_name = "redaction"];`
     */
    public var redaction: com.callscreen.contracts.callscreen.common.v1.RedactionStrategy
      @JvmName("getRedaction")
      get() = _builder.redaction
      @JvmName("setRedaction")
      set(value) {
        _builder.redaction = value
      }
    public var redactionValue: kotlin.Int
      @JvmName("getRedactionValue")
      get() = _builder.redactionValue
      @JvmName("setRedactionValue")
      set(value) {
        _builder.redactionValue = value
      }
    /**
     * ```
     * How the field is rendered when logged. Defaults are derived from
     * `sensitivity` when this is left unset.
     * ```
     *
     * `.callscreen.common.v1.RedactionStrategy redaction = 2 [json_name = "redaction"];`
     */
    public fun clearRedaction() {
      _builder.clearRedaction()
    }

    /**
     * ```
     * How long the field's value may be retained.
     * ```
     *
     * `.callscreen.common.v1.Retention retention = 3 [json_name = "retention"];`
     */
    public var retention: com.callscreen.contracts.callscreen.common.v1.Retention
      @JvmName("getRetention")
      get() = _builder.retention
      @JvmName("setRetention")
      set(value) {
        _builder.retention = value
      }
    public var retentionValue: kotlin.Int
      @JvmName("getRetentionValue")
      get() = _builder.retentionValue
      @JvmName("setRetentionValue")
      set(value) {
        _builder.retentionValue = value
      }
    /**
     * ```
     * How long the field's value may be retained.
     * ```
     *
     * `.callscreen.common.v1.Retention retention = 3 [json_name = "retention"];`
     */
    public fun clearRetention() {
      _builder.clearRetention()
    }

    /**
     * ```
     * When true, the field must never leave its origin region. Enforced by the
     * egress policy in the platform HTTP and Kafka clients.
     * ```
     *
     * `bool residency_bound = 4 [json_name = "residencyBound"];`
     */
    public var residencyBound: kotlin.Boolean
      @JvmName("getResidencyBound")
      get() = _builder.residencyBound
      @JvmName("setResidencyBound")
      set(value) {
        _builder.residencyBound = value
      }
    /**
     * ```
     * When true, the field must never leave its origin region. Enforced by the
     * egress policy in the platform HTTP and Kafka clients.
     * ```
     *
     * `bool residency_bound = 4 [json_name = "residencyBound"];`
     */
    public fun clearResidencyBound() {
      _builder.clearResidencyBound()
    }

    /**
     * ```
     * Free-text justification recorded in the generated data map. Required for
     * SENSITIVE and SECRET fields so that the compliance review has context.
     * ```
     *
     * `string purpose = 5 [json_name = "purpose"];`
     */
    public var purpose: kotlin.String
      @JvmName("getPurpose")
      get() = _builder.purpose
      @JvmName("setPurpose")
      set(value) {
        _builder.purpose = value
      }
    /**
     * ```
     * Free-text justification recorded in the generated data map. Required for
     * SENSITIVE and SECRET fields so that the compliance review has context.
     * ```
     *
     * `string purpose = 5 [json_name = "purpose"];`
     */
    public fun clearPurpose() {
      _builder.clearPurpose()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.callscreen.contracts.callscreen.common.v1.FieldClassification.copy(block: `com.callscreen.contracts.callscreen.common.v1`.FieldClassificationKt.Dsl.() -> kotlin.Unit): com.callscreen.contracts.callscreen.common.v1.FieldClassification =
  `com.callscreen.contracts.callscreen.common.v1`.FieldClassificationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

