// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callscreen/common/v1/types.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.callscreen.contracts.callscreen.common.v1;

@kotlin.jvm.JvmName("-initializepageRequest")
public inline fun pageRequest(block: com.callscreen.contracts.callscreen.common.v1.PageRequestKt.Dsl.() -> kotlin.Unit): com.callscreen.contracts.callscreen.common.v1.PageRequest =
  com.callscreen.contracts.callscreen.common.v1.PageRequestKt.Dsl._create(com.callscreen.contracts.callscreen.common.v1.PageRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * PageRequest is the standard forward-only pagination request.
 *
 * Cursor-based rather than offset-based: offset pagination degrades badly on
 * large tables and produces duplicate or skipped rows when the underlying data
 * changes between pages, which it always does in a live call log.
 * ```
 *
 * Protobuf type `callscreen.common.v1.PageRequest`
 */
public object PageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.callscreen.contracts.callscreen.common.v1.PageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.callscreen.contracts.callscreen.common.v1.PageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.callscreen.contracts.callscreen.common.v1.PageRequest = _builder.build()

    /**
     * ```
     * Maximum items to return. The server clamps this to its own ceiling rather
     * than rejecting an oversized request, so clients never need to know the cap.
     * ```
     *
     * `int32 page_size = 1 [json_name = "pageSize"];`
     */
    public var pageSize: kotlin.Int
      @JvmName("getPageSize")
      get() = _builder.pageSize
      @JvmName("setPageSize")
      set(value) {
        _builder.pageSize = value
      }
    /**
     * ```
     * Maximum items to return. The server clamps this to its own ceiling rather
     * than rejecting an oversized request, so clients never need to know the cap.
     * ```
     *
     * `int32 page_size = 1 [json_name = "pageSize"];`
     */
    public fun clearPageSize() {
      _builder.clearPageSize()
    }

    /**
     * ```
     * Opaque cursor from a previous PageResponse. Empty requests the first page.
     * ```
     *
     * `string page_token = 2 [json_name = "pageToken"];`
     */
    public var pageToken: kotlin.String
      @JvmName("getPageToken")
      get() = _builder.pageToken
      @JvmName("setPageToken")
      set(value) {
        _builder.pageToken = value
      }
    /**
     * ```
     * Opaque cursor from a previous PageResponse. Empty requests the first page.
     * ```
     *
     * `string page_token = 2 [json_name = "pageToken"];`
     */
    public fun clearPageToken() {
      _builder.clearPageToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.callscreen.contracts.callscreen.common.v1.PageRequest.copy(block: `com.callscreen.contracts.callscreen.common.v1`.PageRequestKt.Dsl.() -> kotlin.Unit): com.callscreen.contracts.callscreen.common.v1.PageRequest =
  `com.callscreen.contracts.callscreen.common.v1`.PageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

